// Offline test launcher/checker; never imported into native cognition.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {training} from './cases.mjs';import {sexp,parse} from './fixtures.mjs';import {verify,signatures} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC04\/attempt-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});
const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');
process.on('uncaughtException',e=>{save('failure.json',{status:'FAIL',message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
save('opening.json',checkOpen('docs/gates/SC04/plan.json'));const cases=training();save('cases.json',cases);
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');
save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),model_calls:0,services_touched:[],runtime:'PeTTa/MeTTa with Prolog lexical membrane; JavaScript outside runtime'});
for(const p of ['scripts/sc04/run.mjs','scripts/sc04/cases.mjs','scripts/sc04/fixtures.mjs','scripts/sc04/verify.mjs','effect_membranes/miter_language.pl','src/participation.metta','constitution/soul_compass_v02.metta','tests/fixtures/sc04/contract.md'])save(p.split('/').at(-1),fs.readFileSync(p,'utf8'));
const language=fs.readFileSync('src/grounded_language.metta','utf8'),support=fs.readFileSync('src/participation_support.metta','utf8');const runs={};
const variants={canonical:null,'sever-semantic':['language','(== $claims (index-atom $p 6))','true'],'sever-span':['language','(== (index-atom $r 3) (span (index-atom $p 4) (index-atom $p 5)))','true'],'sever-participation':['support','(== (index-atom $payload 2) (index-atom $request 1))','false'],restored:null};
for(const [variant,mutation] of Object.entries(variants)){
 let l=language,s=support;if(mutation){const [which,a,b]=mutation;const old=which==='language'?l:s;assert.equal(old.split(a).length,2);if(which==='language')l=l.replace(a,b);else s=s.replace(a,b)}save(variant+'-language.metta',l);save(variant+'-support.metta',s);
 const bootstrap=`!(import! &self (library lib_import))\n!(import_prolog_functions_from_file "${root}/${out}/miter_language.pl" (miter_language_tokens))\n!(import! &compass "${root}/${out}/soul_compass_v02.metta")\n!(import! &self "${root}/${out}/participation.metta")\n!(import! &self "${root}/${out}/${variant}-support.metta")\n!(import! &self "${root}/${out}/${variant}-language.metta")\n`;
 const entries=cases.map(c=>`!(let $r (GroundLanguage ${[c.scope,c.nodes,c.registry,c.current,c.operations,c.target,c.budget,c.proposals].map(sexp).join(' ')}) (case-result ${c.id} $r))`).join('\n');save(variant+'-entry.metta',bootstrap+entries+'\n');
 const start=performance.now(),r=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/'+variant+'-entry.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:32*1024*1024});save(variant+'.stdout',r.stdout??'');save(variant+'.stderr',r.stderr??'');save(variant+'-process.json',{status:r.status,signal:r.signal,error:r.error?.message??null,elapsed_ms:performance.now()-start});assert.equal(r.status,0,variant+' process');assert.equal(r.stderr,'',variant+' stderr');
 const lines=r.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(l=>l.startsWith('(case-result '));assert.equal(lines.length,cases.length,variant+' evaluated result count');runs[variant]=Object.fromEntries(lines.map(l=>{const x=parse(l);return[x[1],x[2]]}));save(variant+'-results.json',runs[variant]);
}
let checked=0;for(const c of cases){try{verify(c,runs.canonical[c.id]);verify(c,runs.restored[c.id]);assert.deepEqual(runs.canonical[c.id],runs.restored[c.id]);checked++;}catch(e){e.message=c.id+': '+e.message;throw e}}
const assessment=(variant,id)=>runs[variant][id][3][1][0][0];assert.equal(assessment('canonical','supported-proposal'),'candidate-with-native-support');
for(const id of ['invented-proposal','forged-span'])assert.equal(assessment('canonical',id),'candidate-needs-independent-support');
assert.equal(assessment('canonical','malformed-proposal'),'candidate-malformed');assert.equal(assessment('sever-semantic','invented-proposal'),'candidate-with-native-support');assert.equal(assessment('sever-span','forged-span'),'candidate-with-native-support');
assert(signatures(runs['sever-participation'].canonical).includes('["direct-change"]'));assert(!signatures(runs.canonical.canonical).includes('["direct-change"]'));
save('verdict.json',{status:'PASS-BOUNDED',gate:'SC04',phase:'training-and-counterfactual',cases:checked,variants:Object.keys(variants),source_sha256:hash(language),limits:'Finite controlled language and fixture model proposals; no held-out or live-model claim yet.'});console.log(JSON.stringify({status:'PASS-BOUNDED',cases:checked,variants:Object.keys(variants).length,evidence:out}));
