// Builder fixtures and independent evidence checks. No adapter implementation is supplied here.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {save,read,native,sexp,parse,swi,petta} from '../g22_v2/common.mjs';
process.chdir(root);const number=process.argv[2];assert.match(number??'',/^00[1-5]$/);const dir=root+'/evidence/G28/attempt-'+number,W=root+'/runtime/g27/attempt-28'+number;assert(!fs.existsSync(dir)&&!fs.existsSync(W));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(W,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});save(dir+'/opening.json',checkOpen('docs/gates/G28/plan.json'));
const files=[...new Set([...read(root+'/evidence/G27/attempt-004/freeze.json').files.map(x=>x.path),
 ...read(root+'/evidence/G24/g26-003/repair-003/freeze.json').files.map(x=>x.path),
 ...['src/executable_development_v1.metta','src/bootstrap_executable_development_v1.metta','effect_membranes/miter_executable_development_v1.pl','config/executable-candidate-schema-v1.json','config/local/g03-model-profiles.json','scripts/g28/run.mjs'].map(x=>root+'/'+x)])];
const pins=files.map(path=>({path,sha256:hash(fs.readFileSync(path))}));save(dir+'/freeze.json',{files:pins,model_alias:'qwen-local',max_calls:2,max_tokens_per_call:1024,deadline_per_call_seconds:120,standing:'Finite synthetic source contract; actual local-model candidate, no builder implementation'});fs.mkdirSync(dir+'/code');for(const f of files.filter(p=>!p.includes('/config/local/')))fs.copyFileSync(f,dir+'/code/'+f.slice(root.length+1).replaceAll('/','__'));
const docker='/Applications/Docker.app/Contents/Resources/bin/docker';const dockerRun=args=>execFileSync(docker,args,{encoding:'utf8',timeout:20000,maxBuffer:1024*1024});save(dir+'/services-before.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
const seed=W+'/seed';fs.mkdirSync(seed);const git=args=>execFileSync('/usr/bin/git',['-c','core.hooksPath=/dev/null','-C',seed,...args],{encoding:'utf8'}).trim();git(['init','-b','main']);for(const sub of ['extension','candidate_tests']){fs.mkdirSync(seed+'/'+sub);save(seed+'/'+sub+'/.gitkeep','')}save(seed+'/CONTROL.txt','G28 fixed laboratory base; no executable adapter installed\n');git(['add','CONTROL.txt','extension/.gitkeep','candidate_tests/.gitkeep']);git(['-c','user.name=Miter laboratory builder','-c','user.email=miter-lab@example.invalid','commit','-m','Pin G28 missing-adapter baseline']);const base=git(['rev-parse','HEAD']);
const values=[['ordinary','A source-bound record'],['empty',''],['unicode','Léa — 你好 🌱'],['multiline','first\nsecond\n'],['literal','literal $(printf hijacked); `printf x` \\ $HOME'],['spaces','  retain these spaces  ']];
const cases=values.map(([id,text])=>['io-case',id,text,[...Buffer.from(text+'\n')]]),contracts=W+'/contracts';fs.mkdirSync(contracts);const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
for(const[id,text]of values)save(contracts+'/'+id+'.sh','exec /bin/sh /workspace/extension/adapter.sh '+quote(text)+'\n');save(contracts+'/candidate-smoke.sh','cd /workspace\nexec /bin/sh /workspace/candidate_tests/smoke.sh\n');
const tests=[...values.map(x=>x[0]),'candidate-smoke'];const grantId='g28-grant-'+number,grant={schema:'miter-workshop-grant-v1',grant_id:grantId,project_scope:'G28',repository:seed,contracts,base_commit:base,tests:tests.map(id=>({id})),integrity:[...pins,...tests.map(id=>({path:contracts+'/'+id+'.sh',sha256:hash(fs.readFileSync(contracts+'/'+id+'.sh'))}))]};save(W+'/grant.json',grant);save(dir+'/workshop-grant.json',grant);
const scope=['scope','cut-g28','principal-fixture','project-g28','isolated-builder-lab'],contract=['executable-contract','stdout-source-contract','stdout-record-v1','utf8-argument-v1','same-bytes-plus-lf-v1','Transport one given UTF-8 payload unchanged with exactly one appended LF; do not evaluate it or decide its meaning.',cases];
const payloads=[['contract-source',contract],['inventory-source',['capability-inventory','complete',scope,[]]],['grant-source',['executable-grant','stdout-source-contract',grantId,2,1024,120]]];const nodes=payloads.map(([id,p])=>['node',id,'human-confirmation',[scope[2]],scope[3],'v1',p,[]]);const input=['executable-input','native-stdout-development',scope,nodes,nodes.map(n=>['observation',...structuredClone(n.slice(1,7))]),nodes.map(n=>['at',n[1],'v1']),'contract-source','inventory-source','grant-source'];
save(dir+'/input.json',{native:input,standing:'Builder fixture-admitted contract and bounded inventory, not authenticated live ingress'});save(dir+'/context.json',{schema:'miter-executable-context-v1',workshop_root:W,chat_context:[]});save(dir+'/manifest.json',{files:[...pins,...['input.json','context.json'].map(f=>({path:dir+'/'+f,sha256:hash(fs.readFileSync(dir+'/'+f))}))]});
const boot=`!(import! &self "${root}/src/bootstrap_executable_development_v1.metta")\n!(add-atom &soul (protected-canary Soul))\n`;
// Exact source-proof and contract-comparison controls before any model request.
const variants={canonical:structuredClone(input),available:structuredClone(input),unknown:structuredClone(input),generated:structuredClone(input),foreign:structuredClone(input),neutral:structuredClone(input)};
for(const table of [variants.available[3],variants.available[4]])table.find(n=>n[1]==='inventory-source')[6][3]=['stdout-record-v1'];for(const table of [variants.unknown[3],variants.unknown[4]])table.find(n=>n[1]==='inventory-source')[6][1]='incomplete';for(const table of [variants.generated[3],variants.generated[4]])table.find(n=>n[1]==='contract-source')[2]='generation';for(const table of [variants.foreign[3],variants.foreign[4]])table.find(n=>n[1]==='grant-source')[3]=['another-principal'];variants.neutral[1]='neutral-undertaking-id';
// The console printer emits literal multiline strings. Probe only scalar tags;
// full load-bearing values are captured with the typed wx_save codec below.
const probes=native(dir,'source-probes',Object.entries(variants).map(([id,v])=>`!(result ${id} (let $o (XOpportunity ${sexp(v)}) (index-atom $o 0)))`).join('\n'),boot);assert.equal(probes.length,6);const kinds=Object.fromEntries(probes.map(x=>[x[1],x[2]]));assert.equal(kinds.canonical,'executable-opportunity');assert.equal(kinds.neutral,'executable-opportunity');assert.equal(kinds.available,'executable-development-not-needed');for(const k of ['unknown','generated','foreign'])assert.equal(kinds[k],'executable-development-held');assert(!fs.readdirSync(dir).some(f=>f.endsWith('-raw.json')));
const actual=cases.map(c=>['io-observation',c[1],0,c[3]]),corrupt=structuredClone(actual);corrupt[0][3]=[0];const src=fs.readFileSync('src/executable_development_v1.metta','utf8');
const start=src.indexOf('(= (XCheck '),end=src.indexOf('(= (XCompare ',start);assert(start>=0&&end>start);save(dir+'/comparison-severed-code.metta',src.slice(0,start)+'(= (XCheck $cases $observations) true)\n'+src.slice(end));
const compare=`!(result good (let $r (XCompare ${sexp(cases)} ${sexp(actual)}) (index-atom $r 0)))\n!(result corrupt (let $r (XCompare ${sexp(cases)} ${sexp(corrupt)}) (index-atom $r 0)))`;
const canonical=native(dir,'comparison-canonical',compare,boot);assert.equal(canonical[0][2],'executable-trial-qualified');assert.equal(canonical[1][2],'executable-trial-unqualified');const severBoot=`!(import! &self "${root}/src/bootstrap_grounded_language.metta")\n!(import! &self "${dir}/comparison-severed-code.metta")\n`;const severed=native(dir,'comparison-severed',compare,severBoot);assert.equal(severed[1][2],'executable-trial-qualified');assert.deepEqual(native(dir,'comparison-restored',compare,boot),canonical);
// Parent has no adapter. Test through the same real broker before generation.
const parentBoot=`!(import! &self "${root}/src/bootstrap_workshop_boundary_v1.metta")\n`;
function brokerProbe(id,op,extra={},candidate='parent'){const req={schema:'miter-workshop-request-v1',request_id:id,idempotency_key:id,grant_id:grantId,operation:op,candidate_id:candidate,...extra};save(W+'/request-'+id+'.json',req);return native(dir,id,`!(result probe (WorkshopRequest "${W}" "request-${id}.json"))`,parentBoot)[0][2]}
assert.equal(brokerProbe('parent-create','create_candidate_worktree')[2],'candidate-created');const parent=brokerProbe('parent-trial','run_declared_test',{test_id:'ordinary'});assert.equal(parent[2],'test-failed');assert.equal(brokerProbe('main-write','write_candidate_file',{path:'../seed/CONTROL.txt',contents:'forbidden'})[2],'operation-denied');
const entry=dir+'/execute.metta';save(entry,boot+`!(result outcome (let $result (XRun "${dir}") (wx_save "${dir}" final $result)))\n!(result state (wx_save "${dir}" atomspace ((collapse (match &trial $a $a)) (collapse (match &derived $a $a)) (collapse (match &soul $a $a)))))\n`);const began=Date.now();const p=spawnSync(swi,['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',entry,'silent'],{encoding:'utf8',timeout:300000,maxBuffer:128*1024*1024});save(dir+'/execute.stdout',p.stdout??'');save(dir+'/execute.stderr',p.stderr??'');save(dir+'/execute-process.json',{status:p.status,signal:p.signal,error:p.error?.message,started_at:new Date(began).toISOString(),elapsed_ms:Date.now()-began});assert.equal(p.status,0);assert.equal(p.stderr,'');const final=read(dir+'/final.json').native;assert.equal(final[0],'executable-awaiting-approval',JSON.stringify(final));
const proposal=final[1],candidate=proposal[2],id=candidate[1],product=read(dir+'/'+id+'-product.json'),raw=read(dir+'/'+id+'-raw.json');assert.deepEqual(JSON.parse(raw.choices[0].message.content),product);assert.equal(product.candidate_id,id);assert.equal(candidate[0],'executable-candidate');
const filesActual=[];for(const f of product.files){const path=W+'/candidates/'+id+'/'+f.path;assert.equal(fs.readFileSync(path,'utf8'),f.contents);filesActual.push({path:f.path,sha256:hash(fs.readFileSync(path))})}assert.equal(git(['rev-parse','refs/heads/main']),base);assert.equal(git(['status','--porcelain']),'');assert.equal(fs.readFileSync(seed+'/CONTROL.txt','utf8'),'G28 fixed laboratory base; no executable adapter installed\n');
const trial=proposal[3];assert.equal(trial[1][0],'executable-candidate');assert.equal(trial[2][0],'executable-trial-qualified');assert.deepEqual(trial[2][2],actual);assert.equal(final[2][2],'promotion-proposed');const commitEvent=read(W+'/events/'+proposal[4][3]+'.json');const commit=commitEvent.payload.details.commit;assert.equal(execFileSync('/usr/bin/git',['-C',W+'/candidates/'+id,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),commit);assert.notEqual(commit,base);
const allModelRaw=fs.readdirSync(dir).filter(x=>/^executable-[12]-raw[.]json$/.test(x));assert(allModelRaw.length>=1&&allModelRaw.length<=2);for(const f of pins)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
save(dir+'/services-after.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
save(dir+'/git-history.txt',git(['log','--all','--graph','--decorate','--format=%h %s']));git(['bundle','create',dir+'/candidate-history.bundle','--all']);save(dir+'/candidate-files.json',filesActual);save(dir+'/approval-request.json',{standing:'AWAITING-EXPLICIT-HUMAN-APPROVAL',candidate_id:id,commit,parent:base,files:filesActual,model_calls:allModelRaw.length,target:'Isolated laboratory main branch and registry only; no live service or external network',purpose:product.manifest.purpose,rollback:'Retain prior base revision; no external effect to undo',tests:cases.map(c=>c[1]),candidate_test:'candidate-smoke',not_promoted:true});
for(const sub of ['journal','events','receipts','prepared','states','request-ids'])fs.cpSync(W+'/'+sub,dir+'/'+sub,{recursive:true});for(const f of product.files){const to=dir+'/candidate/'+f.path;fs.mkdirSync(to.slice(0,to.lastIndexOf('/')),{recursive:true});fs.copyFileSync(W+'/candidates/'+id+'/'+f.path,to)}
save(dir+'/verdict.json',{status:'AWAITING-APPROVAL',native_authorship:'bounded-source-grounded-model-candidate',source_probes:kinds,contract_cases:cases.length,model_calls:allModelRaw.length,commit,main_unchanged:true,candidate_bytes_match_raw_model:true,comparison_severed_and_restored:true,not_promoted:true,limits:'Finite nonnetworked sample adapter, not Mattermost or general autonomous software capability'});console.log(JSON.stringify(read(dir+'/verdict.json')));
