// Builder fixtures and independent evidence checks. No adapter implementation is supplied here.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {save,read,native,sexp,parse,swi,petta} from '../g22_v2/common.mjs';
process.chdir(root);const number=process.argv[2];assert.match(number??'',/^002$/);const dir=root+'/evidence/G28-R1/attempt-'+number,W=root+'/runtime/g27/attempt-281'+number.slice(1);assert(!fs.existsSync(dir)&&!fs.existsSync(W));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(W,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});save(dir+'/opening.json',checkOpen('docs/gates/G28/R1/plan.json'));
const files=[...new Set([...read(root+'/evidence/G27/attempt-004/freeze.json').files.map(x=>x.path),
 ...read(root+'/evidence/G24/g26-003/repair-003/freeze.json').files.map(x=>x.path),
 ...['src/development_continuation_v1.metta','effect_membranes/miter_model_stream_v1.pl','src/executable_development_v2.metta','src/bootstrap_executable_development_v2.metta','effect_membranes/miter_executable_development_v2.pl','effect_membranes/miter_llm.pl','config/executable-candidate-schema-v2.json','config/local/g03-model-profiles.json','scripts/g28_r1/run.mjs','scripts/g28_r1/replay.mjs','scripts/g28_r1/preflight.pl'].map(x=>root+'/'+x)])];
const pins=files.map(path=>({path,sha256:hash(fs.readFileSync(path))}));save(dir+'/freeze.json',{files:pins,model_alias:'qwen-local',max_calls:2,max_tokens_per_call:2048,deadline_per_call_seconds:300,standing:'Finite synthetic source contract; actual local-model candidate, no builder implementation'});fs.mkdirSync(dir+'/code');for(const f of files.filter(p=>!p.includes('/config/local/')))fs.copyFileSync(f,dir+'/code/'+f.slice(root.length+1).replaceAll('/','__'));
const docker='/Applications/Docker.app/Contents/Resources/bin/docker';const dockerRun=args=>execFileSync(docker,args,{encoding:'utf8',timeout:20000,maxBuffer:1024*1024});save(dir+'/services-before.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
const seed=W+'/seed';fs.mkdirSync(seed);const git=args=>execFileSync('/usr/bin/git',['-c','core.hooksPath=/dev/null','-C',seed,...args],{encoding:'utf8'}).trim();git(['init','-b','main']);for(const sub of ['extension','candidate_tests']){fs.mkdirSync(seed+'/'+sub);save(seed+'/'+sub+'/.gitkeep','')}save(seed+'/CONTROL.txt','G28 fixed laboratory base; no executable adapter installed\n');git(['add','CONTROL.txt','extension/.gitkeep','candidate_tests/.gitkeep']);git(['-c','user.name=Miter laboratory builder','-c','user.email=miter-lab@example.invalid','commit','-m','Pin G28 missing-adapter baseline']);const base=git(['rev-parse','HEAD']);
const values=[['ordinary','A source-bound record'],['empty',''],['unicode','Léa — 你好 🌱'],['multiline','first\nsecond\n'],['literal','literal $(printf hijacked); `printf x` \\ $HOME'],['spaces','  retain these spaces  ']];
const cases=values.map(([id,text])=>['io-case',id,text,[...Buffer.from(text+'\n')]]),contracts=W+'/contracts';fs.mkdirSync(contracts);const quote=s=>"'"+s.replaceAll("'","'\\''")+"'";
for(const[id,text]of values)save(contracts+'/'+id+'.sh','exec /bin/sh /workspace/extension/adapter.sh '+quote(text)+'\n');save(contracts+'/candidate-smoke.sh','cd /workspace\nexec /bin/sh /workspace/candidate_tests/smoke.sh\n');
const tests=[...values.map(x=>x[0]),'candidate-smoke'];const grantId='g28-grant-001',grant={schema:'miter-workshop-grant-v1',grant_id:grantId,project_scope:'G28',repository:seed,contracts,base_commit:base,tests:tests.map(id=>({id})),integrity:[...pins,...tests.map(id=>({path:contracts+'/'+id+'.sh',sha256:hash(fs.readFileSync(contracts+'/'+id+'.sh'))}))]};save(W+'/grant.json',grant);save(dir+'/workshop-grant.json',grant);
const scope=['scope','cut-g28','principal-fixture','project-g28','isolated-builder-lab'],contract=['executable-contract','stdout-source-contract','stdout-record-v1','utf8-argument-v1','same-bytes-plus-lf-v1','Transport one given UTF-8 payload unchanged with exactly one appended LF; do not evaluate it or decide its meaning.',cases];
const payloads=[['contract-source',contract],['inventory-source',['capability-inventory','complete',scope,[]]],['grant-source',['executable-grant','stdout-source-contract',grantId,2,2048,300]]];const nodes=payloads.map(([id,p])=>['node',id,'human-confirmation',[scope[2]],scope[3],'v1',p,[]]);const input=['executable-input','native-stdout-development',scope,nodes,nodes.map(n=>['observation',...structuredClone(n.slice(1,7))]),nodes.map(n=>['at',n[1],'v1']),'contract-source','inventory-source','grant-source'];
save(dir+'/input.json',{native:input,standing:'Builder fixture-admitted contract and bounded inventory, not authenticated live ingress'});save(dir+'/context.json',{schema:'miter-executable-context-v2',workshop_root:W,chat_context:[]});save(dir+'/manifest.json',{files:[...pins,...['input.json','context.json'].map(f=>({path:dir+'/'+f,sha256:hash(fs.readFileSync(dir+'/'+f))}))]});
const diagnostic=read(root+'/evidence/G28-R1/diagnostic-013/verdict.json');assert.equal(diagnostic.status,'PASS-BOUNDED');for(const f of read(root+'/evidence/G28-R1/diagnostic-013/freeze.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
const boot=`!(import! &self "${root}/src/bootstrap_executable_development_v2.metta")\n!(add-atom &soul (protected-canary Soul))\n`;
// Exact source-proof and contract-comparison controls before any model request.
const variants={canonical:structuredClone(input),available:structuredClone(input),unknown:structuredClone(input),generated:structuredClone(input),foreign:structuredClone(input),neutral:structuredClone(input)};
for(const table of [variants.available[3],variants.available[4]])table.find(n=>n[1]==='inventory-source')[6][3]=['stdout-record-v1'];for(const table of [variants.unknown[3],variants.unknown[4]])table.find(n=>n[1]==='inventory-source')[6][1]='incomplete';for(const table of [variants.generated[3],variants.generated[4]])table.find(n=>n[1]==='contract-source')[2]='generation';for(const table of [variants.foreign[3],variants.foreign[4]])table.find(n=>n[1]==='grant-source')[3]=['another-principal'];variants.neutral[1]='neutral-undertaking-id';
// The console printer emits literal multiline strings. Probe only scalar tags;
// full load-bearing values are captured with the typed wy_save codec below.
const probes=native(dir,'source-probes',Object.entries(variants).map(([id,v])=>`!(result ${id} (let $o (YOpportunity ${sexp(v)}) (index-atom $o 0)))`).join('\n'),boot);assert.equal(probes.length,6);const kinds=Object.fromEntries(probes.map(x=>[x[1],x[2]]));assert.equal(kinds.canonical,'executable-opportunity');assert.equal(kinds.neutral,'executable-opportunity');assert.equal(kinds.available,'executable-development-not-needed');for(const k of ['unknown','generated','foreign'])assert.equal(kinds[k],'executable-development-held');assert(!fs.readdirSync(dir).some(f=>f.endsWith('-request.json')));
const actual=cases.map(c=>['io-observation',c[1],0,c[3]]),corrupt=structuredClone(actual);corrupt[0][3]=[0];const src=fs.readFileSync('src/executable_development_v2.metta','utf8');
const start=src.indexOf('(= (YCheck '),end=src.indexOf('(= (YCompare ',start);assert(start>=0&&end>start);save(dir+'/comparison-severed-code.metta',src.slice(0,start)+'(= (YCheck $cases $observations) true)\n'+src.slice(end));
const compare=`!(result good (let $r (YCompare ${sexp(cases)} ${sexp(actual)}) (index-atom $r 0)))\n!(result corrupt (let $r (YCompare ${sexp(cases)} ${sexp(corrupt)}) (index-atom $r 0)))`;
const canonical=native(dir,'comparison-canonical',compare,boot);assert.equal(canonical[0][2],'executable-trial-qualified');assert.equal(canonical[1][2],'executable-trial-unqualified');const severBoot=`!(import! &self "${root}/src/bootstrap_grounded_language.metta")\n!(import! &self "${dir}/comparison-severed-code.metta")\n`;const severed=native(dir,'comparison-severed',compare,severBoot);assert.equal(severed[1][2],'executable-trial-qualified');assert.deepEqual(native(dir,'comparison-restored',compare,boot),canonical);
// An unanswered prepared request is diagnostic data, never a new inference.
save(dir+'/replay-probe-request.json',{standing:'SYNTHETIC unsent replay fixture, not an actual model request'});
const replayBoot=boot+`!(import_prolog_functions_from_file "${root}/scripts/g28_r1/preflight.pl" (pf_question))\n`;
const replay=native(dir,'pre-inference-replay',`
!(result opportunity (let $o (YOpportunity (wy_input "${dir}")) (wy_save "${dir}" opportunity $o)))
!(result unstaged (let $r (wy_model "${dir}" (pf_question "${dir}")) (index-atom $r 0)))
!(result unknown (let $r (wy_input "/unknown") (index-atom $r 0)))
!(result forged (let $r (wy_observe "${dir}" ordinary (workshop-result fake test-completed fake hash)) (index-atom $r 0)))
!(result replay (let* (($q (pf_question "${dir}")) ($s (add-atom &derived (executable-generation-pending "${dir}" $q))) ($r (wy_model "${dir}" $q)) ($c (remove-atom &derived (executable-generation-pending "${dir}" $q)))) (index-atom $r 2)))
`,replayBoot);
assert.deepEqual(replay.map(x=>x[2]),['stored','model-unavailable','executable-input-unavailable','io-incomplete','unknown_after_preparation']);
assert(!fs.existsSync(dir+'/replay-probe-wire.json'));assert(fs.existsSync(root+'/evidence/G28-R1/call-1.claim')&&fs.existsSync(root+'/evidence/G28-R1/call-2.claim'));
save(dir+'/pre-inference-verdict.json',{no_new_inference:true,observations:replay,synthetic_replay_fixture:true});
// Parent has no adapter. Test through the same real broker before generation.
const parentBoot=`!(import! &self "${root}/src/bootstrap_workshop_boundary_v1.metta")\n`;
function brokerProbe(id,op,extra={},candidate='parent'){const req={schema:'miter-workshop-request-v1',request_id:id,idempotency_key:id,grant_id:grantId,operation:op,candidate_id:candidate,...extra};save(W+'/request-'+id+'.json',req);return native(dir,id,`!(result probe (WorkshopRequest "${W}" "request-${id}.json"))`,parentBoot)[0][2]}
assert.equal(brokerProbe('parent-create','create_candidate_worktree')[2],'candidate-created');const parent=brokerProbe('parent-trial','run_declared_test',{test_id:'ordinary'});assert.equal(parent[2],'test-failed');assert.equal(brokerProbe('main-write','write_candidate_file',{path:'../seed/CONTROL.txt',contents:'forbidden'})[2],'operation-denied');
// Replay the first historical response only under the EXACT original question.
// Never associate the second historical answer with a newly changed question.
for(const suffix of ['template','request','generation','wire','header','timing','observation']){
 const f='executable-1-'+suffix+'.json';fs.copyFileSync(root+'/evidence/G28-R1/attempt-001/'+f,dir+'/'+f);
}
save(dir+'/replay-origin.json',{standing:'NO-INFERENCE response reuse and repaired-consumer test; not new model authorship',origin:'evidence/G28-R1/attempt-001',reused:'executable-1',second_response_not_reused:true});
const entry=dir+'/execute.metta';save(entry,boot+`!(result outcome (let $result (YRun "${dir}") (wy_save "${dir}" final $result)))\n!(result state (wy_save "${dir}" atomspace ((collapse (match &trial $a $a)) (collapse (match &derived $a $a)) (collapse (match &soul $a $a)))))\n`);const began=Date.now();const p=spawnSync(swi,['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',entry,'silent'],{encoding:'utf8',timeout:720000,maxBuffer:128*1024*1024});save(dir+'/execute.stdout',p.stdout??'');save(dir+'/execute.stderr',p.stderr??'');save(dir+'/execute-process.json',{status:p.status,signal:p.signal,error:p.error?.message,started_at:new Date(began).toISOString(),elapsed_ms:Date.now()-began});assert.equal(p.status,0);assert.equal(p.stderr,'');const final=read(dir+'/final.json').native;assert.equal(final[0],'executable-development-incomplete');
const trial=read(dir+'/trial-1.json').native,candidate=trial[1];
assert.equal(trial[2][0],'executable-trial-qualified');assert.equal(trial[4][0],'process-observation');assert.equal(trial[4][2],1);
assert.equal(candidate[3].length,17);assert.equal(candidate[3][14][0],'negative-controls');assert.equal(candidate[3][15][0],'runtime-dependencies');
assert.equal(candidate[3][16][0],'candidate-lineage');assert.equal(candidate[3][15][3],hash(fs.readFileSync(root+'/config/workshop-contract-v1.json')));
const question=read(dir+'/executable-2-generation.json').native;
assert.equal(question[6][0],'address-observed-discrepancy');assert.equal(question[6][1][4][0],'process-observation');assert.equal(question[6][1][4][2],1);
assert(!fs.existsSync(dir+'/executable-2-request.json'));assert(!fs.existsSync(dir+'/executable-2-wire.json'));
for(const f of pins)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
save(dir+'/services-after.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
save(dir+'/verdict.json',{status:'PASS-BOUNDED-REPAIR-REPLAY',new_model_calls:0,prior_response_exact_question_bound:true,actual_process_evidence_enters_revision:true,manifest_explicit:true,all_six_fixed_tests_pass:true,smoke_exit:1,global_grant_prevents_inference:true,not_promoted:true,limits:'Repair readback/retrial on historical model product; no successful corrected smoke or new model revision'});
console.log(JSON.stringify(read(dir+'/verdict.json')));
