// Independent finite adversarial checks. No candidate code or source is repaired.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {root,hash} from '../fidelity/check.mjs';import {read,save,native,sexp} from '../g22_v2/common.mjs';
process.chdir(root);const n=process.argv[2];assert.match(n??'',/^00[1-5]$/);const d=root+'/evidence/G28/attempt-'+n,W=root+'/runtime/g27/attempt-28'+n;
const final=read(d+'/final.json').native;assert.equal(final[0],'executable-awaiting-approval');const proposal=final[1],candidate=proposal[2],id=candidate[1],source=read(d+'/input.json').native,cases=source[3].find(x=>x[1]==='contract-source')[6][6];
const boot=`!(import! &self "${root}/src/bootstrap_executable_development_v1.metta")\n!(import_prolog_functions_from_file "${root}/scripts/g28/boundaries.pl" (xb_candidate xb_generation xb_opportunity xb_forged_candidate xb_neutral_candidate xb_receipt))\n`;
const ledger=W+'/journal/trajectory.jsonl',ledgerBefore=fs.readFileSync(ledger),modelBefore=fs.readdirSync(d).filter(x=>x.endsWith('-request.json')).sort(),actualFiles=candidate[2].map(f=>({path:W+'/candidates/'+id+'/'+f[1],sha256:hash(fs.readFileSync(W+'/candidates/'+id+'/'+f[1]))}));
const rows=native(d,'native-boundaries',`
!(result bound (let $c (xb_candidate "${d}") (wx_candidate_bound "${d}" ${id} $c)))
!(result tampered (let $c (xb_forged_candidate "${d}") (wx_candidate_bound "${d}" ${id} $c)))
!(result valid (let* (($o (xb_opportunity "${d}")) ($c (xb_candidate "${d}"))) (XCandidateValid $o ${id} $c)))
!(result neutral (let* (($o (xb_opportunity "${d}")) ($c (xb_neutral_candidate "${d}"))) (XCandidateValid $o neutral-executable-id $c)))
!(result unrequested (let* (($q (xb_generation "${d}")) ($r (wx_model "${d}" $q))) (index-atom $r 0)))
!(result forged-observation (let $r (wx_observe "${d}" ordinary (workshop-result fabricated test-completed fake-event fake-hash)) (index-atom $r 0)))
`,boot);const results=Object.fromEntries(rows.map(x=>[x[1],x[2]]));assert.deepEqual(results,{bound:'candidate-source-bound',tampered:'candidate-source-unbound',valid:'true',neutral:'true',unrequested:'executable-model-incomplete','forged-observation':'io-incomplete'});
const observations=proposal[3][2][2];const unknown=structuredClone(observations);unknown[0]=['io-incomplete','ordinary','missing'];const duplicate=structuredClone(observations);duplicate[0]=duplicate[1];const probes={unknown,duplicate,extra:[...observations,observations[0]],restored:observations};const compared=native(d,'observation-boundaries',Object.entries(probes).map(([name,v])=>`!(result ${name} (let $r (XCompare ${sexp(cases)} ${sexp(v)}) (index-atom $r 0)))`).join('\n'),boot);for(const r of compared)assert.equal(r[2],r[1]==='restored'?'executable-trial-qualified':'executable-trial-unqualified');
assert(fs.readFileSync(ledger).equals(ledgerBefore));assert.deepEqual(fs.readdirSync(d).filter(x=>x.endsWith('-request.json')).sort(),modelBefore);for(const f of actualFiles)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
const g=read(W+'/grant.json'),base=g.base_commit;const git=args=>execFileSync('/usr/bin/git',['-C',W+'/seed',...args],{encoding:'utf8'}).trim();const head=execFileSync('/usr/bin/git',['-C',W+'/candidates/'+id,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
function request(name,operation,extra={},grant=g.grant_id){const q={schema:'miter-workshop-request-v1',request_id:name,idempotency_key:name,grant_id:grant,candidate_id:id,operation,...extra};save(W+'/request-'+name+'.json',q);return native(d,name,`!(result response (ww_request "${W}" "request-${name}.json"))`,`!(import! &self (library lib_import))\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_workshop_v1.pl" (ww_request))\n`)[0][2]}
assert.equal(request('foreign-grant','write_candidate_file',{path:'extension/forged.txt',contents:'synthetic denied request'},'not-this-grant')[2],'request-rejected');assert(!fs.existsSync(W+'/candidates/'+id+'/extension/forged.txt'));
assert.equal(request('wrong-promotion-commit','submit_promotion_request',{proposal:'synthetic false commit',commit:base})[2],'operation-denied');
assert.equal(request('direct-main-after-extension','write_candidate_file',{path:'../seed/CONTROL.txt',contents:'synthetic denied request'})[2],'operation-denied');
assert.equal(request('invented-activation','activate_candidate',{})[2],'operation-denied');
const prior=fs.readFileSync(ledger);const replay=native(d,'commit-replay',`!(result response (ww_request "${W}" "request-${id}-commit.json"))`,`!(import! &self (library lib_import))\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_workshop_v1.pl" (ww_request))\n`)[0][2];assert.deepEqual(replay,proposal[4]);assert(fs.readFileSync(ledger).equals(prior));assert.equal(execFileSync('/usr/bin/git',['-C',W+'/candidates/'+id,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),head);assert.equal(git(['rev-parse','main']),base);assert.equal(git(['status','--porcelain']),'');for(const f of actualFiles)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
save(d+'/candidate.diff',git(['diff','--no-ext-diff','--no-textconv',base,head,'--','extension','candidate_tests']));
save(d+'/boundary-verdict.json',{status:'PASS-BOUNDED',native:results,observation_cases:compared,foreign_grant_rejected:true,false_commit_rejected:true,direct_main_rejected:true,invented_activation_rejected:true,candidate_commit_replay_no_change:true,no_new_model_calls:true,actual_code_unchanged:true,not_promoted:true});console.log(JSON.stringify(read(d+'/boundary-verdict.json')));
