// Preserve failed gate evidence without upgrading an incomplete candidate to PASS.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';
import {root,hash,validatePlan} from '../fidelity/check.mjs';import {read,save} from '../g22_v2/common.mjs';
process.chdir(root);validatePlan(read(root+'/docs/gates/G28/plan.json'));
const end=root+'/evidence/G28/attempt-004',replay=root+'/evidence/G28/attempt-005';assert.equal(read(end+'/final.json').native[0],'executable-development-incomplete');assert.equal(read(end+'/final.json').native[1],'resource-envelope-exhausted');assert.equal(read(replay+'/verdict.json').new_model_calls,0);
const docker='/Applications/Docker.app/Contents/Resources/bin/docker',dockerRun=args=>execFileSync(docker,args,{encoding:'utf8',timeout:20000,maxBuffer:1024*1024});const after=dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']);save(end+'/services-after-terminal.txt',after);const identities=t=>t.trim().split('\n').filter(Boolean).map(x=>x.split(' ').slice(0,2).join(' ')).sort();assert.deepEqual(identities(fs.readFileSync(end+'/services-before.txt','utf8')),identities(after));const containers=dockerRun(['ps','-a','--format','{{.Names}}']).trim().split('\n').filter(x=>x.startsWith('miter_g27_'));assert.deepEqual(containers,[]);
const attempts=[],allLedgerEvents=[];
for(const a of fs.readdirSync(root+'/evidence/G28').filter(x=>/^attempt-00[1-5]$/.test(x))){const d=root+'/evidence/G28/'+a,n=a.slice(-3),W=root+'/runtime/g27/attempt-28'+n,freeze=read(d+'/freeze.json');for(const f of freeze.files){if(f.path.includes('/config/local/'))continue;const p=d+'/code/'+f.path.slice(root.length+1).replaceAll('/','__');assert.equal(hash(fs.readFileSync(p)),f.sha256,p)}
 const archive=d+'/runtime-records';assert(!fs.existsSync(archive));fs.mkdirSync(archive);for(const sub of ['journal','events','receipts','prepared','states','request-ids'])if(fs.existsSync(W+'/'+sub))fs.cpSync(W+'/'+sub,archive+'/'+sub,{recursive:true});
 const git=args=>execFileSync('/usr/bin/git',['-C',W+'/seed',...args],{encoding:'utf8'}).trim(),g=read(W+'/grant.json');assert.equal(git(['rev-parse','refs/heads/main']),g.base_commit);assert.equal(git(['status','--porcelain']),'');save(d+'/git-history-terminal.txt',git(['log','--all','--graph','--decorate','--format=%H %s']));git(['bundle','create',d+'/laboratory-history.bundle','--all']);
 let count=0;if(fs.existsSync(W+'/journal/trajectory.jsonl')){const lines=fs.readFileSync(W+'/journal/trajectory.jsonl','utf8').trim().split('\n');let previous='GENESIS',parent=null;for(let i=0;i<lines.length;i++){const line=lines[i],e=JSON.parse(line);assert.equal(e.local_sequence,i+1);assert.equal(e.previous_event_hash,previous);assert.deepEqual(e.parent_event_ids,parent?[parent]:[]);assert.equal(hash(line.replace(/"event_hash":"[a-f0-9]{64}",/,'')),e.event_hash);const raw=fs.readFileSync(W+'/journal/objects/sha256/'+e.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(raw),e.payload_hash);assert.equal(e.project_scope,'G28');previous=e.event_hash;parent=e.event_id;const event=read(W+'/events/'+e.event_id+'.json');allLedgerEvents.push(event);count++;const details=event.payload.details;if(details.inspect){assert.equal(details.inspect_status,'exit(0)');const x=JSON.parse(details.inspect)[0],h=x.HostConfig;assert.equal(h.NetworkMode,'none');assert.equal(h.ReadonlyRootfs,true);assert.equal(h.Privileged,false);assert.equal(x.Config.User,'501:20');assert.equal(x.Config.Image,read(root+'/config/workshop-contract-v1.json').image);assert(h.CapDrop.includes('ALL'));assert(h.SecurityOpt.some(x=>x.startsWith('no-new-privileges')));assert.equal(h.Memory,134217728);assert.equal(h.PidsLimit,32);assert.equal(x.Mounts.filter(x=>x.Type==='volume').length,0);const binds=x.Mounts.filter(x=>x.Type==='bind');assert.equal(binds.length,3);assert(binds.some(m=>m.Destination==='/contract'&&!m.RW));for(const sub of ['extension','candidate_tests'])assert(binds.some(m=>m.Source===W+'/candidates/parent/'+sub&&m.Destination==='/workspace/'+sub));}}}
 const requests=fs.readdirSync(d).filter(x=>/^executable-[12]-request.json$/.test(x));const nativeResults=fs.readdirSync(d).filter(x=>/^candidate-[12].json$/.test(x)).map(f=>read(d+'/'+f).native);attempts.push({attempt:a,standing:n==='005'?'synthetic replay, no new calls':n==='004'?'actual model invocation exhausted':'pre-model setup failure',prepared_requests:requests.length,journal_events:count,native_results:nativeResults,main_unchanged:true});
}
// Copy only the two predictions and operational records from this invocation;
// unrelated LM Studio conversations and earlier log entries stay private.
const logPath='/Users/bcb/.lmstudio/server-logs/2026-09/2026-09-03.1.log',lines=fs.readFileSync(logPath,'utf8').split('\n'),operational=[],predictions=[];
for(let i=0;i<lines.length;i++){const m=lines[i].match(/^\[2026-09-03 (16:\d\d:\d\d)\]/);if(!m||m[1]<'16:38:20'||m[1]>'16:45:00')continue;if(/Received request: POST|Prompt processing|Reasoning setting|prompt eval time|Model generated tool calls/.test(lines[i]))operational.push(lines[i]);if(!lines[i].includes('Generated prediction: {'))continue;let text='{',parsed;for(let j=i+1;j<lines.length;j++){text+='\n'+lines[j];try{parsed=JSON.parse(text);break}catch{}}if(parsed&&/executable-[12]/.test(parsed.choices?.[0]?.message?.content??'')){const index=predictions.length+1;save(end+'/diagnostic-server-response-'+index+'.json',parsed);predictions.push({server_time:m[1],file:'diagnostic-server-response-'+index+'.json',sha256:hash(fs.readFileSync(end+'/diagnostic-server-response-'+index+'.json')),finish_reason:parsed.choices[0].finish_reason,usage:parsed.usage,standing:'Server-side diagnostic only; not received/admitted by timed-out native call'});}}
assert.equal(predictions.length,2);save(end+'/server-operational-excerpt.txt',operational.join('\n')+'\n');save(end+'/server-diagnostic-index.json',{source:logPath,selection:'Only G28 invocation 16:38:20–16:45:00 local time; no other conversations',predictions});
const unit=spawnSync(process.execPath,['--test','scripts/fidelity/check.test.mjs'],{encoding:'utf8'});save(root+'/evidence/G28/fidelity-tests.stdout',unit.stdout);save(root+'/evidence/G28/fidelity-tests.stderr',unit.stderr);assert.equal(unit.status,0);
save(root+'/evidence/G28/terminal-verification.json',{status:'BLOCKED',reason:'Two native model calls exhausted the frozen profile; no admissible executable or promotion proposal exists',actual_model_calls:2,prepared_request_copies_in_replay:2,new_replay_calls:0,attempts,journal_events:allLedgerEvents.length,service_identities_unchanged:true,test_containers_cleaned:true,main_unchanged:true,no_candidate_implementation_written:true,independent_authorship_review:'NOT REACHED',candidate_trial_commit_promotion:'NOT REACHED',replay_negative_checks:read(replay+'/verdict.json'),next_authority:'Renewed source grant and explicitly refrozen resource profile before further inference'});
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const p=d+'/'+e.name;assert(!e.isSymbolicLink());return e.isDirectory()?walk(p):[{path:p.slice(root.length+1),sha256:hash(fs.readFileSync(p)),bytes:fs.statSync(p).size}]})}
save(root+'/evidence/G28/all-attempts.json',{files:walk(root+'/evidence/G28')});console.log(JSON.stringify(read(root+'/evidence/G28/terminal-verification.json')));
