import fs from 'node:fs';import assert from 'node:assert/strict';import {root,hash} from '../fidelity/check.mjs';import {native,read,save} from '../g22_v2/common.mjs';
process.chdir(root);const rel=process.argv[2],dir=root+'/'+rel;assert.match(rel,/^evidence\/G24\/attempt-\d{3}$/);assert.equal(read(dir+'/verdict.json').status,'PASS-BOUNDED');
const out=dir+'/boundaries';assert(!fs.existsSync(out));fs.mkdirSync(out);process.on('uncaughtException',e=>{save(out+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
const boot=`!(import! &self "${root}/src/bootstrap_nace_v2.metta")\n`;
function prepare(name){const d=out+'/'+name;fs.mkdirSync(d);const old=dir+'/canonical';for(const f of fs.readdirSync(old).filter(n=>n==='input.json'||n.startsWith('module-')))fs.copyFileSync(old+'/'+f,d+'/'+f);const m=read(old+'/manifest.json');m.files=m.files.map(f=>({...f,path:f.path.startsWith(old+'/')?f.path.replace(old+'/',d+'/'):f.path}));save(d+'/manifest.json',m);return d}
const d=prepare('native-guards'),inv=`(index-atom (index-atom (nn_input "${d}") 1) 1)`,prefix=`(($inv ${inv}) ($old (NSeed $inv)) ($obs (NObserve $inv)))`;
const checks=[];
for(const [name,standing]of [['forged-confirmed','confirmed'],['unverified-mixed','mixed'],['unverified-ambiguous','ambiguous']]){const r=native(d,name,`!(result check (let* ${prefix} (let $forged (efficacy-observation $inv ${standing} (index-atom $obs 3) (index-atom $obs 4)) (NApply $old $forged))))`,boot);assert.deepEqual(r[0][2],['efficacy-rejected','invalid-scope-or-observation']);checks.push(name)}
const unchanged=native(d,'unchanged',`!(result check (let* ${prefix} (NApply $old $obs)))`,boot);assert.equal(unchanged[0][2][0],'efficacy-transition');assert.equal(unchanged[0][2][4],'revised');checks.push('unchanged-observation');
const foreign=native(d,'foreign',`!(result check (let* ${prefix} (NApply (efficacy-belief foreign (index-atom $old 2) (index-atom $old 3) (index-atom $old 4) (stv 0.5 0) 0 ()) $obs)))`,boot);assert.equal(foreign[0][2][0],'efficacy-rejected');checks.push('foreign-scope');
const malformed=native(d,'malformed',`!(result process (NProcess "${d}" (malformed)))\n!(result load (NLoad "${d}" (malformed)))\n!(result apply (NApply (malformed) (efficacy-observation (malformed) confirmed () ())))`,boot);assert.equal(malformed.length,3);malformed.forEach(r=>assert.equal(r[2][0],'efficacy-rejected'));checks.push('total-malformed-boundaries');
const unstaged=native(d,'unstaged',`!(result check (let* ${prefix} (nn_commit "${d}" (NApply $old $obs))))`,boot);assert.equal(unstaged[0][2],'efficacy-commit-incomplete');assert(!fs.existsSync(d+'/store'));checks.push('unstaged-writer');
const writer=native(d,'writer',`!(result repair (let* ${prefix} (let* (($scope (index-atom $old 1)) ($context (index-atom $old 2)) ($pin (index-atom $old 3)) ($id (index-atom $old 4)) ($a (add-atom &derived (nace-efficacy $scope $context $pin $id (stv 0.9 0.9) 9 (stale)))) ($b (add-atom &derived (nace-efficacy $scope $context $pin $id (stv 0.8 0.8) 8 (older)))) ($before (NRead $inv)) ($w (NWrite $old))) (writer-proof $before $w (NRead $inv)))))`,boot);assert.equal(writer[0][2][1],'efficacy-cardinality-fault');assert.equal(writer[0][2][2],'efficacy-projected');assert.deepEqual(writer[0][2][3][5],['stv','0.5','0']);checks.push('remove-variable-add-one');
for(const mode of ['missing-projection','tampered-projection']){const r=prepare(mode),caseExpr=`(index-atom (index-atom (nn_input "${r}") 1) 0)`;const yes=native(r,'learn',`!(result learned (let* (($inv ${caseExpr}) ($loaded (NLoad "${r}" $inv))) (NProcess "${r}" $inv)))`,boot);assert.equal(yes[0][2][0],'efficacy-processed');const projection=fs.readdirSync(r).find(n=>n.startsWith('efficacy-')),ledger=r+'/store/trajectory.jsonl',before=hash(fs.readFileSync(ledger));
 fs.copyFileSync(r+'/'+projection,r+'/before-injection.json');if(mode==='missing-projection')fs.renameSync(r+'/'+projection,r+'/removed-projection.json');else{const x=read(r+'/'+projection);x.native[5]=['stv',1,.99];save(r+'/'+projection,x)}
 const result=native(r,'reload',`!(result load (NLoad "${r}" ${caseExpr}))\n!(result current (NRead ${caseExpr}))`,boot);assert.equal(result[0][2][0],'efficacy-recovery-required');assert.equal(result[1][2],'efficacy-uninitialized');assert.equal(hash(fs.readFileSync(ledger)),before);checks.push(mode);
}
const integrity=prepare('identity');fs.copyFileSync(integrity+'/manifest.json',integrity+'/before-injection.json');const m=read(integrity+'/manifest.json');m.files=m.files.filter(f=>!f.path.endsWith('/src/nal_revision_v1.metta'));save(integrity+'/manifest.json',m);assert.deepEqual(native(integrity,'check',`!(result input (nn_input "${integrity}"))`,boot)[0][2],['nace-input-unavailable']);checks.push('missing-native-participant');
save(out+'/verdict.json',{status:'PASS-BOUNDED',checks,limits:'Finite native admission/storage faults; no power-loss guarantee or untrusted source authentication claim'});console.log(JSON.stringify({status:'PASS-BOUNDED',checks:checks.length}));
