import fs from 'node:fs';import assert from 'node:assert/strict';import {root,hash} from '../fidelity/check.mjs';import {read,save,parse} from '../g22_v2/common.mjs';
const rel=process.argv[2],dir=root+'/'+rel;assert.match(rel,/^evidence\/G24\/attempt-\d{3}$/);assert.equal(read(dir+'/verdict.json').status,'PASS-BOUNDED');assert.equal(read(dir+'/boundaries/verdict.json').status,'PASS-BOUNDED');
for(const f of read(dir+'/freeze.json').files)assert.equal(hash(fs.readFileSync(root+'/'+f.path)),f.sha256,f.path);
const ast=parse('('+fs.readFileSync(root+'/src/nace_v2.metta','utf8').replace(/^;.*$/gm,'')+')');function shape(x){if(!Array.isArray(x))return;if(['if','let'].includes(x[0]))assert.equal(x.length,4);if(x[0]==='let*'){assert.equal(x.length,3);x[1].forEach(b=>assert.equal(b.length,2))}x.forEach(shape)}shape(ast);
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{assert(!e.isSymbolicLink());return e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]})}
let events=0,ledgers=0;for(const path of walk(dir).filter(p=>p.endsWith('/store/trajectory.jsonl'))){const lines=fs.readFileSync(path,'utf8').trim().split('\n');let previous='GENESIS',lastId=null;const states=new Map();for(let i=0;i<lines.length;i++){
 const e=JSON.parse(lines[i]);assert.equal(e.local_sequence,i+1);assert.equal(e.previous_event_hash,previous);assert.deepEqual(e.parent_event_ids,lastId?[lastId]:[]);assert.equal(hash(lines[i].replace(/"event_hash":"[a-f0-9]{64}",/,'')),e.event_hash);
 const raw=fs.readFileSync(path.replace('/trajectory.jsonl','/objects/sha256/'+e.payload_hash+'.json'),'utf8').replace(/\n$/,'');assert.equal(hash(raw),e.payload_hash);const p=JSON.parse(raw),t=p.native;assert.equal(t[0],'efficacy-transition');assert.deepEqual(t[1].slice(0,5),t[2].slice(0,5));if(states.has(p.key))assert.deepEqual(t[1],states.get(p.key));states.set(p.key,t[2]);previous=e.event_hash;lastId=e.event_id;events++;
 }if(!path.includes('/boundaries/')){for(const [key,state]of states){const current=read(path.replace('/store/trajectory.jsonl','/efficacy-'+key+'.json'));assert.deepEqual(current.native,state);assert.equal(state[5][0],'stv');assert(state[5][2]<1)}}ledgers++;
}
for(const arm of ['canonical','restored','neutral','severed']){const d=dir+'/'+arm,expected=read(d+'/expected.json'),after=read(d+'/after-spaces.json');assert.equal(after.derived.filter(x=>x[0]==='nace-efficacy').length,expected.length);for(const e of expected){const b=after.derived.find(x=>x[0]==='nace-efficacy'&&x[3]===e.pin);assert(b);assert(Math.abs(b[5][1]-e.f)<1e-10);assert(Math.abs(b[5][2]-e.c)<1e-10);assert.equal(b[6],e.u);const normalize=x=>arm==='neutral'?x.replace(/^neutral-/,''):x;assert.deepEqual([...b[7]].map(normalize).sort(),[...e.roots].map(normalize).sort());}}
save(dir+'/independent-final.json',{status:'PASS-BOUNDED',events,ledgers,source_shapes:true,projection_and_journal_agree:true,scope:'Exact byte hashes, sequence/parents, old-to-new state chaining, scalar/roots projection and current source identities; not whole-Soul certification'});
const files=walk(root+'/evidence/G24').filter(p=>!p.endsWith('/raw-inventory.json'));save(root+'/evidence/G24/raw-inventory.json',{files:files.map(path=>({path:path.slice(root.length+1),sha256:hash(fs.readFileSync(path)),bytes:fs.statSync(path).size}))});console.log(JSON.stringify({status:'PASS-BOUNDED',events,ledgers,files:files.length}));
