import fs from 'node:fs';import assert from 'node:assert/strict';import {root,hash,checkOpen} from '../fidelity/check.mjs';
import {native,save,read,sexp,parse} from '../g22_v2/common.mjs';import {cases,input} from './cases.mjs';import {verify as expression} from '../sc07/verify.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/G24\/attempt-\d{3}$/);const dir=root+'/'+rel;assert(!fs.existsSync(dir));fs.mkdirSync(dir,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});save(dir+'/opening.json',checkOpen('docs/gates/G24/plan.json'));
const rows=cases(),data=input(rows);save(dir+'/cases.json',rows);
const source=fs.readFileSync('effect_membranes/miter_nace_v2.pl','utf8');const required=[...new Set(['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md',...[...source.matchAll(/'([^']+\.(?:md|metta|pl))'/g)].map(m=>m[1]).filter(p=>p.includes('/'))])];
const files=[...required,'scripts/g24_v2/cases.mjs','scripts/g24_v2/run.mjs'];save(dir+'/freeze.json',{files:files.map(path=>({path,sha256:hash(fs.readFileSync(path))})),mapping:'unit-observation-stv-v1',standing:'Builder synthetic source fixtures, native capability observation, not human-benefit estimates'});fs.mkdirSync(dir+'/code');for(const p of files)fs.copyFileSync(p,dir+'/code/'+p.replaceAll('/','__'));
const bootstrap=`!(import! &self "${root}/src/bootstrap_nace_v2.metta")\n!(add-atom &soul (protected-canary Soul))\n!(add-atom &history (protected-canary adverse-history))\n`;
const state=r=>`(let* (($scope (index-atom ${r} 2)) ($context (index-atom ${r} 6)) ($pin (index-atom ${r} 7)) ($id (index-atom (index-atom ${r} 8) 2))) ((frequency (collapse (match &derived (nace-efficacy $scope $context $pin $id (stv $f $c) $u $roots) $f))) (confidence (collapse (match &derived (nace-efficacy $scope $context $pin $id (stv $f $c) $u $roots) $c))) (units (collapse (match &derived (nace-efficacy $scope $context $pin $id $t $u $roots) $u)))))`;
function prepare(name,rs=rows){const data=input(rs),d=dir+'/'+name;fs.mkdirSync(d);for(const [f,b]of data.modules)save(d+'/'+f,b);save(d+'/input.json',{invocations:data.invocations});const ps=[...required.map(p=>root+'/'+p),d+'/input.json',...[...data.modules.keys()].map(f=>d+'/'+f)];save(d+'/manifest.json',{files:ps.map(path=>({path,sha256:hash(fs.readFileSync(path))}))});return d}
const code=fs.readFileSync('src/nace_v2.metta','utf8'),needle='($next (NRevision (index-atom $old 5) $evidence))';assert.equal(code.split(needle).length,2);
const results={};for(const arm of ['canonical','severed','restored','neutral']){const localRows=structuredClone(rows);if(arm==='neutral')for(const r of localRows){r.id='neutral-'+r.id;r.roots=r.roots.map(x=>'neutral-'+x);r.m.candidate_id='neutral-'+r.m.candidate_id;const q=r.question;r.question='neutral-'+q;for(const list of [r.c.nodes,r.c.registry,r.c.current])for(const n of list)if(n[1]===q)n[1]=r.question}const data=input(localRows),d=prepare(arm,localRows);let boot=bootstrap;if(arm==='severed'){save(d+'/severed-nace.metta',code.replace(needle,'($next (index-atom $old 5))'));boot=bootstrap.replace(`!(import! &self "${root}/src/bootstrap_nace_v2.metta")`,`!(import! &self "${root}/src/bootstrap_voice_construction.metta")\n!(import! &self "${root}/src/nal_revision_v1.metta")\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_nace_v2.pl" (nn_number nn_input nn_save nn_commit nn_restore nn_snapshot))\n!(import! &self "${d}/severed-nace.metta")`)}
 const body=`!(nn_snapshot "${d}" before)\n`+rows.map((r,i)=>`!(result ${r.id} (let* (($inv (index-atom (index-atom (nn_input "${d}") 1) ${i})) ($loaded (NLoad "${d}" $inv)) ($obs (NObserve $inv))) (case-observation $loaded $obs (NProcess "${d}" $inv))))\n!(result fields-${i} (let $inv (index-atom (index-atom (nn_input "${d}") 1) ${i}) ${state('$inv')}))`).join('\n')+`\n!(nn_snapshot "${d}" after)`;
 results[arm]=native(d,'run',body,boot);assert.equal(results[arm].length,rows.length*2);
 const expected=new Map();for(let i=0;i<rows.length;i++){const r=rows[i],got=results[arm][i*2][2],obs=got[2],key=data.invocations[i].module_pin;assert.equal(got[0],'case-observation');assert.equal(got[1],'efficacy-projected');assert.equal(obs[0],'efficacy-observation');assert.equal(obs[2],r.expected,r.id);assert.equal(got[3][0],'efficacy-processed',r.id);
  if(obs[4][0]==='trial-evidence')expression({...r,expected:r.expression},['result',obs[4][1],obs[4][2]]);
  let e=expected.get(key)??{f:.5,c:0,u:0,roots:new Set()};if(['confirmed','disconfirmed'].includes(r.expected)&&!r.roots.some(x=>e.roots.has(x))){if(arm!=='severed'){const w=e.c/(1-e.c),f=r.expected==='confirmed'?1:0;e.f=(w*e.f+f)/(w+1);e.c=Math.min(.99,(w+1)/(w+2))}e.u++;r.roots.forEach(x=>e.roots.add(x))}expected.set(key,e);
  const fields=results[arm][i*2+1][2];for(const [j,k]of [[0,'f'],[1,'c'],[2,'u']]){assert.equal(fields[j][1].length,1);assert(Math.abs(Number(fields[j][1][0])-e[k])<1e-10,r.id+' '+k)}
 }
 const before=read(d+'/before-spaces.json'),after=read(d+'/after-spaces.json');for(const k of ['soul','history','compass'])assert.deepEqual(before[k],after[k]);assert.equal(after.compass.length,129);assert.equal(after.derived.filter(x=>x[0]==='nace-efficacy').length,data.modules.size);assert.equal(after.derived.filter(x=>x[0]==='nace-pending').length,0);
 const restartBody=rows.map((r,i)=>`!(result restart-${i} (let* (($inv (index-atom (index-atom (nn_input "${d}") 1) ${i})) ($loaded (NLoad "${d}" $inv))) (restored $loaded ${state('$inv')})))`).join('\n');const restart=native(d,'restart',restartBody,boot);assert.equal(restart.length,rows.length);for(let i=0;i<rows.length;i++){const final=expected.get(data.invocations[i].module_pin);assert.equal(restart[i][2][1],'efficacy-projected');for(const[j,k]of [[0,'f'],[1,'c'],[2,'u']])assert(Math.abs(Number(restart[i][2][2][j][1][0])-final[k])<1e-10)}save(d+'/expected.json',[...expected].map(([pin,e])=>({pin,...e,roots:[...e.roots]})));
}
assert.deepEqual(results.canonical,results.restored);assert.notDeepEqual(results.canonical,results.severed);
const probe=prepare('probes');const valid=[[['stv',.5,0],['stv',1,.5]],[['stv',.5,0],['stv',.5,0]]];const invalid=[[['stv',.5,1],['stv',1,.5]],[['stv','oops',.5],['stv',0,.5]],[['stv',.5,-.1],['stv',0,.5]]];const probes=native(probe,'validation',[...valid,...invalid].map((v,i)=>`!(result probe-${i} (NRevision ${sexp(v[0])} ${sexp(v[1])}))`).join('\n'),bootstrap);assert.deepEqual(probes[0][2],['stv','1.0','0.5']);assert.deepEqual(probes[1][2],['stv','0.5','0']);for(const p of probes.slice(2))assert.equal(p[2][0],'nal-invalid-truth-input');
const duplicate=native(probe,'duplicate-kernel',`!(import! &self "${root}/src/nal_revision_v1.metta")\n!(result duplicate (NRevision (stv 0.5 0) (stv 1 0.5)))`,bootstrap);assert.equal(duplicate[0][2][0],'nal-operator-cardinality-fault');
save(dir+'/verdict.json',{status:'PASS-BOUNDED',cases:rows.length,arms:['canonical','severed','restored','neutral','restart','numeric-domain','duplicate-kernel'],mapping:'unit-observation-stv-v1',limits:'Native finite capability outcomes on builder source fixtures; not human-benefit probability or G25 learned selection'});console.log(JSON.stringify({status:'PASS-BOUNDED',cases:rows.length,evidence:rel}));
