// Offline source fixtures and independent checks; never loaded by Miter.
import fs from 'node:fs';import assert from 'node:assert/strict';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {native,save,read,sexp} from '../g22_v2/common.mjs';
import {cases,input} from '../g24_v2/cases.mjs';import {replaceText} from '../sc04/fixtures.mjs';import {joint} from '../sc07/cases.mjs';import {verify as expression} from '../sc07/verify.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/G24\/g25-\d{3}$/);const dir=root+'/'+rel;assert(!fs.existsSync(dir));fs.mkdirSync(dir,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});save(dir+'/opening.json',checkOpen('docs/gates/G25/plan.json'));
const sources=read(root+'/evidence/G24/attempt-006/freeze.json').files.map(x=>x.path);const files=[...new Set([...sources,'src/nace_selection_v1.metta','src/bootstrap_nace_selection_v1.metta','scripts/g25_v2/run.mjs'])];save(dir+'/freeze.json',{files:files.map(path=>({path,sha256:hash(fs.readFileSync(path))})),claim:'Matched encounter; learning changes native ranking, not permission'});
const prototypes=cases(),get=id=>structuredClone(prototypes.find(r=>r.id===id));const rows=[];
function add(proto,id,edit=()=>{}){const r=get(proto);r.id=id;r.roots=['independent-'+id];edit(r);rows.push(r);return r}
add('parent-one','warm-parent-choice');
add('parent-one','warm-parent-inspection',r=>{replaceText(r.c,'commitment-source','Keep mara able to inspect ledger.');r.intended=prototypes[1].intended.filter(x=>x[0]!=='retain'||x[3]==='inspection')});
add('candidate-one','warm-candidate-choice');
add('parent-three','later-parent-two',r=>{replaceText(r.c,'commitment-source','Keep mara able to choose and inspect ledger.');r.intended=r.intended.filter(x=>x[3]!=='recovery')});
add('candidate-three','later-candidate-two',r=>{replaceText(r.c,'commitment-source','Keep mara able to choose and inspect ledger.');r.intended=r.intended.filter(x=>x[3]!=='recovery')});
add('parent-three','later-parent-three');add('candidate-three','later-candidate-three');
add('parent-three','matched-parent');const matched=add('candidate-three','matched-candidate');
// Both alternatives share exactly one current encounter, not merely similar prose.
rows[7].c=structuredClone(matched.c);rows[7].question=matched.question;
add('candidate-three','poisoned-permission',r=>{r.c=structuredClone(matched.c);r.question=matched.question;r.m.candidate_id='poisoned-permission';r.m.constructions[1].tokens=['@person','may','@verbs','@artifact'];r.expression='expression-inquiry'});
add('parent-three','hard-joint-parent',r=>{joint(r.c);r.jointClaims=r.intended.filter(x=>x[0]==='retain');r.expression='expression-inquiry'});
add('candidate-three','hard-joint-candidate',r=>{joint(r.c);r.jointClaims=r.intended.filter(x=>x[0]==='retain')});
rows[10].c=structuredClone(rows[11].c);rows[10].question=rows[11].question;
save(dir+'/cases.json',rows);const data=input(rows);assert.deepEqual(data.invocations[7].frame,data.invocations[8].frame);
const boot=`!(import! &self "${root}/src/bootstrap_nace_selection_v1.metta")\n!(add-atom &soul (protected-canary Soul))\n!(add-atom &history (protected-canary adverse-history))\n`;
const capture='(= (ECapture $inv) (let $belief (NRead $inv) (add-atom &trial (efficacy-prior $belief))))\n(= (EOld $inv) (let $belief (match &trial (efficacy-prior $b) $b) (if (NBelongs $belief $inv) $belief (empty))))\n';
function prepare(name,rs=rows){const d=dir+'/'+name;fs.mkdirSync(d);const data=input(rs);for(const[f,b]of data.modules)save(d+'/'+f,b);save(d+'/input.json',{invocations:data.invocations});const paths=[...files.map(p=>root+'/'+p),d+'/input.json',...[...data.modules.keys()].map(f=>d+'/'+f)];save(d+'/manifest.json',{files:paths.map(path=>({path,sha256:hash(fs.readFileSync(path))}))});return d}
const inv=(d,i)=>`(index-atom (index-atom (nn_input "${d}") 1) ${i})`;
const rank=(d,indices=[7,8])=>`(ERank (${indices.map(i=>inv(d,i)).join(' ')}))`;
const wantedParent=rows[7].m.candidate_id,wantedCandidate=rows[8].m.candidate_id;
function verifyRanking(result,rs,indices){assert.equal(result[0],'efficacy-ranking');assert.equal(result[3],'trial-allocation-only');assert.equal(result[1].length,indices.length);for(let j=0;j<indices.length;j++){const opt=result[1][j],r=rs[indices[j]];if(opt[0]==='efficacy-option'){const b=opt[4];expression({...r,expected:r.expression},['result',b[2],b[3]]);const[f,c]=b[4][5].slice(1).map(Number);assert(Math.abs(Number(opt[3])-(c*(f-.5)+.5))<1e-10)}else if(opt[0]==='efficacy-excluded'&&opt.length===4)expression({...r,expected:r.expression},['result',opt[2],opt[3]])}const scored=result[1].filter(x=>x[0]==='efficacy-option'),max=Math.max(...scored.map(x=>Number(x[3])));assert.deepEqual(result[2].map(x=>x[2]).sort(),scored.filter(x=>Number(x[3])===max).map(x=>x[2]).sort());}
const summaries={};for(const arm of ['canonical','severed','restored','neutral']){
 const rs=structuredClone(rows);if(arm==='neutral')for(const r of rs){r.id='neutral-'+r.id;r.roots=r.roots.map(x=>'neutral-'+x)}const d=prepare(arm,rs);let bootstrap=boot+capture;
 if(arm==='severed'){const code=fs.readFileSync('src/nace_selection_v1.metta','utf8');assert.equal(code.split('(= (ECurrent $inv) (NRead $inv))').length,2);save(d+'/severed.metta',code.replace('(= (ECurrent $inv) (NRead $inv))','(= (ECurrent $inv) (EOld $inv))'));bootstrap=`!(import! &self "${root}/src/bootstrap_nace_v2.metta")\n${capture}!(import! &self "${d}/severed.metta")\n!(add-atom &soul (protected-canary Soul))\n!(add-atom &history (protected-canary adverse-history))\n`}
 const order=arm==='neutral'?[8,7]:[7,8];const process=i=>`!(result observation-${i} (let $inv ${inv(d,i)} (NProcess "${d}" $inv)))`;
 const body=`!(nn_snapshot "${d}" before)\n`+[7,8].map(i=>`!(NLoad "${d}" ${inv(d,i)})`).join('\n')+'\n'+[0,1,2].map(process).join('\n')+'\n'+[7,8].map(i=>`!(ECapture ${inv(d,i)})`).join('\n')+`\n!(result before ${rank(d,order)})\n`+[3,4,5,6].map(process).join('\n')+`\n!(result after ${rank(d,order)})\n!(result beliefs ((NRead ${inv(d,7)}) (NRead ${inv(d,8)})))\n!(nn_snapshot "${d}" after)`;
 const raw=native(d,'run',body,bootstrap);assert.equal(raw.length,10);const before=raw.find(x=>x[1]==='before')[2],after=raw.find(x=>x[1]==='after')[2];verifyRanking(before,rs,order);verifyRanking(after,rs,order);assert.deepEqual(before[2].map(x=>x[2]),[wantedParent]);assert.deepEqual(after[2].map(x=>x[2]),[arm==='severed'?wantedParent:wantedCandidate]);
 const prior=Object.fromEntries(before[1].map(x=>[x[2],Number(x[3])])),later=Object.fromEntries(after[1].map(x=>[x[2],Number(x[3])]));assert(Math.abs(prior[wantedParent]-5/6)<1e-10);assert.equal(prior[wantedCandidate],.75);
 const beliefs=raw.find(x=>x[1]==='beliefs')[2];assert.deepEqual(beliefs.map(x=>Number(x[6])),[4,3]);assert(Math.abs(Number(beliefs[0][5][1])-.5)<1e-10);assert.equal(Number(beliefs[1][5][1]),1);
 const pre=read(d+'/before-spaces.json'),post=read(d+'/after-spaces.json');for(const k of ['soul','compass','history'])assert.deepEqual(pre[k],post[k]);assert.equal(post.derived.filter(x=>x[0]==='nace-efficacy').length,2);assert.equal(post.derived.filter(x=>x[0]==='nace-pending').length,0);
 const restarted=native(d,'restart',[7,8].map(i=>`!(NLoad "${d}" ${inv(d,i)})`).join('\n')+`\n!(result replay ${rank(d,order)})`,boot);verifyRanking(restarted[0][2],rs,order);assert.deepEqual(restarted[0][2][2].map(x=>x[2]),[wantedCandidate]);summaries[arm]={before:prior,after:later,restart:wantedCandidate,beliefs};save(d+'/summary.json',summaries[arm]);
}
assert.deepEqual(summaries.canonical,summaries.restored);assert.deepEqual(summaries.canonical.before,summaries.neutral.before);assert.deepEqual(summaries.canonical.after,summaries.neutral.after);
const d=prepare('boundaries');let b=`!(result missing ${rank(d)})\n`+[7,8,9].map(i=>`!(NLoad "${d}" ${inv(d,i)})`).join('\n')+`\n!(result tie ${rank(d)})\n!(result reverse-tie ${rank(d,[8,7])})\n!(let $seed (NSeed ${inv(d,9)}) (NWrite (efficacy-belief (index-atom $seed 1) (index-atom $seed 2) (index-atom $seed 3) (index-atom $seed 4) (stv 1 0.99) 99 (synthetic-high-not-earned))))\n!(result poison ${rank(d,[7,8,9])})\n!(result hard ${rank(d,[10,11])})\n!(result malformed (ERank atom))\n`;
b+=`\n!(result incompatible ${rank(d,[0,8])})\n!(result malformed-entry (ERank (bad)))\n`;
const probes=native(d,'run',b,boot);assert.equal(probes.length,8);const p=Object.fromEntries(probes.map(x=>[x[1],x[2]]));assert.deepEqual(p.missing[2],[]);assert(p.missing[1].every(x=>x[0]==='efficacy-unranked'));for(const key of ['tie','reverse-tie','poison'])assert.deepEqual(p[key][2].map(x=>x[2]).sort(),[wantedParent,wantedCandidate].sort());assert.equal(p.poison[1][2][0],'efficacy-excluded');verifyRanking(p.poison,rows,[7,8,9]);assert.equal(p.hard[1][0][0],'efficacy-excluded');assert.deepEqual(p.hard[2].map(x=>x[2]),[wantedCandidate]);verifyRanking(p.hard,rows,[10,11]);for(const key of ['malformed','incompatible','malformed-entry'])assert.equal(p[key][0],'efficacy-ranking-invalid');
// Independent journal hash, state-chain and final projection verification.
let events=0;for(const arm of ['canonical','severed','restored','neutral']){const d=dir+'/'+arm,lines=fs.readFileSync(d+'/store/trajectory.jsonl','utf8').trim().split('\n');let previous='GENESIS',id=null;const states=new Map();for(let i=0;i<lines.length;i++){const e=JSON.parse(lines[i]);assert.equal(e.local_sequence,i+1);assert.equal(e.previous_event_hash,previous);assert.deepEqual(e.parent_event_ids,id?[id]:[]);assert.equal(hash(lines[i].replace(/"event_hash":"[a-f0-9]{64}",/,'')),e.event_hash);const raw=fs.readFileSync(d+'/store/objects/sha256/'+e.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(raw),e.payload_hash);const o=JSON.parse(raw),t=o.native;if(states.has(o.key))assert.deepEqual(t[1],states.get(o.key));states.set(o.key,t[2]);previous=e.event_hash;id=e.event_id;events++}for(const[key,state]of states)assert.deepEqual(read(d+'/efficacy-'+key+'.json').native,state)}
save(dir+'/verdict.json',{status:'PASS-BOUNDED',events,arms:Object.keys(summaries),matched_frame_hash:hash(JSON.stringify(data.invocations[7].frame)),before:summaries.canonical.before,after:summaries.canonical.after,boundary_cases:Object.keys(p),limits:'Finite contextual trial allocation, no emission; native hard support remains causal, no efficiency or human-benefit claim'});
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])}save(dir+'/inventory.json',{files:walk(dir).map(path=>({path:path.slice(root.length+1),sha256:hash(fs.readFileSync(path)),bytes:fs.statSync(path).size}))});console.log(JSON.stringify(read(dir+'/verdict.json')));
