// Replay/unknown-state regression. Copies a failed laboratory invocation; no new
// model budget is granted, and no candidate implementation is supplied.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {read,save,native} from '../g22_v2/common.mjs';
process.chdir(root);const old=root+'/evidence/G28/attempt-004',d=root+'/evidence/G28/attempt-005',W=root+'/runtime/g27/attempt-28005';assert(!fs.existsSync(d)&&!fs.existsSync(W));fs.mkdirSync(d,{recursive:true});fs.mkdirSync(W,{recursive:true});
save(d+'/opening.json',checkOpen('docs/gates/G28/plan.json'));
const pins=[...read(old+'/freeze.json').files.map(f=>({path:f.path,sha256:hash(fs.readFileSync(f.path))})),...['scripts/g28/incomplete.mjs','scripts/g28/boundaries.pl'].map(p=>({path:root+'/'+p,sha256:hash(fs.readFileSync(root+'/'+p))}))];save(d+'/freeze.json',{files:pins,standing:'No-model-call replay/unknown-state regression; not executable authorship'});fs.mkdirSync(d+'/code');for(const f of pins.filter(x=>!x.path.includes('/config/local/')))fs.copyFileSync(f.path,d+'/code/'+f.path.slice(root.length+1).replaceAll('/','__'));
const oldW=root+'/runtime/g27/attempt-28004';execFileSync('/usr/bin/git',['clone','--no-local',oldW+'/seed',W+'/seed'],{encoding:'utf8'});fs.cpSync(oldW+'/contracts',W+'/contracts',{recursive:true});const grant=read(oldW+'/grant.json');grant.repository=W+'/seed';grant.contracts=W+'/contracts';grant.integrity=[...pins,...grant.tests.map(t=>({path:W+'/contracts/'+t.id+'.sh',sha256:hash(fs.readFileSync(W+'/contracts/'+t.id+'.sh'))}))];save(W+'/grant.json',grant);
for(const name of ['input.json','opportunity.json','executable-1-generation.json','executable-2-generation.json','executable-1-request.json','executable-2-request.json'])fs.copyFileSync(old+'/'+name,d+'/'+name);
save(d+'/context.json',{schema:'miter-executable-context-v1',workshop_root:W,chat_context:[]});save(d+'/manifest.json',{files:[...pins,...['input.json','context.json'].map(f=>({path:d+'/'+f,sha256:hash(fs.readFileSync(d+'/'+f))}))]});save(d+'/lineage.json',{standing:'Synthetic recovery harness carrying exact failed prepared requests; does not renew their grant',source:old,files:['input.json','opportunity.json','executable-1-generation.json','executable-2-generation.json','executable-1-request.json','executable-2-request.json'].map(file=>({file,sha256:hash(fs.readFileSync(old+'/'+file))}))});
const boot=`!(import! &self "${root}/src/bootstrap_executable_development_v1.metta")\n!(import_prolog_functions_from_file "${root}/scripts/g28/boundaries.pl" (xb_saved))\n`;
const cases=native(d,'incomplete-boundaries',`
!(result input (let $x (wx_input "${d}") (index-atom $x 0)))
!(result unstaged (let* (($q (xb_saved "${d}" executable-1-generation.json)) ($r (wx_model "${d}" $q))) (index-atom $r 0)))
!(result replay (let* (($q (xb_saved "${d}" executable-1-generation.json)) ($s (add-atom &derived (executable-generation-pending "${d}" $q))) ($r (wx_model "${d}" $q)) ($c (remove-atom &derived (executable-generation-pending "${d}" $q)))) (wx_save "${d}" replay $r)))
!(result held (let $x (wx_input "/outside-of-workshop") (index-atom $x 0)))
!(result forged (let $r (wx_observe "${d}" ordinary (workshop-result fabricated test-completed fake-event fake-hash)) (index-atom $r 0)))
!(result lineage (wx_candidate_bound "${d}" executable-1 (executable-candidate forged () ())))
`,boot);assert.deepEqual(cases,[['result','input','executable-input'],['result','unstaged','executable-model-incomplete'],['result','replay','stored'],['result','held','executable-input-unavailable'],['result','forged','io-incomplete'],['result','lineage','candidate-source-unbound']]);assert.match(read(d+'/replay.json').native[1],/model_response_unavailable_after_preparation/);
const hashes=read(d+'/lineage.json').files;for(const f of hashes)assert.equal(hash(fs.readFileSync(d+'/'+f.file)),f.sha256);assert(!fs.readdirSync(d).some(x=>x.endsWith('-raw.json')));assert(!fs.existsSync(W+'/journal'));assert(!fs.existsSync(W+'/candidates'));for(const f of pins)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
save(d+'/verdict.json',{status:'PASS-BOUNDED',claim:'Prepared-without-response cannot spend the same request again; unstaged model use, unknown input, forged observation and absent product retain distinct failed standing',new_model_calls:0,candidate_writes:0,promotion:false,does_not_prove:'Candidate generation/trial/commit/promotion remains unproved'});console.log(JSON.stringify(read(d+'/verdict.json')));
