// Offline launcher; native MeTTa owns opportunity, generation and construction.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn,spawnSync,execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {sexp,parse} from '../sc04/fixtures.mjs';import {cases,frame} from './cases.mjs';import {second,clauses} from '../sc06/cases.mjs';import {verify} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC07\/live-\d{3}$/);assert(!fs.existsSync(out));const prior=fs.readdirSync('evidence/SC07').filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync('evidence/SC07/'+n+'/worker-started.json'));assert(prior.length<2,'SC07 allocation exhausted');fs.mkdirSync(out,{recursive:true});const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');process.on('uncaughtException',e=>{save('failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
const row=cases().find(x=>x.id==='joint-supported'),a=row.c,b=second(a),dir=root+'/'+out,id='voice-realization-'+out.slice(-3);save('case.json',row);save('frame.json',{native:frame(a)});save('grant.json',{native:['development-grant',a.scope,1,1024,120],prior_model_requests:prior,scope:'SC07 synthetic laboratory only; no promotion or human emission'});save('opening.json',checkOpen('docs/gates/SC07/plan.json'));
const petta='/private/tmp/miter-g06-petta-ae66fa8',pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');const bootstrap=`!(import! &self "${root}/src/bootstrap_voice_construction.metta")\n`;
save('prepare.metta',bootstrap+`!(let* (($a (DObserve receipt-a independent-native-audit ${sexp(frame(a))} ${sexp(clauses)})) ($b (DObserve receipt-b independent-native-audit ${sexp(frame(b))} ${sexp(clauses)}))) (vc_record_receipts ${sexp(dir)} ($a $b)))\n`);const prep=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',dir+'/prepare.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:8*1024*1024});save('prepare.stdout',prep.stdout??'');save('prepare.stderr',prep.stderr??'');save('prepare-process.json',{status:prep.status,signal:prep.signal});assert.equal(prep.status,0);assert.equal(prep.stderr,'');assert(fs.existsSync(out+'/receipts.json'));assert.equal(JSON.parse(fs.readFileSync(out+'/receipts.json')).records.length,2);
const paths=['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md','constitution/soul_compass_v02.metta','src/participation.metta','src/participation_support.metta','src/grounded_language.metta','src/bootstrap_grounded_language.metta','src/relational_voice.metta','src/bootstrap_relational_voice.metta','src/development_evidence.metta','src/voice_construction.metta','src/bootstrap_voice_construction.metta','effect_membranes/miter_language.pl','effect_membranes/miter_relational_voice.pl','effect_membranes/miter_voice_construction.pl','effect_membranes/miter_store.pl','effect_membranes/miter_llm.pl','derived/voice-realization-seed-v2.json','config/voice-realization-schema-v2.json','config/local/g03-model-profiles.json',out+'/receipts.json',out+'/grant.json',out+'/frame.json'];save('manifest.json',{files:paths.map(path=>({path:root+'/'+path,sha256:hash(fs.readFileSync(path))}))});for(const path of paths.filter(p=>!p.startsWith(out+'/')&&!p.startsWith('config/local/')))save(path.replaceAll('/','__'),fs.readFileSync(path,'utf8'));save('launcher-source.mjs',fs.readFileSync('scripts/sc07/live.mjs','utf8'));save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),profile:'qwen-local',configuration_changed:false});
const canaries=['soul','history','derived'].map(s=>`!(add-atom &${s} (sc07-protected-canary ${s} immutable-test-content))`).join('\n'),surfaces=[['surface-capability','VoicePolicy','retention-omission','miter-voice-realization-v2',['trial-expression'],[]]];
save('entry.metta',bootstrap+canaries+`\n!(case-result live-run (VRun ${sexp(dir)} ${id} (vc_frame ${sexp(dir)}) (vc_receipts ${sexp(dir)}) ${sexp(surfaces)} ${sexp(['development-grant',a.scope,1,1024,120])}))\n`);
const fd=fs.openSync(out+'/stdout','w'),err=fs.openSync(out+'/stderr','w'),start=performance.now(),child=spawn('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',dir+'/entry.metta','silent'],{stdio:['ignore',fd,err]});fs.closeSync(fd);fs.closeSync(err);const timeout=setTimeout(()=>child.kill('SIGTERM'),130000);const result=await new Promise(resolve=>child.on('close',(code,signal)=>resolve({code,signal,elapsed_ms:performance.now()-start})));clearTimeout(timeout);save('process.json',result);assert.equal(result.code,0);assert.equal(fs.readFileSync(out+'/stderr','utf8'),'');assert(fs.existsSync(out+'/result.json'));const n=JSON.parse(fs.readFileSync(out+'/result.json')).native;save('launcher-observation.json',{...result,native_head:n[0],admission:n[1],disposition:n[5]?.[0]});console.log(JSON.stringify({process:result,result:n[0],admission:n[1],disposition:n[5]?.[0],evidence:out}));assert.equal(n[0],'quarantine-construction-result');assert.equal(n[1],'candidate-quarantined');assert.equal(n[5][0],'supported-expression-alternatives');
const output=fs.readFileSync(out+'/stdout','utf8').replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result ')).map(parse);assert.deepEqual(output[0][2],['quarantine-construction-result','candidate-quarantined','stored']);const before=JSON.parse(fs.readFileSync(out+'/before-spaces.json')),after=JSON.parse(fs.readFileSync(out+'/after-spaces.json'));for(const k of ['soul','history','derived','compass']){assert(before[k].length>0);assert.deepEqual(before[k],after[k])}assert.equal(before.trial.length,0);assert.equal(after.trial.length,1);
const actual=JSON.parse(fs.readFileSync(out+'/candidate.json'));const verdict=verify({...row,m:actual},['result',n[4],n[5]]);save('native-construction-verdict.json',{...verdict,standing:'Actual model candidate interpreted through native construction, not a comparative quality or promotion trial'});console.log(JSON.stringify(verdict));
