import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {root,swi,capture,source,prepare,launch,until,state,stopped,trace,save,pause,atomic,control,read,hash} from './common.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/SC08\/boundaries-\d{3}$/);capture(rel);const dir=root+'/'+rel,active=[],checks=[];
function pending(p){const r=spawnSync(swi,['--stack_limit=1g','-q','-s',root+'/scripts/sc08/mechanics.pl','--',p,'prepare','silent'],{encoding:'utf8',timeout:15000});save(p+'/prepare.stdout',r.stdout);save(p+'/prepare.stderr',r.stderr);save(p+'/prepare-process.json',{status:r.status});assert.equal(r.status,0,r.stderr);assert.equal(r.stderr,'');assert.equal(state(p)[3],'pending')}
function fake(p,mode){const out=fs.openSync(p+'/fake.stdout','w'),err=fs.openSync(p+'/fake.stderr','w');const child=spawn(swi,['--stack_limit=1g','-q','-s',root+'/scripts/sc08/mechanics.pl','--',p,mode,'silent'],{stdio:['ignore',out,err]});fs.closeSync(out);fs.closeSync(err);active.push(child);const timer=setTimeout(()=>child.kill('SIGTERM'),15000);const done=new Promise(resolve=>child.on('close',(code,signal)=>{clearTimeout(timer);save(p+'/fake-process.json',{code,signal});resolve({code,signal})}));return {child,done,label:'fake'}}
try{const input=source(dir);
 for(const mode of ['timeout','unavailable','pause','stop','revoke']){const p=dir+'/'+mode;prepare(p,input);pending(p);const before=state(p),run=fake(p,mode);await until(()=>trace(p).some(x=>x.kind==='driver_started'));
  if(['timeout','unavailable'].includes(mode)){await until(()=>state(p)[3]==='incomplete');assert.equal(state(p)[9][0],'transport-incomplete');checks.push({name:mode,result:state(p)[9],stop_ms:await stopped(p,run)})}
  else if(mode==='revoke'){const changed=structuredClone(input);changed.grant[2]=0;atomic(p+'/input.json',changed);await until(()=>state(p)[3]==='revalidation-required');assert.equal(state(p)[6],1);checks.push({name:mode,result:state(p)[9],stop_ms:await stopped(p,run)})}
  else if(mode==='stop'){checks.push({name:mode,stop_ms:await stopped(p,run)});assert.deepEqual(state(p)[7],before[7]);assert.deepEqual(state(p)[8],before[8])}
  else{const at=control(p,'pause');const event=await until(()=>trace(p).filter(x=>x.kind==='native_transition'&&x.reason==='human-paused').at(-1));const ms=(event.wall_time-at)*1000;assert(ms<500);assert.deepEqual(state(p)[7],before[7]);assert.deepEqual(state(p)[8],before[8]);await pause(80);control(p,'resume');await until(()=>state(p)[3]==='incomplete');assert.equal(state(p)[9][0],'transport-incomplete');checks.push({name:mode,pause_ms:ms,result:state(p)[9],stop_ms:await stopped(p,run)})}
  assert.equal(trace(p).filter(x=>x.kind==='transport_start').length,0);assert.equal(read(p+'/synthetic-dispatch.json').standing.includes('no actual model'),true);
 }
 {const p=dir+'/uncertain-restart';prepare(p,input);pending(p);const pendingState=state(p);const r=launch(p);active.push(r.child);await until(()=>state(p)[3]==='reconciliation');assert.deepEqual(state(p)[7],pendingState[7]);assert.deepEqual(state(p)[8],pendingState[8]);assert(!fs.existsSync(p+'/request'));await stopped(p,r);atomic(p+'/control.json',{event:['control',pendingState[1],pendingState[2],'resume']});const again=launch(p,'restart');active.push(again.child);await until(()=>state(p)[3]==='reconciliation');assert.equal(state(p)[6],1);checks.push({name:'uncertain-restart',result:state(p)[9],stop_ms:await stopped(p,again)});assert(!fs.existsSync(p+'/request'))}
 {const p=dir+'/pending-crash';prepare(p,input);pending(p);const run=fake(p,'pause');await until(()=>trace(p).some(x=>x.kind==='driver_started'));run.child.kill('SIGKILL');assert.equal((await run.done).signal,'SIGKILL');save(p+'/crash-checkpoint.json',read(p+'/checkpoint.json'));const r=launch(p,'restart');active.push(r.child);await until(()=>state(p)[3]==='reconciliation');assert.equal(state(p)[6],1);assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,0);checks.push({name:'pending-crash',result:state(p)[9],stop_ms:await stopped(p,r)})}
 for(const mode of ['manifest','missing-authority-pin','semantic-pin','history','malformed-state']){const p=dir+'/'+mode;prepare(p,input);
  if(mode==='manifest'){const m=read(p+'/manifest.json');m.files[0].sha256='0'.repeat(64);save(p+'/manifest.json',m)}
  if(mode==='history'){pending(p);const hp=p+'/history/00000001.json',h=read(hp);h.body.after[6]=0;save(hp,h)}
  if(mode==='missing-authority-pin'){const m=read(p+'/manifest.json');m.files=m.files.filter(f=>!f.path.endsWith('/CONSTITUTION.md'));m.semantic=hash(m.files.map(f=>f.sha256).join('\n'));save(p+'/manifest.json',m)}
  if(mode==='semantic-pin'){const m=read(p+'/manifest.json');m.semantic='0'.repeat(64);save(p+'/manifest.json',m)}
  if(mode==='malformed-state'){save(p+'/seed.json',{native:['malformed']});const m=read(p+'/manifest.json');m.files.find(f=>f.path===p+'/seed.json').sha256=hash(fs.readFileSync(p+'/seed.json'));m.semantic=hash(m.files.map(f=>f.sha256).join('\n'));save(p+'/manifest.json',m)}
  const r=launch(p);active.push(r.child);const e=await r.done;if(mode==='malformed-state'){assert.equal(e.code,0);assert.deepEqual(read(p+'/outcome.json').outcome,['cycle-fault','malformed-state'])}else{assert.equal(e.code,1);assert(fs.existsSync(p+'/runtime-fault.json'))}assert(!fs.existsSync(p+'/request'));checks.push({name:mode,code:e.code})
 }
 const paths=spawnSync(swi,['-q','-s',root+'/effect_membranes/miter_voice_construction.pl','-g',`(vc_path('${root}/evidence/SC08/example','candidate.json',_),vc_path('${root}/evidence/SC07/example','candidate.json',_),\\+vc_path('${root}/evidence/SC080/example','candidate.json',_),\\+vc_path('${root}/evidence/SC08/../outside','candidate.json',_),\\+vc_path('${root}/evidence/SC08/example','/tmp/out',_))->halt(0);halt(1)`],{encoding:'utf8'});save(dir+'/paths.stdout',paths.stdout);save(dir+'/paths.stderr',paths.stderr);assert.equal(paths.status,0);checks.push({name:'exact-path-extension',allowed:2,denied:3});
 save(dir+'/verdict.json',{status:'PASS-BOUNDED',checks,actual_model_calls:0,scope:'Real fake-HTTP transports and native continuation; not a model-authorship or server-confirmed cancellation claim.'});console.log(JSON.stringify({status:'PASS',checks:checks.length}));
}catch(e){for(const c of active)c.kill('SIGTERM');save(dir+'/failure.json',{message:e.message,stack:e.stack});throw e}
