// Independent assertions over committed-plan experiments and stored artifacts.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {parse} from '../sc04/fixtures.mjs';import {verify} from '../sc07/verify.mjs';
process.chdir(root);checkOpen('docs/gates/SC08/plan.json');const read=p=>JSON.parse(fs.readFileSync(p));const path='evidence/SC08/';
const trace=p=>fs.readFileSync(p+'/trace.jsonl','utf8').trim().split('\n').map(JSON.parse);
const norm=x=>Array.isArray(x)?x.map(norm):typeof x==='number'?String(x):x;
const outputs=p=>Object.fromEntries(fs.readFileSync(p,'utf8').replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(l=>l.startsWith('(case-result ')).map(l=>{const x=parse(l);return[x[1],x[2]]}));
const histories=[];
function history(p){let state=read(p+'/seed.json').native,tip='genesis',seq=0;const files=fs.readdirSync(p+'/history').filter(f=>f.endsWith('.json')).sort(),rows=[];
 for(const f of files){const file=p+'/history/'+f,e=read(file);assert.equal(e.body.sequence,++seq);assert.equal(e.body.previous,tip);assert.deepEqual(e.body.before,state);assert.notDeepEqual(e.body.before,e.body.after,'unchanged turn must not become history');state=e.body.after;tip=e.hash;rows.push(e.body);histories.push(root+'/'+file)}
 const cp=read(p+'/checkpoint.json');assert.deepEqual(cp.state,state);assert.equal(cp.tip,tip);assert.equal(cp.sequence,seq);return rows;
}
function snapshot(p,expected){const sessions=trace(p).filter(e=>e.kind==='driver_started');for(const [i,s]of sessions.entries()){const a=read(s.snapshots+'/before-spaces.json'),b=read(s.snapshots+'/after-spaces.json');for(const k of ['soul','history','derived','compass']){assert(a[k].length>0);assert.deepEqual(a[k],b[k])}assert.equal(a.compass.length,129);assert.equal(a.trial.length,0);if(expected!==null)assert.equal(b.trial.length,Array.isArray(expected)?expected[i]:expected)}return sessions.length}
function finalPins(p){const m=read(p+'/manifest.json');assert.equal(m.semantic,hash(m.files.map(f=>f.sha256).join('\n')));for(const f of m.files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path)}
// Actual native outputs, not the runner's summarized opinion.
const c=path+'causal-002',rows=read(c+'/cases.json'),canonical=outputs(c+'/canonical.stdout'),restored=outputs(c+'/restored.stdout');for(const row of rows){assert.deepEqual(canonical[row.id],restored[row.id]);assert.equal(canonical[row.id][0],'cycle-step');assert.equal(canonical[row.id][1][3],row.phase);if(row.reason!==null)assert.deepEqual(canonical[row.id][3],row.reason)}
for(const arm of ['sever-family','sever-opportunity']){const r=outputs(c+'/'+arm+'.stdout');assert.equal(r.qualified[1][3],'waiting');assert.deepEqual(r.qualified[2],[])}assert.equal(canonical.qualified[2][0][0],'dispatch');assert.equal(canonical['neutral-order'][2][0][0],'dispatch');
for(const arm of ['canonical','sever-family','sever-opportunity','restored']){assert.equal(read(c+'/'+arm+'-process.json').status,0);assert.equal(fs.readFileSync(c+'/'+arm+'.stderr','utf8'),'')}
const d=path+'driver-003';for(const name of ['paced','long']){history(d+'/'+name);snapshot(d+'/'+name,0);finalPins(d+'/'+name)}const samples=trace(d+'/long').filter(e=>e.kind==='driver_sample'),warm=samples.filter(e=>e.turn>=1000);assert.equal(samples.at(-1).turn,10000);assert.equal(trace(d+'/long').filter(e=>e.kind==='native_transition').length,1);assert(Math.max(...warm.map(e=>e.local_bytes))-Math.min(...warm.map(e=>e.local_bytes))<262144);assert(trace(d+'/paced').some(e=>e.kind==='mechanical_pacing'&&e.seconds===0.08));
const l=path+'live-001',p=l+'/cycle',lh=history(p),req=p+'/request',candidate=read(req+'/candidate.json'),request=read(req+'/request.json'),raw=read(req+'/raw.json'),timing=read(req+'/timing.json');assert.equal(timing.http_status,200);assert(timing.duration_ms<=120000);assert(request.body.max_tokens<=1024);assert.deepEqual(JSON.parse(raw.choices[0].message.content),candidate);assert.equal(request.request_id,candidate.candidate_id);
const pending=read(l+'/pending-checkpoint.json').state,constructed=read(l+'/constructed-checkpoint.json').state;assert.equal(pending[3],'pending');assert.equal(pending[6],1);assert.deepEqual(constructed[7],pending[7]);assert.deepEqual(constructed[8],pending[8]);assert.deepEqual(read(req+'/generation-intention.json').native,pending[8][3]);assert.deepEqual(read(req+'/opportunity.json').native,pending[7][1]);assert.deepEqual(read(req+'/develop.json').native,pending[7][2]);assert.equal(constructed[9][2],'model-candidate-bound');
const judged=verify({...read(l+'/case.json'),m:candidate},['result',constructed[9][3],constructed[9][4]]);assert(judged.options>0);assert.equal(lh.filter(e=>e.after[3]==='pending').length,1);assert(lh.filter(e=>e.after[3]==='waiting').length>=2);assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,1);assert(lh.some(e=>e.after[3]==='revalidation-required'));assert.equal(snapshot(p,[1,1,0]),3);
const worker=read(req+'/worker-started.json');const start=lh.find(e=>e.after[3]==='pending');assert(start.at<=worker.started_at);assert(read(l+'/second-family-injected.json').at<=start.at);
for(const f of read(req+'/lineage.json').files)assert.equal(hash(fs.readFileSync(req+'/'+f.file)),f.sha256);
// Live predates two mechanical recovery/startup hardenings. Verify its exact frozen bytes.
for(const f of read(req+'/manifest.json').files){let actual=f.path;if(f.path.startsWith(root+'/')&&['effect_membranes/miter_development_cycle.pl','effect_membranes/miter_voice_construction.pl'].includes(f.path.slice(root.length+1)))actual=l+'/'+f.path.slice(root.length+1).replaceAll('/','__');assert.equal(hash(fs.readFileSync(actual)),f.sha256,f.path)}
const b=path+'boundaries-004',bv=read(b+'/verdict.json'),latencies=[];assert.equal(bv.checks.length,13);for(const name of ['timeout','unavailable','pause','stop','revoke','uncertain-restart','pending-crash']){const p=b+'/'+name,h=history(p);assert(h.every(e=>e.after[6]===1));assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,0);finalPins(p);for(const f of fs.readdirSync(p+'/sent-controls')){const sent=read(p+'/sent-controls/'+f);if(!['pause','stop'].includes(sent.event[3]))continue;const change=h.find(e=>e.at>=sent.sent_at&&JSON.stringify(e.observation[7])===JSON.stringify(sent.event));assert(change);const persisted=trace(p).find(e=>e.kind==='native_transition'&&e.sequence===change.sequence);const ms=1000*(persisted.wall_time-sent.sent_at);assert(ms>=0&&ms<500);latencies.push(ms)}}
for(const check of bv.checks){if(check.stop_ms!==undefined)assert(check.stop_ms<500);if(check.pause_ms!==undefined)assert(check.pause_ms<500)}
assert.equal(read(b+'/pending-crash/fake-process.json').signal,'SIGKILL');for(const name of ['manifest','missing-authority-pin','semantic-pin','history']){assert.equal(read(b+'/'+name+'/run-process.json').code,1);assert(read(b+'/'+name+'/runtime-fault.json').error)}assert.deepEqual(read(b+'/malformed-state/outcome.json').outcome,['cycle-fault','malformed-state']);
const replay=path+'replay-003';for(const mode of ['canonical','bad-lineage','bad-candidate','forbidden-write','forbidden-effect']){const rp=replay+'/'+mode;const h=history(rp);finalPins(rp);snapshot(rp,mode==='canonical'?1:0);assert.equal(trace(rp).filter(e=>e.kind==='transport_start').length,0);if(mode==='canonical'){const a=h.find(e=>e.after[3]==='awaiting-trial').after[9];assert.deepEqual(read(rp+'/request/candidate.json'),candidate);verify({...read(replay+'/case.json'),m:candidate},['result',a[3],a[4]])}else assert(h.some(e=>e.after[3]==='incomplete'&&e.after[9][0]==='candidate-uptake-incomplete'))}
execFileSync('/opt/homebrew/bin/swipl',['-q','-s','scripts/sc08/verify-hashes.pl','--',...histories],{stdio:'pipe'});
const calls=fs.readdirSync(path).filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync(path+n+'/cycle/request/worker-started.json')).length;assert.equal(calls,1);
const result={status:'PASS-BOUNDED',native_cases:rows.length,native_arms:4,driver_turns:10000,stable_history_transitions:1,actual_model_requests:calls,actual_candidate_supported_expressions:judged.options,model_duration_ms:timing.duration_ms,boundary_checks:13,final_recovery_replay_cases:5,history_hashes_independently_checked:histories.length,protected_compass_atoms:129,max_fake_pending_interrupt_ms:Math.max(...latencies),limits:'Finite development continuation and expression grammar. No full multi-RNA production scheduler, full nine enactors, complete five authorities, candidate quality/promotion/NACE, G22 or power-loss/external exactly-once claim.'};
if(process.argv[2]==='record'){assert(!fs.existsSync(path+'package-verdict.json'));fs.writeFileSync(path+'package-verdict.json',JSON.stringify(result,null,2)+'\n')}console.log(JSON.stringify(result));
