import fs from 'node:fs';import assert from 'node:assert/strict';import {root,capture,source,prepare,launch,until,state,stopped,trace,save,pause,atomic,control} from './common.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/SC08\/driver-\d{3}$/);capture(rel);const dir=root+'/'+rel,active=[];
try{const input=source(dir),one={...input,receipts:input.receipts.slice(0,1)};
 const p=dir+'/paced';prepare(p,one,{cap:0.08});const r=launch(p);active.push(r.child);await until(()=>fs.existsSync(p+'/checkpoint.json')&&state(p)[3]==='waiting');await pause(250);assert.equal(state(p)[6],0);assert.equal(trace(p).filter(e=>e.kind==='native_transition').length,1);assert(trace(p).some(e=>e.kind==='mechanical_pacing'&&e.seconds===0.08));
 const wrong=structuredClone(input.frame[1]);wrong[2]='other';control(p,'pause',wrong);await pause(150);assert.equal(state(p)[3],'waiting');const stopMs=await stopped(p,r);
 atomic(p+'/control.json',{event:['control',state(p)[1],state(p)[2],'resume']});const next=launch(p,'restart');active.push(next.child);await until(()=>state(p)[3]==='waiting');assert.equal(state(p)[6],0);const restartStopMs=await stopped(p,next);
 const q=dir+'/long';prepare(q,one,{poll:0,cap:0,turns:10000});const long=launch(q,'run',60000);active.push(long.child);const exit=await long.done;assert.equal(exit.code,0,fs.readFileSync(q+'/run.stderr','utf8'));assert.equal(state(q)[6],0);assert.equal(trace(q).filter(e=>e.kind==='native_transition').length,1);const samples=trace(q).filter(e=>e.kind==='driver_sample');assert.equal(samples.at(-1).turn,10000);const warm=samples.filter(e=>e.turn>=1000);assert(Math.max(...warm.map(s=>s.local_bytes))-Math.min(...warm.map(s=>s.local_bytes))<262144);
 save(dir+'/verdict.json',{status:'PASS-BOUNDED',stop_ms:stopMs,restart_stop_ms:restartStopMs,turns:10000,samples,model_calls:0});console.log(JSON.stringify({status:'PASS',stop_ms:stopMs,turns:10000}));
}catch(e){for(const c of active)c.kill('SIGTERM');save(dir+'/failure.json',{message:e.message,stack:e.stack});throw e}
