// One actual model allocation. Input changes are synthetic contacts, not prompts.
import fs from 'node:fs';import assert from 'node:assert/strict';import {root,capture,source,prepare,launch,until,state,stopped,trace,save,pause,atomic,control,read,hash} from './common.mjs';import {verify} from '../sc07/verify.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/SC08\/live-\d{3}$/);const prior=fs.existsSync('evidence/SC08')?fs.readdirSync('evidence/SC08').filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync('evidence/SC08/'+n+'/cycle/request/worker-started.json')):[];assert(prior.length<2,'SC08 actual call allocation exhausted');capture(rel);const dir=root+'/'+rel,active=[];
try{const input=source(dir),p=dir+'/cycle',id='cycle-expression-'+rel.slice(-3);save(dir+'/allocation.json',{prior,maximum_new_calls:1,max_tokens:1024,deadline_seconds:120,endpoint:'http://127.0.0.1:1234/v1/chat/completions',synthetic_only:true,no_service_changes:true});
 prepare(p,{...input,receipts:input.receipts.slice(0,1)},{id});const r=launch(p,'initial',130000);active.push(r.child);await until(()=>fs.existsSync(p+'/checkpoint.json')&&state(p)[3]==='waiting');await pause(100);assert.equal(state(p)[6],0);
 const rows=read(dir+'/receipts.json').records;atomic(p+'/input.json',{...input,receipts:[rows[0],rows[2]]});await until(()=>trace(p).filter(e=>e.kind==='native_transition').length>=2);assert.equal(state(p)[3],'waiting');assert.equal(state(p)[6],0);assert(!fs.existsSync(p+'/request/request.json'));
 save(dir+'/second-family-injected.json',{at:Date.now()/1000,standing:'new material laboratory source family; no repair request'});atomic(p+'/input.json',input);
 await until(()=>fs.existsSync(p+'/request/worker-started.json'));const pending=state(p);assert.equal(pending[3],'pending');assert.equal(pending[6],1);save(dir+'/pending-checkpoint.json',read(p+'/checkpoint.json'));
 await until(()=>state(p)[3]==='awaiting-trial'||['incomplete','revalidation-required'].includes(state(p)[3]),125000);assert.equal(state(p)[3],'awaiting-trial');const completed=state(p);save(dir+'/constructed-checkpoint.json',read(p+'/checkpoint.json'));assert.deepEqual(completed[7],pending[7]);assert.deepEqual(completed[8],pending[8]);
 const result=completed[9],candidate=read(p+'/request/candidate.json'),row=read(dir+'/case.json');const judged=verify({...row,m:candidate},['result',result[3],result[4]]);assert(judged.options>0);await pause(200);assert.equal(state(p)[6],1);assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,1);const stopMs=await stopped(p,r);
 atomic(p+'/control.json',{event:['control',id,input.frame[1],'resume']});const restarted=launch(p,'restart',20000);active.push(restarted.child);await until(()=>state(p)[3]==='awaiting-trial');assert.equal(state(p)[6],1);assert.deepEqual(state(p)[7],pending[7]);assert.deepEqual(state(p)[8],pending[8]);assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,1);const restartStopMs=await stopped(p,restarted);
 const stale=structuredClone(input);stale.frame[4].find(x=>x[1]==='joint-contact')[2]='v2';atomic(p+'/input.json',stale);atomic(p+'/control.json',{event:['control',id,input.frame[1],'resume']});const changed=launch(p,'changed-source');active.push(changed.child);await until(()=>state(p)[3]==='revalidation-required');assert.equal(state(p)[6],1);assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,1);const changeStopMs=await stopped(p,changed);
 const sessions=trace(p).filter(e=>e.kind==='driver_started').map(e=>e.snapshots);for(const [n,s]of sessions.entries()){const before=read(s+'/before-spaces.json'),after=read(s+'/after-spaces.json');for(const k of ['compass','soul','history','derived']){assert(before[k].length);assert.deepEqual(before[k],after[k])}assert.equal(before.trial.length,0);assert.equal(after.trial.length,n<2?1:0)}
 const raw=read(p+'/request/raw.json');assert.deepEqual(JSON.parse(raw.choices[0].message.content),candidate);for(const f of read(p+'/request/lineage.json').files)assert.equal(hash(fs.readFileSync(p+'/request/'+f.file)),f.sha256);
 save(dir+'/verdict.json',{status:'PASS-BOUNDED',actual_model_requests:1,options:judged.options,delayed_independent_source:true,duplicate_requests:0,restart_rehydrated:true,stale_uptake_blocked:true,stop_ms:stopMs,restart_stop_ms:restartStopMs,changed_stop_ms:changeStopMs,sessions});console.log(JSON.stringify({status:'PASS',actual_model_requests:1,options:judged.options}));
}catch(e){for(const c of active)c.kill('SIGTERM');save(dir+'/failure.json',{message:e.message,stack:e.stack});throw e}
