// Requalification of the final recovery mechanics using actual model bytes.
// These are disclosed replays, never counted as new model generation.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {root,swi,capture,source,prepare,launch,until,state,stopped,trace,save,read,hash} from './common.mjs';import {verify} from '../sc07/verify.mjs';
process.chdir(root);const rel=process.argv[2];assert.match(rel??'',/^evidence\/SC08\/replay-\d{3}$/);capture(rel);const dir=root+'/'+rel,active=[];
try{const input=source(dir),origin=root+'/evidence/SC08/live-001/cycle/request',candidate=read(origin+'/candidate.json'),checks=[];
 for(const mode of ['canonical','bad-lineage','bad-candidate','forbidden-write','forbidden-effect']){const p=dir+'/'+mode;prepare(p,input,{id:candidate.candidate_id});const prep=spawnSync(swi,['--stack_limit=1g','-q','-s',root+'/scripts/sc08/mechanics.pl','--',p,'prepare','silent'],{encoding:'utf8',timeout:15000});save(p+'/prepare.stdout',prep.stdout);save(p+'/prepare.stderr',prep.stderr);assert.equal(prep.status,0,prep.stderr);assert.equal(prep.stderr,'');
 const job=p+'/request';fs.mkdirSync(job);const fields=['receipts.json','grant.json','frame.json','candidate.json','raw.json','request.json','timing.json','generation-intention.json','opportunity.json','develop.json'];for(const name of fields)fs.copyFileSync(origin+'/'+name,job+'/'+name);
 const files=[...read(p+'/manifest.json').files,...['receipts.json','grant.json','frame.json'].map(name=>({path:job+'/'+name,sha256:hash(fs.readFileSync(job+'/'+name))}))];save(job+'/manifest.json',{files});save(p+'/replay-origin.json',{origin,files:fields.map(name=>({name,sha256:hash(fs.readFileSync(origin+'/'+name))})),actual_new_model_requests:0});
 if(mode==='bad-lineage')save(job+'/lineage.json',{files:[],parent_hash:'forged',standing:'not-validated'});if(mode==='bad-candidate'){const c=read(job+'/candidate.json');c.candidate_id='unrelated';save(job+'/candidate.json',c)}
 if(mode.startsWith('forbidden-')){const c=read(job+'/candidate.json');if(mode==='forbidden-write')c.allowed_writes=['&soul'];else c.allowed_effects=['http-post'];const raw=read(job+'/raw.json');raw.choices[0].message.content=JSON.stringify(c);save(job+'/candidate.json',c);save(job+'/raw.json',raw);save(p+'/injected-product.json',{standing:'Synthetic forbidden payload with matching local raw envelope; NOT the actual model output',mode})}
 const run=launch(p);active.push(run.child);await until(()=>['awaiting-trial','incomplete'].includes(state(p)[3]));const s=state(p);if(mode==='canonical'){assert.equal(s[3],'awaiting-trial');const r=s[9],v=verify({...read(dir+'/case.json'),m:candidate},['result',r[3],r[4]]);assert(v.options>0);checks.push({name:mode,options:v.options});}else{assert.equal(s[3],'incomplete');assert.equal(s[9][0],'candidate-uptake-incomplete');checks.push({name:mode,result:s[9]})}assert.equal(trace(p).filter(e=>e.kind==='transport_start').length,0);await stopped(p,run);
 const session=trace(p).find(e=>e.kind==='driver_started').snapshots,before=read(session+'/before-spaces.json'),after=read(session+'/after-spaces.json');for(const k of ['compass','soul','history','derived']){assert(before[k].length);assert.deepEqual(before[k],after[k])}assert.equal(after.trial.length,mode==='canonical'?1:0);
 }
 save(dir+'/verdict.json',{status:'PASS-BOUNDED',checks,actual_new_model_requests:0,standing:'Actual SC08 model bytes replayed through final membrane and native cycle, not fresh authorship'});console.log(JSON.stringify({status:'PASS',checks:checks.length}));
}catch(e){for(const c of active)c.kill('SIGTERM');save(dir+'/failure.json',{message:e.message,stack:e.stack});throw e}
