// Independent readback of raw results, call lineage and bounded transport.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {verify} from './verify.mjs';
process.chdir(root);const read=p=>JSON.parse(fs.readFileSync(p));checkOpen('docs/gates/SC05/plan.json');
const p='evidence/SC05/attempt-003/',cases=read(p+'cases.json'),canonical=read(p+'canonical-results.json'),restored=read(p+'restored-results.json');for(const c of cases){verify(c,canonical[c.id]);verify(c,restored[c.id]);assert.deepEqual(canonical[c.id],restored[c.id]);}
for(const arm of read(p+'verdict.json').arms){assert.equal(read(p+arm+'-process.json').status,0);assert.equal(fs.readFileSync(p+arm+'.stderr','utf8'),'');}
for(const f of read(p+'freeze.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path+' differs from final experiment');
const live='evidence/SC05/live-002/',i=read(live+'intention.json'),req=read(live+'native-request.json'),provider=read(live+'raw.json'),candidate=read(live+'candidate.json'),timing=read(live+'timing.json');
assert.equal(i.request_id,req.native[1]);assert.equal(i.request_id,candidate.request_id);assert.deepEqual(i.scope,candidate.scope);assert(i.stored_at<=read(live+'worker-started.json').started_at);assert.equal(timing.http_status,200);assert.deepEqual(JSON.parse(provider.choices[0].message.content).clauses,candidate.clauses);assert.equal(candidate.origin,'model-rendering');
assert.equal(read(live+'native-result.json').native[1][3],'unresolved-or-altered');assert.equal(read(live+'native-result.json').native[2][0],'expression-incomplete');
const replay=read('evidence/SC05/replay-002/verdict.json');assert.equal(replay.status,'faithful');assert.equal(read('evidence/SC05/replay-002/lineage.json').old_audit_sha256,hash(fs.readFileSync(live+'native-result.json')));
const stop='evidence/SC05/live-004/',stopSent=read(stop+'stop-sent.json').sent_at,observed=read(stop+'stop-observed.json').observed_at,native=read(stop+'native-result.json');assert.equal(native.native[0],'expression-cancellation-requested');assert.equal(native.native[1],'worker-cancel-requested');assert.equal(native.native[2],'no-completion-claim');assert(observed>=stopSent&&observed-stopSent<0.5);assert(native.stored_at-stopSent<0.5);assert.equal(read(stop+'process.json').code,0);
const mechanics=read('evidence/SC05/mechanics-002/verdict.json');assert.equal(mechanics.checks,10);assert.equal(mechanics.timeout,'model-timeout');assert.equal(mechanics.unavailable,'provider-unavailable');
const nativePaths=execFileSync('git',['ls-files','src','effect_membranes'],{encoding:'utf8'}).trim().split('\n').concat(['src/relational_voice.metta','effect_membranes/miter_relational_voice.pl']);for(const file of nativePaths){const text=fs.readFileSync(file,'utf8');assert(!/scripts\/[^\s]*\.(?:mjs|cjs)|path\(node\)|\b(?:py-call|janus:py_call)\b/.test(text),'runtime dependency violation '+file)}
const result={status:'PASS-BOUNDED',cases:cases.length,native_arms:5,transport_checks:10,actual_model_requests:3,original_allocation:2,extra_allocation:'evidence/SC05/cancellation-allocation.md',stop_observation_ms:(observed-stopSent)*1000,native_cancel_disposition_ms:(native.stored_at-stopSent)*1000,live_output:'Original incomplete interpretation preserved; explicit seen-text reinterpretation is faithful',runtime_boundary:'PeTTa/MeTTa plus Prolog; JS offline',limitations:'Finite training/counterfactual semantics; no external emission, promotion or server-side inference cancellation claim.'};
if(process.argv[2]==='record'){assert(!fs.existsSync('evidence/SC05/package-verdict.json'));fs.writeFileSync('evidence/SC05/package-verdict.json',JSON.stringify(result,null,2)+'\n')}console.log(JSON.stringify(result));
