// Offline launcher only. Native RRun forms, stores, calls and audits the request.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {base,sexp} from '../sc04/fixtures.mjs';
process.chdir(root);const out=process.argv[2],cancel=process.argv[3]==='cancel';assert.match(out??'',/^evidence\/SC05\/live-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});
const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');const c=base();save('case.json',c);save('opening.json',checkOpen('docs/gates/SC05/plan.json'));save('grant.json',{max_calls:1,scope:c.scope,purpose:'SC05 isolated relational voice evidence',external_human_emission:false});
const paths=['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md','constitution/soul_compass_v02.metta','src/participation.metta','src/participation_support.metta','src/grounded_language.metta','src/bootstrap_grounded_language.metta','src/relational_voice.metta','src/bootstrap_relational_voice.metta','effect_membranes/miter_language.pl','effect_membranes/miter_relational_voice.pl','effect_membranes/miter_store.pl','effect_membranes/miter_llm.pl','config/local/g03-model-profiles.json'];
save('manifest.json',{files:paths.map(path=>({path:root+'/'+path,sha256:hash(fs.readFileSync(path))}))});for(const path of paths.filter(p=>!p.startsWith('config/')))save(path.replaceAll('/','__'),fs.readFileSync(path,'utf8'));
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');
save('entry.metta',`!(import! &self "${root}/src/bootstrap_relational_voice.metta")\n!(RRun ${sexp(root+'/'+out)} voice-local ${'(GroundLanguage '+[c.scope,c.nodes,c.registry,c.current,c.operations,c.target,c.budget,c.proposals].map(sexp).join(' ')+')'})\n`);
save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),cancel_test:cancel,profile:'qwen-local',configuration_changed:false,runtime:'PeTTa/MeTTa plus Prolog; no JavaScript worker'});
const fd=fs.openSync(out+'/stdout','w'),err=fs.openSync(out+'/stderr','w'),started=performance.now();
const child=spawn('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/entry.metta','silent'],{stdio:['ignore',fd,err]});fs.closeSync(fd);fs.closeSync(err);
let sent=null;const poll=setInterval(()=>{if(cancel&&sent===null&&fs.existsSync(out+'/worker-started.json')&&Date.now()/1000-JSON.parse(fs.readFileSync(out+'/worker-started.json')).started_at>=0.75){sent=Date.now()/1000;save('control.json',{event:['control','voice-local',c.scope,'stop']});save('stop-sent.json',{sent_at:sent});}},10);
const timeout=setTimeout(()=>child.kill('SIGTERM'),130000);const result=await new Promise(resolve=>child.on('close',(code,signal)=>resolve({code,signal,elapsed_ms:performance.now()-started})));
clearInterval(poll);clearTimeout(timeout);save('process.json',result);
const files=fs.readdirSync(out);let native=null;if(files.includes('native-result.json'))native=JSON.parse(fs.readFileSync(out+'/native-result.json')).native;
let latency=null;if(sent!==null&&fs.existsSync(out+'/stop-observed.json'))latency=(JSON.parse(fs.readFileSync(out+'/stop-observed.json')).observed_at-sent)*1000;
save('launcher-observation.json',{...result,files,cancel_observation_ms:latency,native_result:native});console.log(JSON.stringify({process:result,cancel_observation_ms:latency,native_result_head:native?.[0],audit:native?.[1]?.[3],stderr:fs.readFileSync(out+'/stderr','utf8'),evidence:out}));
assert.equal(result.code,0);assert.equal(fs.readFileSync(out+'/stderr','utf8'),'');
if(cancel){assert(latency!==null);assert(latency<500);}else assert(native,'expected an evaluated and stored native result, not an unreduced expression');
