// Offline native VoiceRNA probe; no model call or human-facing effect.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {root,checkOpen} from '../fidelity/check.mjs';import {base,sexp,parse} from '../sc04/fixtures.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC05\/probe-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});
const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');save('opening.json',checkOpen('docs/gates/SC05/plan.json'));const c=base();save('case.json',c);save('native.metta',fs.readFileSync('src/relational_voice.metta','utf8'));
const ground=`(GroundLanguage ${[c.scope,c.nodes,c.registry,c.current,c.operations,c.target,c.budget,c.proposals].map(sexp).join(' ')})`;
const expressions=[['faithful',['You requested revision of ledger.','Mara must remain able to choose and inspect and restore ledger.']],['permission',['You requested revision of ledger.','Mara may choose and inspect and restore ledger.']],['promise',['I will revise ledger.','Mara must remain able to choose and inspect and restore ledger.']],['false-completion',['You requested revision of ledger.','Mara must remain able to choose and inspect and restore ledger.','The revision of ledger is complete.']]];
const entry=`!(import! &self "${root}/src/bootstrap_relational_voice.metta")\n`+expressions.map(([id,clauses])=>`!(let* (($g ${ground}) ($i (RIntend probe-voice $g)) ($a (RAudit $i ${sexp(c.scope)} ${sexp(c.scope)} ${sexp(clauses)}))) (case-result ${id} (result $i $a (RDisposition $a 1))))`).join('\n')+'\n';save('entry.metta',entry);
const r=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s','/private/tmp/miter-g06-petta-ae66fa8/src/main.pl','--',root+'/'+out+'/entry.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:16*1024*1024});save('stdout',r.stdout??'');save('stderr',r.stderr??'');save('process.json',{status:r.status,signal:r.signal,error:r.error?.message??null});
const results=(r.stdout??'').replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(l=>l.startsWith('(case-result ')).map(parse);save('results.json',results);console.log(JSON.stringify({status:r.status,stderr:r.stderr,results:results.map(x=>({id:x[1],intention:x[2]?.[1]?.[0],audit:x[2]?.[2]?.[3],disposition:x[2]?.[3]?.[0]})),evidence:out}));
assert.equal(r.status,0);assert.equal(r.stderr,'');assert.equal(results.length,expressions.length);
for(const x of results){assert.equal(x[2][1][0],'voice-intention');assert.equal(x[2][2][0],'voice-audit');assert.equal(x[2][2][3],x[1]==='faithful'?'faithful':'meaning-altered');}
