// External builder runner. Five native arms; no LLM or human-facing effect.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {sexp,parse} from '../sc04/fixtures.mjs';import {cases} from './cases.mjs';import {verify} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC05\/attempt-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});
const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');process.on('uncaughtException',e=>{save('failure.json',{status:'FAIL',message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
save('opening.json',checkOpen('docs/gates/SC05/plan.json'));const rows=cases();save('cases.json',rows);const src=fs.readFileSync('src/relational_voice.metta','utf8');
const inputs=['scripts/sc05/run.mjs','scripts/sc05/cases.mjs','scripts/sc05/verify.mjs','tests/fixtures/sc05/contract.md','src/relational_voice.metta','src/grounded_language.metta','src/participation_support.metta','src/participation.metta','constitution/soul_compass_v02.metta'];
save('freeze.json',{before_execution:new Date().toISOString(),files:inputs.map(p=>({path:p,sha256:hash(fs.readFileSync(p))})),disclosure:'Builder-authored training and counterfactual cases, not held-out evaluation'});for(const p of inputs)save(p.replaceAll('/','__'),fs.readFileSync(p,'utf8'));
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),model_calls:0});
const arms={canonical:null,'sever-intention':['(RRetentions $g)))','()))'],'sever-audit':['($defects (RAlterations (index-atom $intention 4) $uses $readings))','($defects ())'],'always-reject':['(if (== (size-atom $defects) 0) faithful','(if false faithful'],restored:null},results={};
for(const [arm,mutation]of Object.entries(arms)){
 let native=src;if(mutation){assert.equal(src.split(mutation[0]).length,2);native=src.replace(...mutation)}save(arm+'.metta',native);
 const entry=`!(import! &self "${root}/src/bootstrap_grounded_language.metta")\n!(import! &self "${root}/${out}/${arm}.metta")\n`+rows.map(r=>`!(let* (($g (GroundLanguage ${[r.c.scope,r.c.nodes,r.c.registry,r.c.current,r.c.operations,r.c.target,r.c.budget,r.c.proposals].map(sexp).join(' ')})) ($i (RIntend laboratory-voice $g)) ($a (RAudit $i ${sexp(r.current)} ${sexp(r.candidateScope)} ${sexp(r.clauses)}))) (case-result ${r.id} (voice-test-result $g $i $a (RDisposition $a 1) (if (PShape $i voice-intention 7) (RModelRequest $i) no-request))))`).join('\n')+'\n';save(arm+'-entry.metta',entry);
 const start=performance.now(),p=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/'+arm+'-entry.metta','silent'],{encoding:'utf8',timeout:60000,maxBuffer:64*1024*1024});save(arm+'.stdout',p.stdout??'');save(arm+'.stderr',p.stderr??'');save(arm+'-process.json',{status:p.status,signal:p.signal,error:p.error?.message??null,elapsed_ms:performance.now()-start});assert.equal(p.status,0);assert.equal(p.stderr,'');
 const lines=p.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result '));assert.equal(lines.length,rows.length);results[arm]=Object.fromEntries(lines.map(l=>{const x=parse(l);return[x[1],x[2]]}));save(arm+'-results.json',results[arm]);
}
const checked=rows.map(r=>{const result=verify(r,results.canonical[r.id]);verify(r,results.restored[r.id]);assert.deepEqual(results.canonical[r.id],results.restored[r.id]);return result});
assert.equal(results['sever-intention']['missing-request'][2][4].length,1);assert.equal(results['sever-intention']['faithful'][3][3],'meaning-altered');assert.equal(results['sever-audit']['false-completion'][3][3],'faithful');assert.equal(results['always-reject']['faithful'][3][3],'meaning-altered');
save('verdict.json',{status:'PASS-BOUNDED',cases:checked,arms:Object.keys(arms),limits:'Finite technical expression, training/counterfactual evidence only; no live emission, promotion, broad voice or model self-judgment.'});console.log(JSON.stringify({status:'PASS-BOUNDED',cases:checked.length,arms:Object.keys(arms).length,evidence:out}));
