// Offline experiment driver. Native MeTTa performs construction and comparison.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {sexp,parse} from '../sc04/fixtures.mjs';import {cases,frame} from './cases.mjs';import {verify} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC07\/attempt-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');process.on('uncaughtException',e=>{save('failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
save('opening.json',checkOpen('docs/gates/SC07/plan.json'));const rows=cases(),src=fs.readFileSync('src/voice_construction.metta','utf8');save('cases.json',rows);for(const r of rows)save(r.id+'.json',r.m);
const files=['src/voice_construction.metta','src/development_evidence.metta','src/bootstrap_voice_construction.metta','effect_membranes/miter_voice_construction.pl','scripts/sc07/cases.mjs','scripts/sc07/run.mjs','scripts/sc07/verify.mjs'];save('freeze.json',{at:new Date().toISOString(),files:files.map(path=>({path,sha256:hash(fs.readFileSync(path))})),standing:'Builder authored finite cases; no blind held-out claim'});for(const p of files)save(p.replaceAll('/','__'),fs.readFileSync(p,'utf8'));
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');save('runtime.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),model_calls:0});
const mutations={canonical:null,'sever-intention':['(= (VWanted $i) (RClaimSet (index-atom $i 4)))','(= (VWanted $i) ())'],'sever-semantics':['(= (VReadMatches $readings $claims)\n (and (== (size-atom (RUnresolved $readings)) 0)\n  (VSame (RClaimSet (RMeaningUses $readings)) $claims)))','(= (VReadMatches $readings $claims) true)'],'sever-composition':['(VExtend $covered $chosen $f) (empty)))))','(empty) (empty)))))'],'sever-joint':['($joint-misses (VJointMisses $joints $fragments))','($joint-misses ())'],restored:null},runs={};
for(const [arm,mutation]of Object.entries(mutations)){let native=src;if(mutation){assert.equal(src.split(mutation[0]).length,2,arm);native=src.replace(...mutation)}save(arm+'.metta',native);
const entry=`!(import! &self "${root}/src/bootstrap_relational_voice.metta")\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_voice_construction.pl" (vc_word vc_budget vc_sentence vc_module))\n!(import! &self "${root}/src/development_evidence.metta")\n!(import! &self "${root}/${out}/${arm}.metta")\n`+rows.map(r=>`!(let* (($m (vc_module "${root}/${out}/${r.id}.json")) ($result (VConstruct ${sexp(frame(r.c))} $m ${r.fuel}))) (case-result ${r.id} (result $result (VEligible $result))))`).join('\n')+'\n';save(arm+'-entry.metta',entry);
const p=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/'+arm+'-entry.metta','silent'],{encoding:'utf8',timeout:60000,maxBuffer:128*1024*1024});save(arm+'.stdout',p.stdout??'');save(arm+'.stderr',p.stderr??'');save(arm+'-process.json',{status:p.status,signal:p.signal});assert.equal(p.status,0,arm);assert.equal(p.stderr,'',arm);const lines=p.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result '));assert.equal(lines.length,rows.length);runs[arm]=Object.fromEntries(lines.map(l=>{const x=parse(l);return[x[1],x[2]]}));save(arm+'-results.json',runs[arm]);}
const checked=rows.map(r=>{const result=verify(r,runs.canonical[r.id]);verify(r,runs.restored[r.id]);assert.deepEqual(runs.canonical[r.id],runs.restored[r.id]);return result});
assert.notDeepEqual(runs['sever-intention']['compound-alternatives'],runs.canonical['compound-alternatives']);assert.equal(runs['sever-semantics']['permission-shift'][2][0],'supported-expression-alternatives');assert.equal(runs['sever-composition']['compound-alternatives'][2][0],'expression-inquiry');assert.equal(runs['sever-joint']['joint-unavailable-in-seed'][2][0],'supported-expression-alternatives');
save('verdict.json',{status:'PASS-BOUNDED',cases:checked,arms:Object.keys(mutations),model_calls:0,scope:'Native construction and source-grounded comparison of finite expressive possibilities, not general semantics or promotion'});console.log(JSON.stringify({status:'PASS-BOUNDED',cases:checked.length,arms:Object.keys(mutations),options:checked.filter(x=>x.options!==undefined).map(x=>[x.id,x.options]),evidence:out}));
