// Independent event, Git and sandbox evidence verification.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';
import {root,hash,read,save} from '../g22_v2/common.mjs';
const E=root+'/evidence/G28-R3',d=E+'/attempt-002',G=read(root+'/config/workshop-promotion-v1.json'),W=G.workshop_root,V=read(d+'/verdict.json');assert(!fs.existsSync(E+'/verification.json'));assert.equal(V.status,'PASS-BOUNDED');
for(const f of read(d+'/freeze.json').files){const copy=d+'/code/'+f.path.slice(root.length+1).replaceAll('/','__');if(fs.existsSync(copy))assert.equal(hash(fs.readFileSync(copy)),f.sha256);else assert.equal(hash(fs.readFileSync(f.path)),f.sha256)}
const lines=fs.readFileSync(W+'/journal/trajectory.jsonl','utf8').trim().split('\n');let previous='GENESIS',parents=[];const kinds=[];
for(const[i,line]of lines.entries()){const r=JSON.parse(line);assert.equal(r.local_sequence,i+1);assert.equal(r.previous_event_hash,previous);assert.deepEqual(r.parent_event_ids,parents);assert.equal(hash(line.replace(/"event_hash":"[a-f0-9]{64}",/,'')),r.event_hash);const object=fs.readFileSync(W+'/journal/objects/sha256/'+r.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(object),r.payload_hash);const ev=read(W+'/events/'+r.event_id+'.json');assert.deepEqual(JSON.parse(object),ev.payload);previous=r.event_hash;parents=[r.event_id];kinds.push(ev.payload.request.operation)}
const git=args=>execFileSync('/usr/bin/git',['-C',W+'/seed',...args],{encoding:'utf8'}).trim(),merge=V.merge;
assert.equal(git(['rev-parse','main']),merge);assert.equal(git(['show','-s','--format=%P',merge]),G.parent+' '+G.target);assert.equal(git(['diff','--name-only',G.target,merge]),'');assert.equal(git(['status','--porcelain']),'');
for(const f of read(G.evidence_root+'/candidate-1.json').native[2])assert.equal(hash(fs.readFileSync(W+'/seed/'+f[1])),f[3]);
assert.equal(kinds.filter(x=>x==='promote_candidate').length,1);assert.equal(kinds.filter(x=>x==='select_active_revision').length,3);assert.equal(kinds.filter(x=>x==='later_use').length,3);
assert.equal(read(E+'/attempt-005/verdict.json').status,'PASS-BOUNDED');const containers=execFileSync('/Applications/Docker.app/Contents/Resources/bin/docker',['ps','--format','{{.ID}} {{.Names}}'],{encoding:'utf8'});assert.equal(containers,fs.readFileSync(root+'/evidence/G28-R2/services-final.txt','utf8'));
const tests=spawnSync(process.execPath,['--test','scripts/fidelity/check.test.mjs'],{cwd:root,encoding:'utf8'});assert.equal(tests.status,0);save(E+'/fidelity-tests.stdout',tests.stdout);save(E+'/fidelity-tests.stderr',tests.stderr);
save(E+'/verification.json',{status:'PASS-BOUNDED',events:lines.length,one_merge_event:true,three_projection_events:true,three_later_use_events:true,exact_two_parent_additive_merge:true,target_tree_preserved:true,tests_use_disposable_worktrees:true,replays_add_no_events:true,receipt_event_and_ledger_validated:true,services_unchanged:true,no_model_calls:true,limits:'Isolated non-networked laboratory fork-test-merge/later-use proof; no production or Mattermost claim'});console.log(JSON.stringify(read(E+'/verification.json')));
