// Builder-only workshop experiment. No candidate code is attributed to Miter.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {native,save,read} from '../g22_v2/common.mjs';
process.chdir(root);const name=process.argv[2];assert.match(name??'',/^attempt-\d+$/);const dir=root+'/evidence/G27/'+name,R=root+'/runtime/g27/'+name;assert(!fs.existsSync(dir)&&!fs.existsSync(R));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(R,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});save(dir+'/opening.json',checkOpen('docs/gates/G27/plan.json'));
const files=['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md','config/workshop-contract-v1.json','src/workshop_boundary_v1.metta','src/bootstrap_workshop_boundary_v1.metta','effect_membranes/miter_workshop_v1.pl','effect_membranes/miter_process.pl','scripts/g27/run.mjs'];
const pins=files.map(p=>({path:root+'/'+p,sha256:hash(fs.readFileSync(p))}));save(dir+'/freeze.json',{files:pins,new_model_calls:0});fs.mkdirSync(dir+'/code');for(const f of files)fs.copyFileSync(f,dir+'/code/'+f.replaceAll('/','__'));
const docker='/Applications/Docker.app/Contents/Resources/bin/docker';const dockerRun=args=>execFileSync(docker,args,{encoding:'utf8',timeout:20000,maxBuffer:1024*1024});save(dir+'/docker-version.txt',dockerRun(['version','--format','{{.Server.Version}}']));
// Record only service names/IDs/status, never env or credentials.
save(dir+'/services-before.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
const seed=R+'/seed';fs.mkdirSync(seed);const git=args=>execFileSync('/usr/bin/git',['-c','core.hooksPath=/dev/null','-C',seed,...args],{encoding:'utf8'}).trim();git(['init','-b','main']);fs.mkdirSync(seed+'/extension');fs.mkdirSync(seed+'/candidate_tests');save(seed+'/extension/.gitkeep','');save(seed+'/candidate_tests/.gitkeep','');save(seed+'/CONTROL.txt','Builder-owned immutable laboratory main\n');git(['add','CONTROL.txt','extension/.gitkeep','candidate_tests/.gitkeep']);git(['-c','user.name=Miter laboratory builder','-c','user.email=miter-lab@example.invalid','commit','-m','Pin harmless G27 seed']);const base=git(['rev-parse','HEAD']);
const contracts=R+'/contracts';fs.mkdirSync(contracts);const tests={
 contract:'set -eu\ntest "$(cat /workspace/extension/message.txt)" = "hello from the isolated candidate"\nprintf "contract-passed\\n"\n',
 attacks:'set -eu\ntest ! -e /outside/secret-canary.txt\ntest ! -e /var/run/docker.sock\ntest ! -e /host-proc/1/status\ntest ! -e /workspace/.git\nif touch /outside-root 2>/dev/null; then exit 21; fi\ncat /proc/net/route\ntest "$(tail -n +2 /proc/net/route)" = ""\nif wget -T 1 -q -O /tmp/net http://192.0.2.1/; then exit 22; fi\nprintf "filesystem-secret-socket-process-network-blocked\\n"\n',
 canary:'if test -r /outside/secret-canary.txt; then cat /outside/secret-canary.txt; else printf "canary-inaccessible\\n"; fi\n',
 hang:'sleep 30\n',flood:'while :; do printf "bounded-output-probe-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\\n"; done\n'};
for(const[id,body]of Object.entries(tests))save(contracts+'/'+id+'.sh',body);
const grant={schema:'miter-workshop-grant-v1',grant_id:'grant-'+name,repository:seed,contracts,base_commit:base,tests:Object.keys(tests).map(id=>({id})),integrity:[...pins,...Object.keys(tests).map(id=>({path:contracts+'/'+id+'.sh',sha256:hash(fs.readFileSync(contracts+'/'+id+'.sh'))}))]};save(R+'/grant.json',grant);save(dir+'/grant.json',grant);
const boot=`!(import! &self "${root}/src/bootstrap_workshop_boundary_v1.metta")\n`;let n=0;const records=[];
function request(op,extra={},expected,candidate='sample',transform=d=>d){const id='r'+(++n),d=transform({schema:'miter-workshop-request-v1',request_id:id,idempotency_key:'key-'+id,grant_id:grant.grant_id,operation:op,candidate_id:candidate,...extra}),file='request-'+id+'.json';save(R+'/'+file,d);save(dir+'/'+file,d);const raw=native(dir,id,`!(result response (WorkshopRequest "${R}" "${file}"))`,boot);assert.equal(raw.length,1);const result=raw[0][2];assert.equal(result[0],'workshop-result',JSON.stringify(result));if(expected)assert.equal(result[2],expected,op+' '+id);const event=read(R+'/events/'+result[3]+'.json');records.push({request:d,result,event});return records.at(-1)}
request('create_candidate_worktree',{},'candidate-created');const written=request('write_candidate_file',{path:'extension/message.txt',contents:'hello from the isolated candidate\n'},'candidate-written');
const ledger=R+'/journal/trajectory.jsonl',beforeReplay=fs.readFileSync(ledger,'utf8');const replay=native(dir,'replay',`!(result replay (WorkshopRequest "${R}" "request-${written.request.request_id}.json"))`,boot);assert.deepEqual(replay[0][2],written.result);assert.equal(fs.readFileSync(ledger,'utf8'),beforeReplay);
request('write_candidate_file',{path:'extension/message.txt',contents:'must not overwrite'},'idempotency-conflict','sample',d=>({...d,idempotency_key:written.request.idempotency_key}));assert.equal(fs.readFileSync(R+'/candidates/sample/extension/message.txt','utf8'),'hello from the isolated candidate\n');
request('write_candidate_file',{path:'extension/message.txt',contents:'must not overwrite'},'request-id-conflict','sample',d=>({...d,request_id:written.request.request_id}));
save(R+'/prepared/key-r'+(n+1)+'.json',{standing:'Synthetic crash after prepare, before receipt'});request('write_candidate_file',{path:'extension/pending.txt',contents:'must not replay'},'workshop-recovery-required');assert(!fs.existsSync(R+'/candidates/sample/extension/pending.txt'));
request('read_candidate_file',{path:'extension/message.txt'},'candidate-read');request('list_candidate_tree',{},'candidate-tree');
for(const path of ['../CONTROL.txt','/Users/bcb/.env','CONTROL.txt','.git/config','extension/../../seed/CONTROL.txt','../contracts/contract.sh'])request('write_candidate_file',{path,contents:'inert denied probe'},'operation-denied');
fs.mkdirSync(R+'/synthetic-outside');save(R+'/synthetic-outside/secret-canary.txt','SYNTHETIC-G27-CANARY-NOT-A-CREDENTIAL\n');fs.symlinkSync(R+'/synthetic-outside',R+'/candidates/sample/extension/escape');request('write_candidate_file',{path:'extension/escape/new.txt',contents:'must not escape'},'operation-denied');assert(!fs.existsSync(R+'/synthetic-outside/new.txt'));
request('run_declared_test',{test_id:'contract',command:'anything'},'operation-denied');request('run_declared_test',{test_id:'contract',network:'host'},'operation-denied');request('run_declared_test',{test_id:'undeclared'},'operation-denied');
request('write_candidate_file',{path:'extension/no-identity.txt',contents:'never'},'request-rejected','sample',d=>{delete d.request_id;return d});request('write_candidate_file',{path:'extension/foreign.txt',contents:'never'},'request-rejected','sample',d=>({...d,grant_id:'not-this-grant'}));
request('submit_promotion_request',{},'operation-unsupported');
function inspectChecks(details){assert.equal(details.inspect_status,'exit(0)');const x=JSON.parse(details.inspect)[0],h=x.HostConfig;const failures=[];function need(ok,name){if(!ok)failures.push(name)}need(x.Config.Image===read(root+'/config/workshop-contract-v1.json').image,'image');need(x.Config.User==='501:20','unprivileged');need(h.NetworkMode==='none','network');need(h.ReadonlyRootfs===true,'readonly');need(h.Privileged===false,'not-privileged');need(h.CapDrop?.includes('ALL'),'capabilities');need(h.SecurityOpt?.some(x=>x.startsWith('no-new-privileges')),'no-new-privileges');need(h.PidMode!=='host','pid-isolation');need(h.Memory===134217728,'memory');need(h.NanoCpus===500000000,'cpu');need(h.PidsLimit===32,'pids');need(h.Tmpfs?.['/tmp']?.includes('noexec'),'tmpfs');const m=x.Mounts.filter(y=>y.Type==='bind');need(m.length===3,'mount-count');need(m.some(y=>y.Source===contracts&&y.Destination==='/contract'&&!y.RW),'readonly-contract');for(const sub of ['extension','candidate_tests'])need(m.some(y=>y.Source===R+'/candidates/sample/'+sub&&y.Destination==='/workspace/'+sub&&y.RW),'workspace-'+sub);return failures}
const positive=request('run_declared_test',{test_id:'contract'},'test-completed');assert.match(positive.event.payload.details.stdout,/contract-passed/);assert.deepEqual(inspectChecks(positive.event.payload.details),[]);
const attacks=request('run_declared_test',{test_id:'attacks'},'test-completed');assert.match(attacks.event.payload.details.stdout,/filesystem-secret-socket-process-network-blocked/);assert.deepEqual(inspectChecks(attacks.event.payload.details),[]);
const canary=request('run_declared_test',{test_id:'canary'},'test-completed');assert.equal(canary.event.payload.details.stdout,'canary-inaccessible\n');
request('run_declared_test',{test_id:'hang'},'test-incomplete-timeout');const flood=request('run_declared_test',{test_id:'flood'},'test-incomplete-output');assert.equal(flood.event.payload.details.stdout.length,16384);
// Isolated, intentionally invalid profile exposes ONLY a synthetic canary.
const args=structuredClone(canary.event.payload.details.argv);const container='miter-g27-severed-'+name;args[args.indexOf('--name')+1]=container;const imageAt=args.indexOf(read(root+'/config/workshop-contract-v1.json').image);args.splice(imageAt,0,'--mount','type=bind,src='+R+'/synthetic-outside,dst=/outside,readonly');let unsafe;
try{const stdout=dockerRun(args),inspect=dockerRun(['inspect',container]);save(dir+'/severed.json',{argv:args,stdout,inspect});assert.equal(stdout,'SYNTHETIC-G27-CANARY-NOT-A-CREDENTIAL\n');unsafe=inspectChecks({inspect_status:'exit(0)',inspect});assert(unsafe.includes('mount-count'));}finally{dockerRun(['rm','--force','--volumes',container])}
const restored=request('run_declared_test',{test_id:'canary'},'test-completed');assert.equal(restored.event.payload.details.stdout,'canary-inaccessible\n');assert.deepEqual(inspectChecks(restored.event.payload.details),[]);
const diff=request('get_diff',{},'candidate-diff');assert.match(diff.event.payload.details.diff,/hello from the isolated candidate/);request('get_test_artifact',{test_key:positive.request.idempotency_key},'test-artifact');
request('create_candidate_worktree',{},'candidate-created','neutral');request('write_candidate_file',{path:'extension/message.txt',contents:'hello from the isolated candidate\n'},'candidate-written','neutral');request('run_declared_test',{test_id:'contract'},'test-completed','neutral');request('discard_candidate',{},'candidate-archived','neutral');request('discard_candidate',{},'candidate-archived');assert(fs.existsSync(R+'/archive/sample/extension/message.txt'));assert(!fs.existsSync(R+'/candidates/sample'));
assert.equal(git(['rev-parse','refs/heads/main']),base);assert.equal(git(['status','--porcelain']),'');assert.equal(fs.readFileSync(seed+'/CONTROL.txt','utf8'),'Builder-owned immutable laboratory main\n');for(const f of pins)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);
save(dir+'/git-history.txt',git(['log','--all','--graph','--decorate','--oneline']));save(dir+'/git-worktrees.txt',git(['worktree','list','--porcelain']));git(['bundle','create',dir+'/laboratory-history.bundle','--all']);
const remaining=dockerRun(['ps','-a','--format','{{.Names}}']).trim().split('\n').filter(x=>x.startsWith('miter_g27_')||x===container);assert.deepEqual(remaining,[]);save(dir+'/services-after.txt',dockerRun(['ps','--format','{{.ID}} {{.Names}} {{.Status}}']));
let previous='GENESIS',parent=null;const lines=fs.readFileSync(ledger,'utf8').trim().split('\n');for(let i=0;i<lines.length;i++){const e=JSON.parse(lines[i]);assert.equal(e.local_sequence,i+1);assert.equal(e.previous_event_hash,previous);assert.deepEqual(e.parent_event_ids,parent?[parent]:[]);assert.equal(hash(lines[i].replace(/"event_hash":"[a-f0-9]{64}",/,'')),e.event_hash);const raw=fs.readFileSync(R+'/journal/objects/sha256/'+e.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(raw),e.payload_hash);previous=e.event_hash;parent=e.event_id}
save(dir+'/records.json',records);for(const sub of ['journal','events','receipts','prepared','states'])if(fs.existsSync(R+'/'+sub))fs.cpSync(R+'/'+sub,dir+'/'+sub,{recursive:true});fs.cpSync(R+'/archive/sample/extension',dir+'/candidate-extension',{recursive:true,dereference:false});
save(dir+'/verdict.json',{status:'PASS-BOUNDED',operations:records.length,journal_events:lines.length,exact_replay_no_effect:true,invalid_profile_detected:unsafe,containers_cleaned:true,candidates:'Recoverable runtime archive, no branch deletion',no_model_calls:true,limits:'Finite mechanical Docker containment, not kernel-proof security or Soul-generated extension authorship'});
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isSymbolicLink()?[]:e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])}save(dir+'/inventory.json',{files:walk(dir).map(path=>({path:path.slice(root.length+1),sha256:hash(fs.readFileSync(path)),bytes:fs.statSync(path).size}))});console.log(JSON.stringify(read(dir+'/verdict.json')));
