// Builder instrumentation only: finite source fixtures, worker lifecycle and independent checks.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {native,prepare,report,bind,save,read,sexp,parse,swi,petta,participants} from '../g22_v2/common.mjs';
import {cases} from '../g22_v2/cases.mjs';import {reports} from '../g22_v2/verify.mjs';
process.chdir(root);const name=process.argv[2];assert.match(name??'',/^g26-\d{3}(\/repair-\d{3})?$/);const dir=root+'/evidence/G24/'+name,trialRoot=root+'/evidence/G22/'+name;
assert(!fs.existsSync(dir)&&!fs.existsSync(trialRoot));fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(trialRoot,{recursive:true});
process.on('uncaughtException',e=>{save(dir+'/failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
save(dir+'/opening.json',checkOpen('docs/gates/G26/plan.json'));
const files=[...new Set([...participants,...read(root+'/evidence/G24/g25-002/freeze.json').files.map(x=>x.path),
 'src/development_resume_v1.metta','src/bootstrap_development_resume_v1.metta','effect_membranes/miter_development_resume_v1.pl','effect_membranes/miter_continuity.pl','src/continuity.metta','scripts/g26_v2/run.mjs'])];
const sourcePins=files.map(path=>({path:root+'/'+path,sha256:hash(fs.readFileSync(path))}));save(dir+'/freeze.json',{files:sourcePins,new_model_calls:0,chat_context:[],scope:'Laboratory native worker restart, not production daemon'});fs.mkdirSync(dir+'/code');for(const f of files)fs.copyFileSync(f,dir+'/code/'+f.replaceAll('/','__'));
const rows=cases().filter(r=>['joint-supported','seed-individual','observed-completion'].includes(r.id));const accepted=trialRoot+'/accepted';prepare(accepted,rows);const pr=report(accepted,'parent'),cr=report(accepted,'candidate');reports(rows,read(accepted+'/parent.json'),pr);reports(rows,read(accepted+'/candidate.json'),cr);bind(accepted);
const admitted=native(accepted,'admit',`!(result admit (TVExecute "${accepted}"))`);assert.equal(admitted[0][2][1][0],'trial-admissible');
const rejected=trialRoot+'/rejected',bad=read(accepted+'/candidate.json');bad.candidate_id='g26-rejected-loss';bad.constructions=bad.constructions.filter(x=>x.meaning!=='completion');prepare(rejected,rows,bad);report(rejected,'parent');report(rejected,'candidate');bind(rejected,true);const rejection=native(rejected,'reject',`!(result reject (TVExecute "${rejected}"))`);assert.equal(rejection[0][2][1][0],'trial-not-admitted');
const old=root+'/evidence/G24/g25-002/canonical',eff=dir+'/efficacy';fs.mkdirSync(eff);for(const f of fs.readdirSync(old)){if(f==='store')fs.cpSync(old+'/'+f,eff+'/'+f,{recursive:true});else if(/^(input|module-|efficacy-)/.test(f))fs.copyFileSync(old+'/'+f,eff+'/'+f)}
const data=read(eff+'/input.json');const newPaths=[...sourcePins.map(x=>x.path),eff+'/input.json',...new Set(data.invocations.map(x=>eff+'/'+x.module_file))];save(eff+'/manifest.json',{files:newPaths.map(path=>({path,sha256:hash(fs.readFileSync(path))}))});
const frame=data.invocations[7].frame;assert.deepEqual(frame,data.invocations[8].frame);save(dir+'/frame.json',{native:frame});
const eventRows=d=>fs.readFileSync(d+'/store/trajectory.jsonl','utf8').trim().split('\n').map(JSON.parse);const history=[accepted,rejected,eff].map(d=>({store:d+'/store',event_ids:eventRows(d).map(e=>e.event_id)}));const events=history.flatMap(x=>x.event_ids);
const scope=frame[1],base=read(root+'/tests/fixtures/g08_capsule_current.json');Object.assign(base,{project_id:scope[3],project_name:'Scoped expressive development',project_purpose:'Retain participation while extending faithful expression',current_goal:'Compare currently supported expressive capability using earned efficacy',current_artifact_ref:dir+'/frame.json',current_artifact_hash:hash(fs.readFileSync(dir+'/frame.json')),exact_location:'matched source cut / current three-retention encounter',last_completed_work:'Accepted compound capability and revised contextual efficacy from native trials',open_questions:['Which currently supported module best serves the sourced optional coexpression question?'],next_intended_movement:'Construct supported alternatives at the retained source cut and consult matching earned efficacy',live_tensions:['Efficacy cannot substitute for required meaning or authority'],commitments:['Retain choice, inspection and recovery as actually sourced'],relevant_event_ids:events,principal_scope:scope[2],audience_scope:scope[4],relevant_memory_ids:[],created_at:new Date().toISOString(),capsule_id:'checkpoint-current',previous_capsule_id:'checkpoint-prior',supersedes_capsule_id:'checkpoint-prior',status:'current'});
const prior={...base,capsule_id:'checkpoint-prior',previous_capsule_id:'none',supersedes_capsule_id:'none',status:'active',last_completed_work:'Prior capability trials and source cut retained',next_intended_movement:'Complete native admission and efficacy trials'};save(dir+'/prior-fixture.json',prior);save(dir+'/current-fixture.json',base);const cs=dir+'/continuity';
const capBoot=`!(import! &self (library lib_import))\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_continuity.pl" (miter_continuity_write_capsule miter_continuity_set_current))\n!(import! &self "${root}/src/continuity.metta")\n`;
const caps=native(dir,'capsules',`!(result prior (AppendContinuityCapsule "${cs}" "${root}/runtime/g07/libmiter_store_posix.dylib" "${dir}/prior-fixture.json"))\n!(result current (AppendContinuityCapsule "${cs}" "${root}/runtime/g07/libmiter_store_posix.dylib" "${dir}/current-fixture.json"))\n!(result select (SelectCurrentCapsule "${cs}" "${root}/runtime/g07/libmiter_store_posix.dylib" "${scope[3]}" "checkpoint-current"))`,capBoot);assert.deepEqual(caps.map(x=>x[2]),['capsule-appended','capsule-appended','current-capsule-selected']);
const context={schema:'miter-development-resume-v1',accepted_root:accepted,efficacy_root:eff,project_id:scope[3],capsule_store:cs,invocation_indices:[7,8],history,chat_context:[]};
function bindResume(c){save(dir+'/resume.json',c);save(dir+'/resume-manifest.json',{files:[...sourcePins,...['resume.json','frame.json'].map(f=>({path:dir+'/'+f,sha256:hash(fs.readFileSync(dir+'/'+f))}))]})}bindResume(context);
const boot=`!(import! &self "${root}/src/bootstrap_development_resume_v1.metta")\n!(add-atom &soul (protected-canary Soul))\n!(add-atom &history (protected-canary adverse-history))\n`;
const state='(state (collapse (match &derived (active-voice-v2 $r $p $c $pins) (active $r $p $c $pins))) (collapse (match &derived (nace-efficacy $s $c $p $id $t $u $roots) (belief $s $c $p $id $t $u $roots))) (collapse (match &soul $a $a)) (collapse (match &compass $a $a)))';
function tree(pid){const all=execFileSync('ps',['-axo','pid=,ppid=,comm='],{encoding:'utf8'}).trim().split('\n').map(s=>{const m=s.trim().match(/^(\d+)\s+(\d+)\s+(.+)$/);return m?{pid:Number(m[1]),ppid:Number(m[2]),command:m[3]}:null}).filter(Boolean);const ids=new Set([pid]);let changed=true;while(changed){changed=false;for(const p of all)if(ids.has(p.ppid)&&!ids.has(p.pid)){ids.add(p.pid);changed=true}}return all.filter(p=>ids.has(p.pid))}
async function run(label){const entry=dir+'/'+label+'.metta';save(entry,boot+`!(result before (dr_capture "${dir}" "${label}-before" ${state}))\n!(result resume (dr_capture "${dir}" "${label}-resume" (DRResume "${dir}")))\n!(result after (dr_capture "${dir}" "${label}-after" ${state}))\n`);save(dir+'/'+label+'-descriptor.json',read(dir+'/resume.json'));
 const child=spawn(swi,['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',entry,'silent'],{stdio:['ignore','pipe','pipe']});let out='',err='',samples=[];child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);const interval=setInterval(()=>{try{samples.push(tree(child.pid))}catch{}},50);const timeout=setTimeout(()=>child.kill('SIGTERM'),120000);const result=await new Promise(resolve=>child.on('close',(status,signal)=>resolve({status,signal})));clearInterval(interval);clearTimeout(timeout);save(dir+'/'+label+'.stdout',out);save(dir+'/'+label+'.stderr',err);const after=tree(child.pid);const observed=new Set(samples.flat().map(p=>p.pid));const surviving=execFileSync('ps',['-axo','pid='],{encoding:'utf8'}).trim().split(/\s+/).map(Number).filter(p=>observed.has(p));save(dir+'/'+label+'-process.json',{pid:child.pid,...result,samples,after,surviving});assert.equal(result.status,0,label);assert.equal(err,'',label);assert.equal(after.length,0);assert.equal(surviving.length,0);assert(samples.some(t=>t.some(p=>p.pid===child.pid)));const printed=out.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(result '));assert.equal(printed.length,3,label);const decode=t=>t.list?t.list.map(decode):Object.values(t)[0];const raw=['before','resume','after'].map(k=>{const d=read(dir+'/'+label+'-'+k+'-native.json');assert.deepEqual(decode(d.term),d.native);return ['result',k,d.native]});assert.deepEqual(raw[0][2][1],[]);assert.deepEqual(raw[0][2][2],[]);assert.deepEqual(raw[0][2].slice(3),raw[2][2].slice(3));assert.equal(raw[2][2][4].length,129);return raw}
const verify=r=>{const out=r[1][2];assert.equal(out[0],'development-resumed');const cap=out[1];assert.equal(cap[1],scope[3]);assert.equal(cap[4],'checkpoint-current');assert.deepEqual(cap[5],frame);assert.equal(cap[6],base.exact_location);assert.equal(cap[10],base.next_intended_movement);assert.deepEqual(cap[12],events);assert.deepEqual(out[2][2].map(x=>x[2]),['cycle-expression-001']);assert.equal(out[2][1].filter(x=>x[0]==='efficacy-option').length,2);assert.equal(r[2][2][1].length,1);assert.equal(r[2][2][2].length,2);return out};
const first=verify(await run('first')),restart=verify(await run('restart'));assert.deepEqual(first,restart);assert.equal(read(dir+'/first-process.json').pid===read(dir+'/restart-process.json').pid,false);
// Preserve exact complete test state before same-path missing-projection tests.
fs.cpSync(accepted,dir+'/saved-accepted',{recursive:true});fs.cpSync(eff,dir+'/saved-efficacy',{recursive:true});fs.cpSync(cs,dir+'/saved-continuity',{recursive:true});const historyPins=history.flatMap(h=>[h.store+'/trajectory.jsonl',...fs.readdirSync(h.store+'/objects/sha256').map(f=>h.store+'/objects/sha256/'+f)]).map(path=>({path,sha256:hash(fs.readFileSync(path))}));save(dir+'/history-before.json',historyPins);
const missing={active:accepted+'/active.json',efficacy:eff+'/'+fs.readdirSync(eff).find(f=>f.startsWith('efficacy-')),capsule:cs+'/projects/'+scope[3]+'/current.json'};
for(const[label,path]of Object.entries(missing)){const backup=path+'.g26-removed';const h=hash(fs.readFileSync(path));fs.renameSync(path,backup);try{const r=await run('missing-'+label);assert.equal(r[1][2][0],'development-resume-incomplete');save(dir+'/missing-'+label+'-verdict.json',{status:'EXPECTED-RECOVERY',projection:path,sha256:h,result:r[1][2],history_retained:true})}finally{fs.renameSync(backup,path)}assert.equal(hash(fs.readFileSync(path)),h);verify(await run('restored-'+label))}
bindResume({...context,invocation_indices:[8,7]});verify(await run('neutral'));bindResume(context);
const moduleProbe=native(dir,'module-binding-probe',`!(result binding (let* (($input (dr_input "${dir}")) ($accepted (index-atom $input 1)) ($invs (index-atom $input 3)) ($loaded (TVHydrate $accepted (tv_restore $accepted)))) ((DRActiveFits $accepted $invs (index-atom $input 8)) (DRActiveFits $accepted $invs ()) (DRActiveFits $accepted $invs (index-atom $input 8)))))`,boot);assert.deepEqual(moduleProbe[0][2],['true','false','true']);
const wrong={...base,principal_scope:'foreign-principal'}; // Pure native scope attack, never writes the accepted capsule.
const invs=read(dir+'/efficacy/input.json').invocations;const probe=native(dir,'scope-probe',`!(result scope (let* (($input (dr_input "${dir}")) ($cap (index-atom $input 4))) (DRCapsuleFits (resume-capsule (index-atom $cap 1) foreign-principal (index-atom $cap 3) (index-atom $cap 4) (index-atom $cap 5) (index-atom $cap 6) (index-atom $cap 7) (index-atom $cap 8) (index-atom $cap 9) (index-atom $cap 10) (index-atom $cap 11) (index-atom $cap 12) (index-atom $cap 13)) (index-atom $input 3))))`,boot);assert.equal(probe[0][2],'false');
for(const f of [...sourcePins,...historyPins])assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path);
// Independent exact-byte validation of every original and newly appended ledger.
let count=0;for(const store of [...history.map(h=>h.store),dir+'/restart-store']){const lines=fs.readFileSync(store+'/trajectory.jsonl','utf8').trim().split('\n');let previous='GENESIS';for(let i=0;i<lines.length;i++){const e=JSON.parse(lines[i]);assert.equal(e.local_sequence,i+1);assert.equal(e.previous_event_hash,previous);assert.equal(hash(lines[i].replace(/"event_hash":"[a-f0-9]{64}",/,'')),e.event_hash);const raw=fs.readFileSync(store+'/objects/sha256/'+e.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(raw),e.payload_hash);previous=e.event_hash;count++}}
save(dir+'/verdict.json',{status:'PASS-BOUNDED',verified_events:count,worker_runs:9,missing_projections:Object.keys(missing),baseline:read(root+'/evidence/G24/g25-002/canonical/summary.json').before,restarted_ranking:'cycle-expression-001',chat_context:[],model_calls:0,scope:'Fresh native laboratory processes; accepted lineage, learned efficacy and exact capsule jointly used, original evidence untouched'});
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name])}save(dir+'/inventory.json',{files:[...walk(dir),...walk(trialRoot)].map(path=>({path:path.slice(root.length+1),sha256:hash(fs.readFileSync(path)),bytes:fs.statSync(path).size}))});console.log(JSON.stringify(read(dir+'/verdict.json')));
