// Offline launcher: native MeTTa forms opportunity/intention and owns loading.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn,spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {sexp} from '../sc04/fixtures.mjs';import {scenarios,frame} from './cases.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC06\/live-\d{3}$/);assert(!fs.existsSync(out));
const prior=fs.readdirSync('evidence/SC06').filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync('evidence/SC06/'+n+'/worker-started.json'));assert(prior.length<2,'SC06 model request allocation exhausted');
fs.mkdirSync(out,{recursive:true});const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');process.on('uncaughtException',e=>{save('failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
const c=scenarios()[0],dir=root+'/'+out,id='voice-development-'+out.slice(-3);save('case.json',c);save('opening.json',checkOpen('docs/gates/SC06/plan.json'));save('grant.json',{native:c.grant,model_requests_allocated:1,prior_model_requests:prior,scope:'SC06 synthetic laboratory; no human emission or promotion'});
const petta='/private/tmp/miter-g06-petta-ae66fa8',pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');
const bootstrap=`!(import! &self "${root}/src/bootstrap_voice_development.metta")\n`;
save('prepare.metta',bootstrap+`!(let* (($a (DObserve receipt-a independent-native-audit ${sexp(frame(c.a))} ${sexp(c.ca)})) ($b (DObserve receipt-b independent-native-audit ${sexp(frame(c.b))} ${sexp(c.cb)}))) (vd_record_receipts ${sexp(dir)} ($a $b)))\n`);
const prep=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',dir+'/prepare.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:8*1024*1024});save('prepare.stdout',prep.stdout??'');save('prepare.stderr',prep.stderr??'');save('prepare-process.json',{status:prep.status,signal:prep.signal});assert.equal(prep.status,0);assert.equal(prep.stderr,'');assert(fs.existsSync(out+'/receipts.json'));assert.equal(JSON.parse(fs.readFileSync(out+'/receipts.json')).records.length,2);
const paths=['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md','constitution/soul_compass_v02.metta','src/participation.metta','src/participation_support.metta','src/grounded_language.metta','src/bootstrap_grounded_language.metta','src/relational_voice.metta','src/bootstrap_relational_voice.metta','src/voice_development.metta','src/bootstrap_voice_development.metta','effect_membranes/miter_language.pl','effect_membranes/miter_relational_voice.pl','effect_membranes/miter_voice_development.pl','effect_membranes/miter_store.pl','effect_membranes/miter_llm.pl','derived/voice-policy-seed.json','config/module-schema.json','config/local/g03-model-profiles.json',out+'/receipts.json',out+'/grant.json'];
save('manifest.json',{files:paths.map(path=>({path:root+'/'+path,sha256:hash(fs.readFileSync(path))}))});for(const path of paths.filter(p=>!p.startsWith(out+'/')&&!p.startsWith('config/local/')))save(path.replaceAll('/','__'),fs.readFileSync(path,'utf8'));
save('launcher-source.mjs',fs.readFileSync('scripts/sc06/live.mjs','utf8'));save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),profile:'qwen-local',configuration_changed:false,runtime:'PeTTa/MeTTa plus Prolog; JavaScript is offline launcher only'});
save('entry.metta',bootstrap+`!(DRun ${sexp(dir)} ${id} ${sexp(c.a.scope)} (vd_read_receipts ${sexp(dir)}) ${sexp(c.surfaces)} ${sexp(c.grant)})\n!(case-result live-callability (DTrialPlan ${id} (semantic-drift)))\n`);
const fd=fs.openSync(out+'/stdout','w'),err=fs.openSync(out+'/stderr','w'),started=performance.now(),child=spawn('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',dir+'/entry.metta','silent'],{stdio:['ignore',fd,err]});fs.closeSync(fd);fs.closeSync(err);const timeout=setTimeout(()=>child.kill('SIGTERM'),130000);const result=await new Promise(resolve=>child.on('close',(code,signal)=>resolve({code,signal,elapsed_ms:performance.now()-started})));clearTimeout(timeout);save('process.json',result);
assert.equal(result.code,0);assert.equal(fs.readFileSync(out+'/stderr','utf8'),'');assert(fs.existsSync(out+'/result.json'),'native result must be independently readable');const native=JSON.parse(fs.readFileSync(out+'/result.json')).native;save('launcher-observation.json',{...result,native_result:native,claim:'Candidate generation/quarantine, not quality or promotion'});console.log(JSON.stringify({process:result,result:native[0],quarantine:native[1],evidence:out}));assert.equal(native[0],'quarantine-result');assert.equal(native[1],'candidate-quarantined');
