// Offline disclosure-timed experiment. No test expectation enters native input.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {generate} from './unfamiliar.mjs';import {sexp,parse} from './fixtures.mjs';import {verify} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC04\/heldout-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});
const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');
process.on('uncaughtException',e=>{save('failure.json',{status:'FAIL',message:e.message,stack:e.stack,heldout_claim:'invalid for this failed version; repair requires a fresh freeze and seed'});console.error(e.stack);process.exitCode=1});
const paths=['src/grounded_language.metta','src/participation_support.metta','src/participation.metta','src/bootstrap_grounded_language.metta','effect_membranes/miter_language.pl','constitution/soul_compass_v02.metta','scripts/sc04/heldout.mjs','scripts/sc04/unfamiliar.mjs','scripts/sc04/verify.mjs','scripts/sc04/fixtures.mjs','scripts/sc04/cases.mjs','scripts/sc04/run.mjs','tests/fixtures/sc04/contract.md'];
const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();const fixed=paths.map(path=>{const bytes=fs.readFileSync(path);assert(bytes.equals(execFileSync('git',['show',commit+':'+path])),path+' must be frozen before disclosure');return {path,sha256:hash(bytes)}});
save('opening.json',checkOpen('docs/gates/SC04/plan.json'));save('freeze.json',{commit,files:fixed,before_seed:true,boundary:'Builder knows the generator and grammar; concrete seed/instances not inspected before this freeze.'});
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');
const seed=crypto.randomBytes(16).toString('hex'),cases=generate(seed);save('disclosure.json',{seed,generated_at:new Date().toISOString(),cases,model_calls:0});
for(const p of fixed)save(p.path.split('/').at(-1),fs.readFileSync(p.path,'utf8'));
const runs={};for(const arm of ['canonical','restored']){
 const entry=`!(import! &self (library lib_import))\n!(import_prolog_functions_from_file "${root}/${out}/miter_language.pl" (miter_language_tokens))\n!(import! &compass "${root}/${out}/soul_compass_v02.metta")\n!(import! &self "${root}/${out}/participation.metta")\n!(import! &self "${root}/${out}/participation_support.metta")\n!(import! &self "${root}/${out}/grounded_language.metta")\n`+cases.map(c=>`!(let $r (GroundLanguage ${[c.scope,c.nodes,c.registry,c.current,c.operations,c.target,c.budget,c.proposals].map(sexp).join(' ')}) (case-result ${c.id} $r))`).join('\n')+'\n';save(arm+'-entry.metta',entry);
 const start=performance.now(),r=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/'+arm+'-entry.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:32*1024*1024});save(arm+'.stdout',r.stdout??'');save(arm+'.stderr',r.stderr??'');save(arm+'-process.json',{status:r.status,signal:r.signal,error:r.error?.message??null,elapsed_ms:performance.now()-start});assert.equal(r.status,0);assert.equal(r.stderr,'');
 const lines=r.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(l=>l.startsWith('(case-result '));assert.equal(lines.length,cases.length);runs[arm]=Object.fromEntries(lines.map(l=>{const x=parse(l);return[x[1],x[2]]}));save(arm+'-results.json',runs[arm]);
}
for(const c of cases){try{verify(c,runs.canonical[c.id]);verify(c,runs.restored[c.id]);assert.deepEqual(runs.canonical[c.id],runs.restored[c.id]);}catch(e){e.message=c.id+': '+e.message;throw e}}
for(const f of fixed)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,'no changes after disclosure');
save('verdict.json',{status:'PASS-BOUNDED',gate:'SC04',phase:'undisclosed-generated-instances',cases:cases.length,freeze_commit:commit,pin,limits:'Generated instances inside a builder-known finite grammar/domain. No external blind review, broad language generality, live model, or effect claim.'});console.log(JSON.stringify({status:'PASS-BOUNDED',cases:cases.length,evidence:out}));
