import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn,spawnSync,execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';
import {prepare} from './prepare.mjs';
process.chdir(root);
const rel=process.argv[2];assert.match(rel??'',/^evidence\/SC03\/attempt-\d{3}$/);assert(!fs.existsSync(rel));fs.mkdirSync(rel,{recursive:true});
const save=(name,x)=>fs.writeFileSync(rel+'/'+name,typeof x==='string'?x:JSON.stringify(x)+'\n');
save('opening.json',checkOpen('docs/gates/SC03/plan.json'));
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d';assert.equal(execFileSync('git',['-C','/private/tmp/miter-g06-petta-ae66fa8','rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C','/private/tmp/miter-g06-petta-ae66fa8','status','--porcelain'],{encoding:'utf8'}).trim(),'');
save('environment.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),model_calls:0,services_touched:[],boundary:'single-process isolated local graph lab; not power-loss or general remote exactly-once'});
for(const [to,from] of [['runner.mjs','scripts/sc03/run.mjs'],['preparer.mjs','scripts/sc03/prepare.mjs'],['lab-edit.pl','scripts/sc03/lab_edit.pl'],['main.pl','scripts/sc03/main.pl'],['membrane.pl','effect_membranes/miter_undertaking.pl'],['native.metta','src/undertaking.metta']])save(to,fs.readFileSync(from,'utf8'));
const active=new Set(),checks=[],observations={};let serial=0;
const readWorld=p=>JSON.parse(fs.readFileSync(p.dir+'/world.json')).body;
// While the process is live, read only newline-committed diagnostic records.
const trace=p=>{const s=fs.readFileSync(p.dir+'/trace.jsonl','utf8');return s.slice(0,s.lastIndexOf('\n')+1).split('\n').filter(Boolean).map(JSON.parse)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function waitFor(fn,ms=12000){const start=performance.now();for(;;){const v=fn();if(v)return v;if(performance.now()-start>ms)throw Error('timed out waiting for laboratory condition');await sleep(5);}}
function command(p,args,label){const r=spawnSync('/opt/homebrew/bin/swipl',['-q','-s',...args],{encoding:'utf8',timeout:10000});fs.writeFileSync(p.dir+'/'+label+'.stdout',r.stdout??'');fs.writeFileSync(p.dir+'/'+label+'.stderr',r.stderr??'');assert.equal(r.status,0,label);assert.equal(r.stderr,'',label+' stderr');}
function init(name,options={},change=()=>{}){const p=prepare(rel+'/'+name,options);const seed=readSeed(p);change(seed);fs.writeFileSync(p.dir+'/seed.json',JSON.stringify(seed)+'\n');command(p,['scripts/sc03/main.pl','--','init',p.dir,'silent'],'init');return p;}
const readSeed=p=>JSON.parse(fs.readFileSync(p.dir+'/seed.json'));
function launch(p,label='run',deadline=15000){const out=fs.openSync(p.dir+'/'+label+'.stdout','w'),err=fs.openSync(p.dir+'/'+label+'.stderr','w');const child=spawn('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s','scripts/sc03/main.pl','--',p.dir,'silent'],{stdio:['ignore',out,err]});fs.closeSync(out);fs.closeSync(err);active.add(child);const timer=setTimeout(()=>child.kill('SIGTERM'),deadline);const started=performance.now();const done=new Promise(resolve=>child.on('close',(code,signal)=>{clearTimeout(timer);active.delete(child);const result={code,signal,elapsed_ms:performance.now()-started};fs.writeFileSync(p.dir+'/'+label+'-process.json',JSON.stringify(result)+'\n');resolve(result)}));return{child,done,label};}
function send(p,kind,amount=0,id=null){serial++;id??='control-'+serial;const event=['control',id,kind,p.seed.scope[2],p.seed.scope[3],amount];const name=String(serial).padStart(4,'0')+'-'+kind+'.json';const tmp=p.dir+'/inbox/'+name+'.tmp';fs.writeFileSync(tmp,JSON.stringify({event})+'\n');fs.renameSync(tmp,p.dir+'/inbox/'+name);return event;}
async function stop(p,run){const start=performance.now();send(p,'stop');const result=await run.done;assert.equal(result.code,0);assert.equal(fs.readFileSync(p.dir+'/'+run.label+'.stderr','utf8'),'');const latency=performance.now()-start;assert(latency<500,'stop latency');return latency;}
function edit(p,kind){command(p,['scripts/sc03/lab_edit.pl','--',p.dir,kind],'edit-'+kind);}
function verifyEffects(p){const w=readWorld(p),seen=new Set();let state=readSeed(p).edges;for(const r of w.receipts){const key=JSON.stringify(r[1]);assert(!seen.has(key));seen.add(key);assert.equal(r[2],'applied');const pending=r[4],op=pending[5];assert.deepEqual(new Set(pending[3].map(JSON.stringify)),new Set(state.map(JSON.stringify)));const after=new Set(state.map(JSON.stringify));for(const e of op[4])after.delete(JSON.stringify(e));for(const e of op[3])after.add(JSON.stringify(e));assert.deepEqual(new Set(pending[4].map(JSON.stringify)),after);state=pending[4];}assert.deepEqual(new Set(state.map(JSON.stringify)),new Set(w.edges.map(JSON.stringify)));assert.deepEqual(w.history.filter(x=>x[0]==='effect_application').map(x=>x[1]),w.receipts.map(x=>x[1]));assert(w.history.some(x=>x[0]==='native_transition'));return w;}
try{
  for(const name of ['canonical','restored']){const p=init(name),r=launch(p);await waitFor(()=>readWorld(p).state[6]==='completed');let w=verifyEffects(p);assert.equal(w.receipts.length,2);assert.deepEqual(w.receipts.map(x=>x[4][5][1]),['preserve-participation','direct-change']);observations[name]={stop_ms:await stop(p,r),receipts:2};checks.push(name+' native composition and observed completion');}
  {const p=init('renewal',{budget:1}),r=launch(p);await waitFor(()=>readWorld(p).state[6]==='awaiting-resource');let w=readWorld(p);assert.equal(w.receipts.length,1);assert.equal(w.state[5],0);const event=send(p,'renew',1);await waitFor(()=>readWorld(p).state[6]==='completed');send(p,'renew',1,event[1]);await waitFor(()=>trace(p).some(x=>x.reason==='duplicate-renewal'));w=verifyEffects(p);assert.equal(w.receipts.length,2);assert.equal(w.state[5],0);await stop(p,r);checks.push('grant boundary, explicit renewal and durable duplicate protection');}
  for(const [name,change,expected] of [['no-operator',s=>{s.operations=[];s.state[4]=[]},'waiting'],['missing-purpose',s=>{s.records=s.records.filter(x=>x[1]!=='purpose-source')},'waiting'],['already-complete',s=>{s.edges.push(['edge','artifact','revised'])},'completed']]){const p=init(name,{},change),r=launch(p);await waitFor(()=>readWorld(p).state[6]===expected);assert.equal(readWorld(p).receipts.length,0);await stop(p,r);checks.push(name+' is distinct and has no forced effect');}
  for(const complete of [false,true]){const p=init(complete?'revoked-complete':'revoked-before-work',{complete},s=>{s.grant[3]='revoked'}),r=launch(p);await waitFor(()=>readWorld(p).state[6]===(complete?'completed':'revalidation-required'));const w=readWorld(p);assert.equal(w.receipts.length,0);assert.equal(w.state[5],8);assert.equal(w.state[10][2][0],'grounded-participation');await stop(p,r);checks.push(complete?'revoked write grant still permits supported completion':'revoked write grant retains native reasoning without effect or spent allocation');}
  {const p=init('consequence-severed',{variant:'consequence-severed'}),r=launch(p);await waitFor(()=>readWorld(p).state[6]==='waiting'&&readWorld(p).receipts.length===1);assert.equal(verifyEffects(p).state[6],'waiting');await stop(p,r);checks.push('consequence-severed cannot continue the canonical undertaking');}
  console.log('SC03: composition, renewal, completion and consequence arms passed.');
  for(const severed of [false,true]){const p=init(severed?'continuity-severed':'restart',{delay:0.25}),first=launch(p,'before-crash');await waitFor(()=>readWorld(p).receipts.length===1);first.child.kill('SIGKILL');const crash=await first.done;assert.equal(crash.signal,'SIGKILL');fs.copyFileSync(p.dir+'/world.json',p.dir+'/crash-checkpoint.json');if(severed)edit(p,'continuity_severed');const second=launch(p,'after-crash');if(severed){await waitFor(()=>readWorld(p).state[6]==='revalidation-required');assert.equal(readWorld(p).receipts.length,1);}else{await waitFor(()=>readWorld(p).state[6]==='completed');const w=verifyEffects(p);assert.equal(w.receipts.length,2);assert.equal(w.state[5],6);assert.equal(w.state[11],2);}await stop(p,second);checks.push(severed?'continuity severing loses exact resumption without duplicate effects':'restart resumes source-bound work without repeating effect');}
  for(const kind of ['relevant_contact','unrelated_contact','revoke','stale_semantics','purpose_missing']){const p=init(kind,{delay:1}),r=launch(p);await waitFor(()=>readWorld(p).state[6]==='waiting-result');const t=performance.now();send(p,'pause');await waitFor(()=>readWorld(p).state[6]==='suspended');const latency=performance.now()-t;assert(latency<500);await sleep(30);assert.equal(readWorld(p).receipts.length,0);edit(p,kind);send(p,'resume');await waitFor(()=>kind==='unrelated_contact'?readWorld(p).state[6]==='completed':['relevant_contact','purpose_missing'].includes(kind)?readWorld(p).state[6]==='waiting':readWorld(p).state[6]==='revalidation-required');const w=readWorld(p);assert.equal(w.receipts.length,kind==='unrelated_contact'?2:0);observations[kind]={pause_ms:latency,stop_ms:await stop(p,r)};checks.push(kind+' causes fitting native re-entry');}
  console.log('SC03: interruption, restart, scope/version and changed-contact arms passed.');
  {const p=init('manifest-tamper');fs.appendFileSync(p.dir+'/compass.metta','; unauthorized test mutation\n');const r=launch(p),exit=await r.done;assert.equal(exit.code,1);assert.equal(readWorld(p).receipts.length,0);assert(fs.readFileSync(p.dir+'/run.stderr','utf8').length);checks.push('bootstrap detects loaded-bundle mismatch before effects');}
  {const p=init('paced-readiness',{complete:true,poll:0.04}),r=launch(p);await waitFor(()=>readWorld(p).state[6]==='completed');await sleep(500);const w=readWorld(p);assert.equal(w.receipts.length,0);const transitions=trace(p).filter(x=>x.kind==='native_transition');assert.equal(transitions.length,1);const pacing=trace(p).filter(x=>x.kind==='mechanical_pacing');assert(pacing.some(x=>x.seconds===0.1));assert(pacing.every(x=>x.progress_claim===false));assert.equal(JSON.parse(fs.readFileSync(p.dir+'/profile.json')).watchdog_turns,'none');observations.readiness={stop_ms:await stop(p,r),nonstop_transitions:1,pacing};checks.push('adaptive readiness has no mandatory lifetime, model call or invented progress');}
  {const p=init('long-run',{complete:true,poll:0,turns:10000}),r=launch(p,'run',120000);const exit=await r.done;assert.equal(exit.code,0);assert.equal(fs.readFileSync(p.dir+'/run.stderr','utf8'),'');const samples=trace(p).filter(x=>x.kind==='driver_sample');assert(samples.some(x=>x.turn===10000));const warm=samples.filter(x=>x.turn>=1000);assert(Math.max(...warm.map(x=>x.local_bytes))-Math.min(...warm.map(x=>x.local_bytes))<262144,'turn-proportional local stack growth');assert.equal(readWorld(p).receipts.length,0);observations.long_run={samples,elapsed_ms:exit.elapsed_ms};checks.push('10000 recurring native turns without retained stack growth');}
  save('verdict.json',{gate:'SC03',status:'PASS-BOUNDED',checks,observations,source_sha256:hash(fs.readFileSync('src/undertaking.metta')),limits:'Isolated local graph/undertaking engine only. No broad semantics, full Soul, live service, G22, or power-loss guarantee.'});console.log(JSON.stringify({status:'PASS-BOUNDED',checks:checks.length,evidence:rel}));
}catch(e){for(const p of active)p.kill('SIGTERM');save('failure.json',{status:'FAIL',message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1;}
