:- ensure_loaded('../../effect_membranes/miter_resume.pl').
:- initialization(main,main).
main :-
    Root='runtime/g11/base-store',Capsules='runtime/g11/base-continuity',
    miter_chroma_read_json('tests/fixtures/g08_capsule_current.json',Old),
    New=Old.put(_{capsule_id:"capsule-g11-003",previous_capsule_id:"capsule-g08-002",
      supersedes_capsule_id:"capsule-g08-002",created_at:"2026-09-02T07:00:00Z",
      relevant_event_ids:["evt-g07-witnessed-result-0003","evt-g07-fork-0004","source-g11-book-pause"]}),
    miter_cs_write('runtime/g11/book-capsule.json',New),
    append_fixture(Root,"source-g11-book-pause","project-checkpoint","2026-09-02T07:00:00Z",
       "project-g08-glass-archive",_{capsule_id:New.capsule_id,project_id:New.project_id,
       artifact_hash:New.current_artifact_hash,exact_location:New.exact_location}),
    miter_continuity_write_capsule(Capsules,'runtime/g07/libmiter_store_posix.dylib',
      'runtime/g11/book-capsule.json',CR),writeln(CR),CR=='capsule-appended',
    miter_continuity_set_current(Capsules,'runtime/g07/libmiter_store_posix.dylib',
      'project-g08-glass-archive','capsule-g11-003',SR),writeln(SR),SR=='current-capsule-selected',
    forall(member(Id-Time,["unrelated-g11-15"-"2026-09-17T07:00:00Z",
       "unrelated-g11-50"-"2026-10-22T07:00:00Z","unrelated-g11-89"-"2026-11-30T07:00:00Z",
       "unrelated-g11-90"-"2026-12-01T06:59:00Z"]),
       append_fixture(Root,Id,"unrelated-contact",Time,"unrelated-project",_{topic:"Synthetic non-book work."})),
    Registry=_{schema:"miter-project-registry-v1",projects:[_{kind:"book",
      project_id:"project-g08-glass-archive",principal_scope:"principal:g08-human",
      audience_scope:"scope:g08-private-project"}]},
    miter_cs_write('runtime/g11/project-registry.json',Registry),
    crypto_file_hash('runtime/g11/project-registry.json',Hash,[algorithm(sha256),encoding(octet)]),
    forall(member(Arm,[canonical,'chroma-off','capsule-off']),make_context(Arm,Hash)),
    current_prolog_flag(pid,Pid),miter_cs_write('runtime/g11/setup-process.json',_{pid:Pid}).
append_fixture(Root,Id,Kind,Time,Project,Payload) :-
    I=_{schema:"miter-event-intent-v1",event_id:Id,event_kind:Kind,occurred_at:Time,recorded_at:Time,
      source_surface:"g11-synthetic-timeline",source_principal:"principal:g08-human",
      audience_scope:"scope:g08-private-project",project_scope:Project,provenance_kind:"direct-contact",
      parent_event_ids:[],correlation_id:"g11-timeline",payload:Payload},
    format(atom(Path),'runtime/g11/timeline/~s.json',[Id]),miter_cs_write(Path,I),
    miter_store_append_event(Root,'runtime/g07/libmiter_store_posix.dylib',Path,R),
    writeln(R),R=='event-appended'.
make_context(Arm,Hash) :-
    format(atom(Store),'runtime/g11/~w/store',[Arm]),
    format(atom(Out),'runtime/g11/~w/outputs',[Arm]),
    directory_file_path(Out,'capsule.json',CapOut),
    format(atom(Ctx),'runtime/g11/~w/context.json',[Arm]),
    format(string(Id),'g11-~w',[Arm]),
    C=_{schema:"miter-resume-context-v1",text:"Where was I with the book?",
      request_id:Id,query_tag:Id,occurred_at:"2026-12-01T07:00:00Z",chat_context:[],
      principal_scope:"principal:g08-human",audience_scope:"scope:g08-private-project",
      registry_ref:"runtime/g11/project-registry.json",registry_sha256:Hash,
      memory_store:Store,capsule_store:"runtime/g11/base-continuity",
      output_dir:Out,capsule_output:CapOut},miter_cs_write(Ctx,C).
