// Independent stored-state and lineage verification, offline only.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {parse} from '../sc04/fixtures.mjs';import {verify} from './verify.mjs';
process.chdir(root);const read=p=>JSON.parse(fs.readFileSync(p)),outputs=p=>Object.fromEntries(fs.readFileSync(p,'utf8').replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result ')).map(l=>{const x=parse(l);return[x[1],x[2]]}));checkOpen('docs/gates/SC07/plan.json');
const dir='evidence/SC07/attempt-004/',rows=read(dir+'cases.json'),verdict=read(dir+'verdict.json'),runs={};for(const arm of verdict.arms){assert.equal(read(dir+arm+'-process.json').status,0);assert.equal(fs.readFileSync(dir+arm+'.stderr','utf8'),'');runs[arm]=outputs(dir+arm+'.stdout');assert.deepEqual(runs[arm],read(dir+arm+'-results.json'))}for(const r of rows){verify(r,runs.canonical[r.id]);verify(r,runs.restored[r.id]);assert.deepEqual(runs.canonical[r.id],runs.restored[r.id])}for(const f of read(dir+'freeze.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path);
assert.equal(runs['sever-semantics']['permission-shift'][2][0],'supported-expression-alternatives');assert.equal(runs['sever-composition']['compound-alternatives'][2][0],'expression-inquiry');assert.equal(runs['sever-joint']['joint-unavailable-in-seed'][2][0],'supported-expression-alternatives');assert.notDeepEqual(runs['sever-intention']['compound-alternatives'],runs.canonical['compound-alternatives']);
const live='evidence/SC07/live-001/',c=read(live+'candidate.json'),raw=read(live+'raw.json'),request=read(live+'request.json'),q=read(live+'generation-intention.json').native,o=read(live+'opportunity.json'),rna=read(live+'develop.json'),n=read(live+'result.json').native,timing=read(live+'timing.json');assert.deepEqual(JSON.parse(raw.choices[0].message.content),c);assert.equal(c.candidate_id,request.request_id);assert.equal(c.candidate_id,q[1]);assert.deepEqual(q[5],['opportunity',o.native]);assert.deepEqual(rna.native[3],['opportunity',o.native]);assert.equal(n[0],'quarantine-construction-result');assert.equal(n[1],'candidate-quarantined');assert.equal(n[3],'model-candidate-bound');assert.deepEqual(outputs(live+'stdout')['live-run'],['quarantine-construction-result','candidate-quarantined','stored']);assert.equal(read(live+'process.json').code,0);assert.equal(fs.readFileSync(live+'stderr','utf8'),'');assert.equal(timing.http_status,200);assert(timing.duration_ms<=120000);assert(request.body.max_tokens<=1024);assert(o.stored_at<=read(live+'worker-started.json').started_at);assert(rna.stored_at<=read(live+'worker-started.json').started_at);
const liveVerdict=verify({...read(live+'case.json'),m:c},['result',n[4],n[5]]);assert(liveVerdict.options>0);
const sourceEvents=o.native[5][1],receipts=read(live+'receipts.json').records;assert.deepEqual(new Set(sourceEvents),new Set(receipts.map(r=>r[1])));for(const b of o.native[6][1])for(const e of [b[2],b[3]]){assert(receipts.some(r=>JSON.stringify(r)===JSON.stringify(e[4])));assert.equal(e[4][6][3],'meaning-altered')}
const before=read(live+'before-spaces.json'),after=read(live+'after-spaces.json');for(const k of ['soul','history','derived','compass']){assert(before[k].length>0);assert.deepEqual(before[k],after[k])}assert.equal(before.trial.length,0);assert.deepEqual(after.trial,[['trial-voice-realization',c.candidate_id,n[2]]]);for(const f of read(live+'manifest.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256);for(const f of read(live+'lineage.json').files)assert.equal(hash(fs.readFileSync(live+f.file)),f.sha256);assert.equal(read(live+'lineage.json').parent_hash,hash(fs.readFileSync('derived/voice-realization-seed-v2.json')));
const bd='evidence/SC07/boundaries-001/',b=read(bd+'verdict.json');assert.equal(b.cases.length,17);for(const row of b.cases){const p=bd+row.name+'/',r=outputs(p+'stdout');assert.deepEqual(r.boundary,row.result);assert.equal(r['legacy-absent'],'true');assert.equal(r['trial-count'],row.name==='valid-replay'?'1':'0');assert.equal(read(p+'process.json').status,0);assert.equal(fs.readFileSync(p+'stderr','utf8'),'');if(fs.existsSync(p+'before-spaces.json')){const old=read(p+'before-spaces.json'),next=read(p+'after-spaces.json');for(const k of ['compass','soul','history','derived']){assert(old[k].length>0);assert.deepEqual(old[k],next[k])}}}
const stop=bd+'cancel/',sent=read(stop+'stop-sent.json').sent_at,observed=read(stop+'stop-observed.json').observed_at,persisted=read(stop+'cancellation.json').stored_at;assert(observed>=sent&&observed-sent<0.5);assert(persisted>=sent&&persisted-sent<0.5);
for(const file of ['src/bootstrap_voice_construction.metta','src/development_evidence.metta','src/voice_construction.metta','effect_membranes/miter_voice_construction.pl'])assert(!/DApplyRules|DTrialPlan|DGeneration|scripts\/|py-call|janus:py_call/.test(fs.readFileSync(file,'utf8')),'retired decision/runtime seam '+file);
const calls=fs.readdirSync('evidence/SC07').filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync('evidence/SC07/'+n+'/worker-started.json')).length;assert.equal(calls,1);const result={status:'PASS-BOUNDED',construction_cases:rows.length,native_arms:verdict.arms.length,boundary_cases:b.cases.length,parser_classes:3,actual_model_requests:calls,model_duration_ms:timing.duration_ms,actual_candidate_supported_expressions:liveVerdict.options,compass_atoms_unchanged:before.compass.length,protected_canaries_unchanged:3,trial_atoms_added:1,stop_observed_ms:(observed-sent)*1000,stop_persisted_ms:(persisted-sent)*1000,limits:'Finite native construction and scoped joint comparison; supplied grammar resources, not novel general language, full Soul, quality improvement, promotion, NACE or recurring-driver integration.'};if(process.argv[2]==='record'){assert(!fs.existsSync('evidence/SC07/package-verdict.json'));fs.writeFileSync('evidence/SC07/package-verdict.json',JSON.stringify(result,null,2)+'\n')}console.log(JSON.stringify(result));
