// Independent stored-state/lineage verification. Offline builder only.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';import {parse} from '../sc04/fixtures.mjs';import {verify} from './verify.mjs';
process.chdir(root);const read=p=>JSON.parse(fs.readFileSync(p));checkOpen('docs/gates/SC06/plan.json');
const readResults=p=>Object.fromEntries(fs.readFileSync(p,'utf8').replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result ')).map(l=>{const x=parse(l);return[x[1],x[2]]}));
const p='evidence/SC06/attempt-004/',arms=['canonical','sever-source','sever-revalidation','sever-family','restored'],runs={};
for(const arm of arms){assert.equal(read(p+arm+'-process.json').status,0);assert.equal(fs.readFileSync(p+arm+'.stderr','utf8'),'');runs[arm]=readResults(p+arm+'.stdout');assert.deepEqual(runs[arm],read(p+arm+'-results.json'))}
const harness=verify(read(p+'cases.json'),read(p+'modules.json'),read(p+'compiler-cases.json'),runs);assert.deepEqual(harness,read(p+'verdict.json'));
for(const f of read(p+'freeze.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path+' differs from final experiment');
const live='evidence/SC06/live-002/',before=read(live+'before-spaces.json'),after=read(live+'after-spaces.json');for(const key of ['soul','history','derived','compass']){assert(before[key].length>0);assert.deepEqual(before[key],after[key])}assert.equal(before.trial.length,0);assert.equal(after.trial.length,1);
const c=read(live+'candidate.json'),raw=read(live+'raw.json'),request=read(live+'request.json'),intention=read(live+'generation-intention.json').native,opportunity=read(live+'opportunity.json'),develop=read(live+'develop.json'),timing=read(live+'timing.json'),result=read(live+'result.json').native;
assert.deepEqual(JSON.parse(raw.choices[0].message.content),c);assert.equal(request.request_id,c.candidate_id);assert.equal(intention[1],c.candidate_id);assert.deepEqual(intention[5],['opportunity',opportunity.native]);assert.deepEqual(develop.native[3],['opportunity',opportunity.native]);assert.deepEqual(result.slice(0,2),['quarantine-result','candidate-quarantined']);assert.equal(result[3],'model-candidate-bound');assert.equal(timing.http_status,200);assert(timing.duration_ms<=120000);assert(request.body.max_tokens<=1024);
assert(opportunity.stored_at<=read(live+'worker-started.json').started_at);assert(develop.stored_at<=read(live+'worker-started.json').started_at);assert.deepEqual(after.trial[0],['trial-voice-policy',c.candidate_id,result[2]]);
const normalize=x=>Array.isArray(x)?x.map(normalize):typeof x==='number'?String(x):x;const baseline=structuredClone(runs.canonical.canonical[3]);baseline[1]=c.candidate_id;assert.deepEqual(normalize(opportunity.native),baseline);assert.deepEqual(normalize(read(live+'receipts.json').records),runs.canonical.canonical.slice(1,3));
const output=readResults(live+'stdout');assert.deepEqual(output['live-run'],['quarantine-result','candidate-quarantined','stored']);assert.equal(output['live-callability'][0],'rendering-plan');assert.equal(read(live+'process.json').code,0);assert.equal(fs.readFileSync(live+'stderr','utf8'),'');
for(const f of read(live+'manifest.json').files)assert.equal(hash(fs.readFileSync(f.path)),f.sha256,f.path);for(const f of read(live+'lineage.json').files)assert.equal(hash(fs.readFileSync(live+f.file)),f.sha256,f.file);assert.equal(read(live+'lineage.json').parent_hash,hash(fs.readFileSync('derived/voice-policy-seed.json')));
const boundary='evidence/SC06/boundaries-002/',bv=read(boundary+'verdict.json');assert.equal(bv.cases.length,11);assert.equal(bv.model_calls,0);
for(const row of bv.cases){const dir=boundary+row.name+'/',r=readResults(dir+'stdout');assert.deepEqual(r.boundary,row.result);assert.equal(read(dir+'process.json').status,0);assert.equal(fs.readFileSync(dir+'stderr','utf8'),'');assert.equal(r['trial-count'],row.name==='valid-replay'?'1':'0');assert.deepEqual(read(dir+'parse-results.json'),{truncated:'model-truncated',refusal:'model-refusal',malformed:'malformed-model-output'});
 if(fs.existsSync(dir+'before-spaces.json')){const b=read(dir+'before-spaces.json'),a=read(dir+'after-spaces.json');for(const key of ['soul','history','derived','compass']){assert(b[key].length>0);assert.deepEqual(a[key],b[key])}}
}
const stop=boundary+'cancel/',sent=read(stop+'stop-sent.json').sent_at,observed=read(stop+'stop-observed.json').observed_at,persisted=read(stop+'cancellation.json').stored_at;assert(observed>=sent&&observed-sent<0.5);assert(persisted>=sent&&persisted-sent<0.5);
const expected={'valid-replay':'candidate-quarantined','candidate-mismatch':'unproven-candidate-lineage','soul-write':'forbidden-write','external-effect':'forbidden-effect','bad-purpose-type':'malformed-schema','unknown-field':'malformed-schema','wrong-id':'wrong-schema-or-id','integrity-changed':'unproven-candidate-lineage'};for(const [name,status]of Object.entries(expected))assert.equal(readResults(boundary+name+'/stdout').boundary[1],status);
assert.deepEqual(readResults(boundary+'timeout/stdout').boundary,['development-transport-incomplete','model-timeout','stored']);assert.deepEqual(readResults(boundary+'unavailable/stdout').boundary,['development-transport-incomplete','provider-unavailable','stored']);
const nativePaths=execFileSync('git',['ls-files','src','effect_membranes'],{encoding:'utf8'}).trim().split('\n').concat(['src/voice_development.metta','src/bootstrap_voice_development.metta','effect_membranes/miter_voice_development.pl']);for(const path of nativePaths){const s=fs.readFileSync(path,'utf8');assert(!/scripts\/[^\s]*\.(?:mjs|cjs)|path\(node\)|\b(?:py-call|janus:py_call)\b/.test(s),'runtime seam '+path)}
const modelCalls=fs.readdirSync('evidence/SC06').filter(n=>/^live-\d{3}$/.test(n)&&fs.existsSync('evidence/SC06/'+n+'/worker-started.json')).length;assert.equal(modelCalls,2);
const summary={status:'PASS-BOUNDED',harness,boundary_cases:11,typed_parser_classes:3,actual_model_requests:modelCalls,final_model_duration_ms:timing.duration_ms,protected_compass_atoms:before.compass.length,protected_fixture_canaries:3,trial_atoms_added:1,cancellation_observed_ms:(observed-sent)*1000,cancellation_persisted_ms:(persisted-sent)*1000,limits:'Finite source-bound opportunity and model candidate quarantine. Not recurring-driver integration, quality, promotion, NACE or general Soul; first live partial return retained.'};
if(process.argv[2]==='record'){assert(!fs.existsSync('evidence/SC06/package-verdict.json'));fs.writeFileSync('evidence/SC06/package-verdict.json',JSON.stringify(summary,null,2)+'\n')}console.log(JSON.stringify(summary));
