// Offline native opportunity/compiler probe. No model or external effects.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {root,checkOpen} from '../fidelity/check.mjs';import {base,clone,sexp,parse} from '../sc04/fixtures.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC06\/probe-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');save('opening.json',checkOpen('docs/gates/SC06/plan.json'));save('native.metta',fs.readFileSync('src/voice_development.metta','utf8'));
const a=base(),rename=x=>Array.isArray(x)?x.map(rename):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,rename(v)])):x==='artifact'?'artifact-two':x==='person'?'person-two':x,b=rename(clone(a));
for(const rs of [b.nodes,b.registry])for(const n of rs)if(n[6][0]==='named')n[6][2]=n[6][2].replace('-two',''); // kinds are vocabulary, not entity IDs
const frame=c=>['voice-frame',c.scope,c.nodes,c.registry,c.current,c.operations,c.target,c.budget,c.proposals];const clauses=['You requested revision of ledger.','Mara must remain able to choose and restore ledger.'];const surface=[['surface-capability','VoicePolicy','retention-omission','miter-voice-policy-v1',['trial-guidance'],[]]],grant=['development-grant',a.scope,1,1024,120];save('inputs.json',{a,b,clauses,surface,grant});
const observe=(id,c)=>`(DObserve ${id} independent-native-audit ${sexp(frame(c))} ${sexp(clauses)})`;
save('entry.metta',`!(import! &self "${root}/src/bootstrap_voice_development.metta")\n!(let* (($a ${observe('receipt-a',a)}) ($b ${observe('receipt-b',b)}) ($o (DOpportunity development ${sexp(a.scope)} ($a $b) ${sexp(surface)} ${sexp(grant)})) ($i (index-atom (index-atom (index-atom $a 6) 4) 1)) ($text (DCompile $i 1))) (probe-result $a $b $o (DDevelop $o) $text (RAudit $i ${sexp(a.scope)} ${sexp(a.scope)} $text)))\n`);
const p=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s','/private/tmp/miter-g06-petta-ae66fa8/src/main.pl','--',root+'/'+out+'/entry.metta','silent'],{encoding:'utf8',timeout:30000,maxBuffer:24*1024*1024});save('stdout',p.stdout??'');save('stderr',p.stderr??'');save('process.json',{status:p.status,signal:p.signal});assert.equal(p.status,0);assert.equal(p.stderr,'');const lines=p.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(probe-result '));assert.equal(lines.length,1);const r=parse(lines[0]);save('results.json',r);console.log(JSON.stringify({a:r[1]?.[0],b:r[2]?.[0],opportunity:r[3]?.[0],events:r[3]?.[5],ground:r[3]?.[4],rna:r[4]?.[0],compiler:r[6]?.[3],clauses:r[5]}));assert.equal(r[3][0],'development-opportunity');assert.equal(r[4][0],'develop-rna');assert.equal(r[6][3],'faithful');assert.deepEqual(new Set(r[3][5][1]),new Set(['receipt-a','receipt-b']));
