// Builder-side training/counterfactual runner. Not a native runtime dependency.
import fs from 'node:fs';import assert from 'node:assert/strict';import {spawnSync,execFileSync} from 'node:child_process';import {root,hash,checkOpen} from '../fidelity/check.mjs';import {sexp,parse} from '../sc04/fixtures.mjs';import {scenarios,modules,frame,policySexp,compilerCases} from './cases.mjs';import {verify} from './verify.mjs';
process.chdir(root);const out=process.argv[2];assert.match(out??'',/^evidence\/SC06\/attempt-\d{3}$/);assert(!fs.existsSync(out));fs.mkdirSync(out,{recursive:true});const save=(p,x)=>fs.writeFileSync(out+'/'+p,typeof x==='string'?x:JSON.stringify(x)+'\n');process.on('uncaughtException',e=>{save('failure.json',{message:e.message,stack:e.stack});console.error(e.stack);process.exitCode=1});
save('opening.json',checkOpen('docs/gates/SC06/plan.json'));const rows=scenarios(),mods=modules(),compilers=compilerCases();save('cases.json',rows);save('modules.json',mods);save('compiler-cases.json',compilers);const src=fs.readFileSync('src/voice_development.metta','utf8');const files=['src/voice_development.metta','effect_membranes/miter_voice_development.pl','scripts/sc06/cases.mjs','scripts/sc06/run.mjs','scripts/sc06/verify.mjs'];save('freeze.json',{at:new Date().toISOString(),files:files.map(path=>({path,sha256:hash(fs.readFileSync(path))})),claim:'Builder-authored training/counterfactuals, no hidden-test claim'});for(const p of files)save(p.replaceAll('/','__'),fs.readFileSync(p,'utf8'));
const pin='ae66fa8e41dcd5539d614706bd4e5cfb34f9608d',petta='/private/tmp/miter-g06-petta-ae66fa8';assert.equal(execFileSync('git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),pin);assert.equal(execFileSync('git',['-C',petta,'status','--porcelain'],{encoding:'utf8'}).trim(),'');save('runtime.json',{pin,swi:execFileSync('/opt/homebrew/bin/swipl',['--version'],{encoding:'utf8'}).trim(),model_calls:0});
const variants={canonical:null,'sever-source':['(== (index-atom $r 3) independent-native-audit)','true'],'sever-revalidation':['(== (index-atom $recomputed 6) (index-atom $r 6))','true'],'sever-family':['(DSameFamily (index-atom $a 3) (index-atom $b 3))','false'],restored:null},runs={};
for(const [arm,mutation]of Object.entries(variants)){let native=src;if(mutation){assert.equal(src.split(mutation[0]).length,2);native=src.replace(...mutation)}save(arm+'.metta',native);
const bootstrap=`!(import! &self "${root}/src/bootstrap_relational_voice.metta")\n!(import_prolog_functions_from_file "${root}/effect_membranes/miter_voice_development.pl" (vd_sentence))\n!(import! &self "${root}/${out}/${arm}.metta")\n`;
const entries=rows.map(r=>`!(let* (($a (DObserve receipt-a independent-native-audit ${sexp(frame(r.a))} ${sexp(r.ca)})) ($b (DObserve receipt-b independent-native-audit ${sexp(frame(r.b))} ${sexp(r.cb)})) ($o (DOpportunity development ${sexp(r.a.scope)} ${r.records} ${sexp(r.surfaces)} ${sexp(r.grant)}))) (case-result ${r.id} (result $a $b $o (DDevelop $o))))`);
for(const m of mods)entries.push(`!(case-result module-${m.id} (DModuleValid fixture-module ${policySexp(m.m)}))`);
// Calling a quarantined data interpreter is not a comparative G22 trial.
entries.push(`!(let* (($m ${policySexp(mods[0].m)}) ($first (DQuarantine fixture-module $m model-candidate-bound)) ($again (DQuarantine fixture-module $m model-candidate-bound))) (case-result trial-call (result $first $again (DTrialPlan fixture-module (semantic-drift)) (DTrialPlan absent (semantic-drift)) (DQuarantine fixture-module $m unproven-model-candidate))))`);
for(const r of compilers)for(const v of [0,1])entries.push(`!(let* (($g (DGround ${sexp(frame(r.c))})) ($i (RIntend compiler $g)) ($text (DCompile $i ${v}))) (case-result compiler-${r.id}-${v} (result $text (RAudit $i ${sexp(r.c.scope)} ${sexp(r.c.scope)} $text))))`);
save(arm+'-entry.metta',bootstrap+entries.join('\n')+'\n');const p=spawnSync('/opt/homebrew/bin/swipl',['--stack_limit=1g','-q','-s',petta+'/src/main.pl','--',root+'/'+out+'/'+arm+'-entry.metta','silent'],{encoding:'utf8',timeout:60000,maxBuffer:64*1024*1024});save(arm+'.stdout',p.stdout??'');save(arm+'.stderr',p.stderr??'');save(arm+'-process.json',{status:p.status,signal:p.signal});assert.equal(p.status,0);assert.equal(p.stderr,'');const lines=p.stdout.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(x=>x.startsWith('(case-result '));assert.equal(lines.length,entries.length);runs[arm]=Object.fromEntries(lines.map(l=>{const x=parse(l);return[x[1],x[2]]}));save(arm+'-results.json',runs[arm]);}
const verdict=verify(rows,mods,compilers,runs);save('verdict.json',verdict);console.log(JSON.stringify({...verdict,evidence:out}));
