// Freeze the native request-shape discriminator before inference.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {execFileSync,spawnSync} from 'node:child_process';
import {root,hash,checkOpen} from '../fidelity/check.mjs';
import {native,save,read,pins,petta,sexp} from '../g22_v2/common.mjs';

process.chdir(root);const tag=process.argv[2]??'501';assert.match(tag,/^5[0-9]{2}$/);const dir=`${root}/evidence/G29/attempt-${tag}`;
assert(!fs.existsSync(dir));fs.mkdirSync(dir,{recursive:true});
process.on('uncaughtException',error=>{save(`${dir}/prepare-failure.json`,{message:error.message,stack:error.stack});console.error(error.stack);process.exitCode=1});
save(`${dir}/opening.json`,checkOpen('docs/gates/G29/R5/plan.json'));
assert.equal(execFileSync('/usr/bin/git',['-C',petta,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),'ae66fa8e41dcd5539d614706bd4e5cfb34f9608d');
const r2dir=`${root}/evidence/G29/attempt-210`,r4dir=`${root}/evidence/G29/attempt-402`,r1dir=`${root}/evidence/G29/attempt-101`;
const r2final=read(`${r2dir}/final-r2.json`).native,priorCandidate=r2final[1][1],r2input=read(`${r2dir}/input.json`).native,design=r2input[1],designPart=r2input[2];
const r4failure=read(`${r4dir}/r4-failure-verdict.json`);assert.equal(r4failure.status,'FAIL-EVIDENCE');assert(r4failure.preload_succeeded&&r4failure.schema_constrained_requests&&r4failure.crash_correlated);
const dependencies=[['artifact-obligation','bridge','valid-dict-runtime'],['artifact-obligation','bridge','authorization-before-payload'],['artifact-obligation','bridge','stable-identity'],['artifact-obligation','bridge','idempotency'],['artifact-obligation','tests','syntax'],['artifact-obligation','tests','valid-dict-runtime'],['artifact-obligation','tests','public-contract-exercise']];
const ref=file=>['evidence-ref',file,`sha256-${hash(fs.readFileSync(`${r2dir}/${file}`))}`];
const observations=[['obligation-observation','r2-bridge-dict','valid-dict-runtime','violated',ref('trial-r2.json')],['obligation-observation','r2-tests-syntax','syntax','violated',ref('trial-r2.json')],['obligation-observation','r2-tests-dict','valid-dict-runtime','violated',ref('trial-r2.json')],['representation-example','swi-dict','Config = _{server_id:s1}, get_dict(server_id, Config, SID).'],['representation-example','quoted-path',"Path = '/api/v4/posts'."]];
const experiments=[
 ['request-shape-experiment','strict-json','nemotron-local','strict-schema','full-source','does-not-discriminate','reversible','defeated','exhausted'],
 ['request-shape-experiment','plain-sentinel','nemotron-local','no-schema','sentinel-probe','discriminates-schema-vs-general','reversible','supported','available'],
 ['request-shape-experiment','remote-sentinel','remote-model','no-schema','sentinel-probe','discriminates-schema-vs-general','reversible','unsupported','not-authorized']
];
const input=['surface-request-shape-repair-input',design,designPart,priorCandidate,dependencies,observations,experiments,['surface-repair-grant','G29-R5',3,2048,300,'nemotron-local','no-schema-exact-sentinels','no-credentials'],['repair-provenance','G29-R4','attempt-402','schema-constrained-inference-defeated']];
save(`${dir}/input.json`,{native:input});fs.copyFileSync(`${r4dir}/reference-lock.json`,`${dir}/reference-lock.json`);
const stateProcess=spawnSync('/Users/bcb/.lmstudio/bin/lms',['ps'],{encoding:'utf8'});assert.equal(stateProcess.status,0);const baseline=(stateProcess.stdout??'')+(stateProcess.stderr??'');assert(baseline.includes('No models are currently loaded'));save(`${dir}/model-state-before.txt`,baseline);
const sources=['CONSTITUTION.md','MITER_SOUL_CONSTITUTIVE_SPEC_DRAFT.md','BUILD_FIDELITY_PROTOCOL.md','WORK_PROTOCOL.md','ACCEPTANCE.md','docs/gates/G29/R5/plan.json','docs/gates/G29/R5/plan.md','docs/gates/G29/R4/outcome.md','config/surface-event-v1.json','config/surface-effect-v1.json','config/mattermost-design-candidate-v1.json','config/mattermost-design-part-v1.json','config/mattermost-code-part-v1.json','config/local/g03-model-profiles.json','src/surface_design_v1.metta','src/bootstrap_surface_design_v1.metta','src/surface_extension_v1.metta','src/bootstrap_surface_extension_v1.metta','src/participation_support.metta','src/bootstrap_grounded_language.metta','effect_membranes/miter_surface_design_v1.pl','effect_membranes/miter_surface_extension_v1.pl','effect_membranes/miter_model_stream_v1.pl','effect_membranes/miter_llm.pl','effect_membranes/miter_store.pl','effect_membranes/miter_process.pl','scripts/g29/r5_prepare.mjs','scripts/g29/r5_run.mjs','scripts/g29/r5_quality.mjs','scripts/g29/r5_verify.mjs'];
const retained=[`${r4dir}/r4-failure-verdict.json`,`${r4dir}/final-r4.json`,`${r4dir}/crash-metadata-r4.json`,`${r4dir}/load-observation.json`,`${r4dir}/unload-observation.json`,`${r2dir}/r2-failure-verdict.json`,`${r2dir}/trial-r2.json`,`${r2dir}/candidate/extension/mattermost_bridge.pl`,`${r2dir}/candidate/candidate_tests/mattermost_contract_tests.pl`,`${r1dir}/design-1-observation.json`,`${r1dir}/design-1-wire.json`,...read(`${dir}/reference-lock.json`).files.map(x=>x.path)];
save(`${dir}/manifest.json`,{schema:'miter-g29-freeze-v1',files:pins([...sources.map(x=>`${root}/${x}`),...retained,`${dir}/input.json`,`${dir}/reference-lock.json`,`${dir}/model-state-before.txt`]),plan:'docs/gates/G29/R5/plan.json',plan_commit:'b59e7db29e802c1fd5f3567ef7f41b414883069e',request_shape_selection:'native',diagnostic:{max_calls:1,max_output_tokens:64,deadline_seconds:120,expected:'MITER_NEMOTRON_READY',response_format:false},artifacts:{contingent_on_exact_diagnostic:true,max_calls:2,max_output_tokens:2048,deadline_seconds:300,capture_bytes:2097152,envelope:['BEGIN_SOURCE','END_SOURCE'],response_format:false},load:{model:'nemotron-3.5-30b-a3b-antislop-ftpo-i1',gpu:'max',context:8192,ttl:900,speculative_mtp:false},credentials:[],mattermost_network:false,prior_candidate:'mattermost-r2'});
const docker='/Applications/Docker.app/Contents/Resources/bin/docker';save(`${dir}/services-before.txt`,execFileSync(docker,['ps','--format','{{.ID}} {{.Names}}'],{encoding:'utf8',timeout:20000}));
assert(!fs.existsSync(`${root}/runtime/g29/candidates/mattermost-r5`));for(const slot of [1,2,3])assert(!fs.existsSync(`${root}/evidence/G29/R5-call-${slot}.claim`));
const removed=experiments.filter(x=>x[1]!=='plain-sentinel'),ambiguous=structuredClone(experiments);ambiguous[2][7]='supported';ambiguous[2][8]='available';
const exact=['surface-diagnostic-observation','probe','eof',200,10,true,'stop','sentinel-exact',100,'MITER_NEMOTRON_READY',true],mismatch=structuredClone(exact);mismatch[7]='sentinel-mismatch';mismatch[9]='READY';mismatch[10]=false;
const boot=`!(import! &self "${root}/src/bootstrap_surface_extension_v1.metta")\n`;
const rows=native(dir,'r5-native-preflight',`!(result experiment (SXSelectExperiment ${sexp(experiments)}))\n!(result experiment-reordered (SXSelectExperiment ${sexp([...experiments].reverse())}))\n!(result experiment-removed (SXSelectExperiment ${sexp(removed)}))\n!(result experiment-ambiguous (SXSelectExperiment ${sexp(ambiguous)}))\n!(result exact-diagnostic (SXDiagnosticValid ${sexp(exact)}))\n!(result mismatch-diagnostic (SXDiagnosticValid ${sexp(mismatch)}))\n!(result targets (SXRepairTargets ${sexp(dependencies)} ${sexp(observations)}))`,boot);
const map=Object.fromEntries(rows.map(x=>[x[1],x[2]]));assert.equal(map.experiment[0],'request-shape-selected');assert.equal(map.experiment[1],'plain-sentinel');assert.equal(map.experiment[2],'nemotron-local');assert.equal(map['experiment-reordered'][1],'plain-sentinel');assert.equal(map['experiment-removed'][0],'request-shape-unresolved');assert.deepEqual(map['experiment-removed'][1],[]);assert.equal(map['experiment-ambiguous'][0],'request-shape-unresolved');assert.equal(map['experiment-ambiguous'][1].length,2);assert.equal(map['exact-diagnostic'],'true');assert.equal(map['mismatch-diagnostic'],'false');assert.deepEqual(new Set(map.targets),new Set(['bridge','tests']));
save(`${dir}/preflight-verdict.json`,{status:'PASS-BOUNDED',selected_experiment:'plain-sentinel',selected_model:'nemotron-local',reordering_neutral:true,removal_holds:true,ambiguity_unresolved:true,exact_sentinel_admitted:true,mismatch_rejected:true,native_targets:map.targets,new_model_calls:0});save(`${dir}/prepared.json`,{status:'PREPARED',selected_experiment:'plain-sentinel',selected_model:'nemotron-local',native_targets:map.targets,new_model_calls:0,baseline_model_state:'empty'});console.log(JSON.stringify(read(`${dir}/prepared.json`)));
