// Preserve the exact remote diagnostic truncation and its containment.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {root,read,save} from '../g22_v2/common.mjs';

const tag=process.argv[2]??'703',dir=`${root}/evidence/G29/attempt-${tag}`;
const run=read(`${dir}/run-verdict.json`),observation=read(`${dir}/openrouter-probe-r7-1-observation.json`).native;
assert.equal(run.status,'FAIL-EVIDENCE');assert.equal(observation[0],'openrouter-observation');assert.equal(observation[2],'diagnostic');assert.equal(observation[3],'eof');assert.equal(observation[4],200);assert.equal(observation[6],true);assert.equal(observation[7],'length');assert.equal(observation[8],'provider-response');assert.equal(observation[10],'MITER_OPENROUT');assert.equal(observation[11],'z-ai/glm-5.3');assert.equal(observation[12],'Modal');assert.equal(observation[13][2],64);
assert(fs.existsSync(`${root}/evidence/G29/R7-call-1.claim/owner.json`));for(const slot of [2,3])assert(!fs.existsSync(`${root}/evidence/G29/R7-call-${slot}.claim`));assert(!fs.existsSync(`${root}/runtime/g29/candidates/mattermost-r7`));assert.equal(read(`${dir}/secret-audit.json`).evidence_and_candidate_absent,true);assert.equal(fs.readFileSync(`${dir}/model-state-before.txt`,'utf8'),fs.readFileSync(`${dir}/model-state-after.txt`,'utf8'));assert.equal(fs.readFileSync(`${dir}/services-before.txt`,'utf8'),fs.readFileSync(`${dir}/services-after.txt`,'utf8'));
save(`${dir}/r7-failure-verdict.json`,{status:'FAIL-EVIDENCE',selected_resource:'openrouter-glm53',selected_model:'z-ai/glm-5.3',provider:'Modal',transport:'eof',http_status:200,finish_reason:'length',expected:'MITER_OPENROUTER_READY',returned:'MITER_OPENROUT',prompt_tokens:44,completion_tokens:64,total_tokens:108,reported_cost:0.0003432,claimed_calls:1,transmitted_requests:1,artifact_calls:0,artifact_guard_respected:true,credential_absent:true,local_model_state_unchanged:true,services_unchanged:true,candidate_created:false,candidate_promoted:false,consequence:'Renew only the calibrated remote grant: 256 diagnostic completion tokens and 4096 per source artifact, under fresh R8 claim identities and unchanged exact-content gates.'});console.log(JSON.stringify(read(`${dir}/r7-failure-verdict.json`)));
