!(import! &compass "/Users/claritymiter/miter/evidence/SC03/attempt-006/relevant_contact/compass.metta")
!(import! &self "/Users/claritymiter/miter/evidence/SC03/attempt-006/relevant_contact/participation.metta")
!(import! &self "/Users/claritymiter/miter/evidence/SC03/attempt-006/relevant_contact/support.metta")
!(import! &self "/Users/claritymiter/miter/evidence/SC03/attempt-006/relevant_contact/undertaking.metta")
