// Independent capture and hash/lineage review, never a runtime verdict engine.
import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {root,hash,validatePlan} from '../fidelity/check.mjs';import {save,read} from '../g22_v2/common.mjs';
process.chdir(root);const E=root+'/evidence/G28-R1';assert(!fs.existsSync(E+'/terminal-verification.json'));
const plan=validatePlan(read(root+'/docs/gates/G28/R1/plan.json'));const canonical=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
const reports=[];for(const n of ['001','002','003']){const d=E+'/attempt-'+n,W=root+'/runtime/g27/attempt-281'+n.slice(1),g=read(W+'/grant.json'),seed=W+'/seed';
 const git=args=>execFileSync('/usr/bin/git',['-c','core.hooksPath=/dev/null','-C',seed,...args],{encoding:'utf8'}).trim();assert.equal(git(['rev-parse','main']),g.base_commit);assert.equal(git(['status','--porcelain']),'');
 const rawLines=fs.readFileSync(W+'/journal/trajectory.jsonl','utf8').trim().split('\n'),rows=rawLines.map(JSON.parse);let prev='GENESIS',parent=[];const commits=[];
 for(const [i,row] of rows.entries()){assert.equal(row.local_sequence,i+1);assert.equal(row.previous_event_hash,prev);assert.deepEqual(row.parent_event_ids,parent);assert.equal(hash(rawLines[i].replace(/"event_hash":"[a-f0-9]{64}",/,'')),row.event_hash);const event=read(W+'/events/'+row.event_id+'.json');const payload=fs.readFileSync(W+'/journal/objects/sha256/'+row.payload_hash+'.json','utf8').replace(/\n$/,'');assert.equal(hash(payload),row.payload_hash);assert.deepEqual(JSON.parse(payload),event.payload);assert.equal(row.event_id,'workshop-'+row.payload_hash);prev=row.event_hash;parent=[row.event_id];if(event.payload.status==='candidate-committed')commits.push({candidate:event.payload.request.candidate_id,commit:event.payload.details.commit});assert.notEqual(event.payload.status,'promotion-proposed')}
 const candidates=[];for(const entry of commits){const c=read(d+'/candidate-'+entry.candidate.split('-').at(-1)+'.json').native;const obs=read(d+'/'+entry.candidate+'-observation.json').native;assert.deepEqual(c[2],obs[10]);const out=d+'/candidates/'+entry.candidate;fs.mkdirSync(out,{recursive:true});for(const f of c[2]){const path=W+'/candidates/'+entry.candidate+'/'+f[1];assert.equal(hash(fs.readFileSync(path)),f[3]);assert.equal(fs.readFileSync(path,'utf8'),f[2]);const target=out+'/'+f[1];fs.mkdirSync(target.slice(0,target.lastIndexOf('/')),{recursive:true});fs.copyFileSync(path,target)}assert.equal(execFileSync('/usr/bin/git',['-C',W+'/candidates/'+entry.candidate,'rev-parse','HEAD'],{encoding:'utf8'}).trim(),entry.commit);save(out+'/candidate.diff',git(['diff','--no-ext-diff','--no-textconv',g.base_commit,entry.commit,'--','extension','candidate_tests']));candidates.push({...entry,files:c[2].map(f=>({path:f[1],sha256:f[3]}))})}
 for(const sub of ['journal','events','receipts','prepared','states','request-ids'])if(fs.existsSync(W+'/'+sub))fs.cpSync(W+'/'+sub,d+'/'+sub,{recursive:true,errorOnExist:true,force:false});
 save(d+'/git-history.txt',git(['log','--all','--graph','--decorate','--format=%h %s']));git(['bundle','create',d+'/candidate-history.bundle','--all']);
 // Historical snapshots remain valid even where the live source was repaired.
 for(const p of read(d+'/freeze.json').files){const copy=d+'/code/'+p.path.slice(root.length+1).replaceAll('/','__');if(fs.existsSync(copy))assert.equal(hash(fs.readFileSync(copy)),p.sha256);else assert(p.path.includes('/config/local/'))}
 reports.push({attempt:n,new_model_calls:n==='001'?2:0,ledger_events:rows.length,main_unchanged:true,candidates});
}
const t=[1,2].map(n=>read(E+'/attempt-001/executable-'+n+'-timing.json'));assert(t.every(x=>x.transport==='eof'&&x.http_status===200&&x.elapsed_ms<300000));
const c1=read(E+'/attempt-001/candidate-1.json').native,c2=read(E+'/attempt-001/candidate-2.json').native;assert.deepEqual(c1[2],c2[2]);assert(fs.existsSync(E+'/call-1.claim')&&fs.existsSync(E+'/call-2.claim'));assert(!fs.existsSync(E+'/attempt-002/executable-2-request.json'));
const docker='/Applications/Docker.app/Contents/Resources/bin/docker',services=execFileSync(docker,['ps','--format','{{.ID}} {{.Names}} {{.Status}}'],{encoding:'utf8'});save(E+'/services-final.txt',services);const identity=s=>s.trim().split('\n').map(l=>l.split(' ').slice(0,2).join(' ')).sort();assert.deepEqual(identity(services),identity(fs.readFileSync(E+'/attempt-001/services-before.txt','utf8')));assert(!services.includes('miter_g27_'));
for(const [p,h] of Object.entries(plan.controls))assert.equal(hash(fs.readFileSync(root+'/'+p)),h);for(const f of plan.preserved)assert.equal(hash(fs.readFileSync(root+'/'+f.path)),f.sha256);
save(E+'/terminal-verification.json',{status:'BLOCKED',reason:'Both complete model candidates pass six fixed tests and fail the candidate-authored smoke; renewal required. No promotion.',actual_model_calls:2,model_ms:t.map(x=>x.elapsed_ms),identical_candidate_files:true,reports,repair_replay:read(E+'/attempt-003/verdict.json'),boundaries:read(E+'/attempt-003/boundary-verdict.json'),native_quality:read(E+'/quality-003/verdict.json'),user_services_unchanged:true,controls_unchanged:true,preserved_G22_unchanged:true,not_promoted:true});
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(p+'/'+e.name):[p+'/'+e.name]);save(E+'/all-attempts.json',{files:walk(E).filter(p=>!p.endsWith('/all-attempts.json')).sort().map(path=>({path:path.slice(root.length+1),sha256:hash(fs.readFileSync(path))}))});console.log(JSON.stringify({status:'SEALED-BLOCKED',actual_model_calls:2,reports}));
