!(import! &self "/Users/claritymiter/miter/src/bootstrap_surface_design_v1.metta")
!(import_prolog_functions_from_file "/Users/claritymiter/miter/effect_membranes/miter_surface_extension_v1.pl"
 (sx_name sx_part_name sx_repair_name sx_old_file sx_model sx_part_model sx_repair_model sx_repair_model_r4 sx_preload sx_unload sx_save sx_materialize sx_scan sx_syntax sx_trial))
!(import! &self "/Users/claritymiter/miter/src/surface_extension_v1.metta")
